### ISSUE TITLE
Ticket dependency delete confirmation - don't delete button click

### ISSUE THREAD

**Issue by afranjin** [django-helpdesk/django-helpdesk#1000]
**Describe the bug**
After add dependency to ticket and then want remove the confirm modal append and on do not delete 404 not find. Fixed wrang path on button click.

**To Reproduce**
Ticket dependency - do not delete 404
Steps to reproduce:
1.Log in with user(admin-role)
2.Helpdesk
3.All Tickets
4.Click any Ticket
5.Add Ticket Dependency
6.Delete Ticket Dependency
7.Don't Delete

Page not found (404)
Request Method: | GET
-- | --
http://127.0.0.1:8080/tickets/12/dependency/

**Expected behavior**
Need to redirect to ticket edit after button do not delete is clicked.

**Desktop (please complete the following information):**
 - OS:MacOs - M1
 - Browser chrome
 - Version 98.0.4758.109 (Official Build) (arm64)

**Comment by gwasser** [comment]
Thank you! This should be fixed now that #1001 is merged, so I will close this ticket.
