### ISSUE TITLE
Django 4 Support.

### ISSUE THREAD

**Issue by nickmccullum** [django-helpdesk/django-helpdesk#1002]
Hello,

I am going to be working on upgrading a project to Django 4 using a fork of `django-helpdesk`. If we run it successfully in production for a few weeks, are you open to merging in our fork and releasing a version of this project with official Django 4 support?

Thanks,
Nick

**Comment by nickmccullum** [comment]
@gwasser as a heads up, everything is working well on our fork in staging environment - we are deploying the Django-4 compatible fork tomorrow!

**Comment by gwasser** [comment]
thanks for the update @nickmccullum! I'm glad to hear the Django 4 upgrade is looking good, I'm looking forward to seeing it! Hopefully that can help us do another push to resolve some bugs that have been hanging around for a while.

**Comment by gwasser** [comment]
#1009 PR for this! Thank you @nickmccullum !

**Comment by gwasser** [comment]
This was previously merged into `unstable` and will be available in 0.4.0 release. Closing this ticket now.

**Comment by gwasser** [comment]
Definitely! A PR for Django 4 support would be most welcome. Thank you.
