### ISSUE TITLE
Django 4 / django-helpdesk 0.4 release to-dos

### ISSUE THREAD

**Issue by gwasser** [django-helpdesk/django-helpdesk#1010]
In #1009 I wrote:

> Thank you so much for this! I think the best way to proceed is to actually rebase and merge this into the `unstable` branch for the 0.4 release. My thinking is that the current 0.3 release supports Django 2.2 -> 3.2. Some of the syntax changes here might break the Django 2.2 support, so instead let's do a 0.4 release that supports Django 3.2 -> 4.2 (when 4.2 LTS comes out) so that users have a nice upgrade path. I'd be ok with doing a 0.4 release sooner rather than later, with less new features, to focus on bugfixes and just getting something that supports Django 4 out the door. Then we can use the 0.5 release for more new features.

What do folks think about this plan? If so, what do y'all think needs to be prioritized for a 0.4 release in the near future, and what should be saved for the 0.5 release development period?

**Comment by gwasser** [comment]
There's a 0.4.0 milestone tag now with tickets, if folks want to look thru and let me know which bugfixes or new features they'd like to work on, that would be helpful. No release date in mind yet, just thinking much quicker than the 0.3 release! So my question would be, what seems doable in the next month or two let's say? Otherwise we'll kick tickets back to the 0.5 release.

**Comment by nickmccullum** [comment]
@gwasser any update on this? We'd like to move away from using our fork of the repository in production as soon as possible. So far no issues. :)

**Comment by gwasser** [comment]
Thanks for checking in @nickmccullum and getting this patch in! I haven't heard too much feedback so I am assuming there's no big showstopper bugs. If so I'll try to get this released in the next week or so once I clean up some documents. I think we'll need to keep the 0.3.x and 0.4.x releases in support until the Django 4.2 LTS release is out so need the documentation to reflect that.

**Comment by anust** [comment]
@gwasser is there a rest API to respond to a ticket with details?

**Comment by SALIMA534** [comment]
@gwasser Thank you for considering to support Django 4+ version because we are planning to use your package to create help app in our application. Could you let us know approximate time frame to release new version of this package.

**Comment by nickmccullum** [comment]
@gwasser any updates on the Django 4 release?

**Comment by gwasser** [comment]
@anust the API does not support adding responses just yet, only creating and modifying the ticket itself. this could be something to add in future releases.

@SALIMA534 @nickmccullum I've unfortunately been a bit bogged down in other responsibilities but would expect to pull together a release this weekend. Help appreciated to update the documentation for Django 4, if you have time to look it over and submit a PR! I'm not well-read on the Django 3->4 changes yet so not sure if our docs need to change much.

**Comment by SALIMA534** [comment]
Hi @gwasser Hope your weekend went well. Please let us know when Django 4+ version support is available?

**Comment by gwasser** [comment]
@SALIMA534 @nickmccullum please note I have packaged and released django helpdesk 0.4.0 now. let me know if there are any immediate release concerns, please open a new ticket for any bug reports.

My plan is for us to use the 0.4 release primarily to do Django 4.x support and clean up work. Some code dates back to the original Django release so we need to look at modernizing it and getting ready for new features. New features will be pushed back to the 0.5 release which I'd expect to support and come out around the same time that Django 4.2 LTS is released.

Thank you everyone for testing!
