### ISSUE TITLE
Disable ticket fields

### ISSUE THREAD

**Issue by Mte90** [django-helpdesk/django-helpdesk#1012]
The idea is to disable fields to be showed and filled by the users like:

* ~~Priority~~
* ~~Dependencies~~
* ~~Time spent~~
* ~~Due Date~~
* ~~Is this update public (a way to set a default value for this)~~

Reading the docs (the settings.py of demo isn't complete): https://django-helpdesk.readthedocs.io/en/0.2.x/settings.html#options-for-public-ticket-submission-form

This 2 fields doesn't have options:

* Dependencies
* Time spent

**Comment by gwasser** [comment]
Does the PR #1011 cover the missing fields or is this something that still needs done?

**Comment by Mte90** [comment]
No doesn't involve that stuff. In this case I preferred to open the ticket before to do the code..
