### ISSUE TITLE
403 error on demo

### ISSUE THREAD

**Issue by Benbb96** [django-helpdesk/django-helpdesk#1016]
It seems like all forms on the demo app generate a 403 error (CSRF Token).  
See [the login page](http://django-helpdesk-demo.herokuapp.com/login/) or [the ticket creation form](http://django-helpdesk-demo.herokuapp.com/tickets/submit/)

There may be some bug with the SECRET_KEY ?

**Comment by gwasser** [comment]
I updated the demo to run on the latest release but still get the CSRF error. I don't think there's a problem with the secret key, or at least I haven't changed anything recently so I'd expect it to still work.

**Comment by Benbb96** [comment]
Could it be some settings to update for CSRF ? [CSRF_USE_SESSIONS](https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-use-sessions) or [CSRF_COOKIE_HTTPONLY](https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-cookie-httponly)

**Comment by gwasser** [comment]
@Benbb96 it seems to be working now. I could login as the demo user without any CSRF errors. It wasn't using HTTPS the other day for some reason, but the updated configuration seems good now. I'll close this but feel free to open if for some reason it isn't totally resolved.

**Comment by Benbb96** [comment]
Ok, I think that's because the link in the readme redirected me to the HTTP page, and I confirm it is still not working. But in HTTPS, yes it might has always been working!
