### ISSUE TITLE
Max Ticket number value 

### ISSUE THREAD

**Issue by Asutherland8219** [django-helpdesk/django-helpdesk#1019]
Hey our helpdesk is reaching close to 10k tickets and I was wondering if anyone knew what happens when we hit the 10k mark? Does the value continue as 10000 or will it reset to 0001 and potentially overwrite the existing 0001 ticket? 
![image](https://user-images.githubusercontent.com/60415557/173058481-eb68e35c-2732-4e68-ba25-024c06dec8df.png)

**Comment by timthelion** [comment]
Great that you're getting so much good use out of it. As far as I know helpdesk supports up to 4 billion tickets. Or 2³² - 1

**Comment by Asutherland8219** [comment]
@timthelion bit of a double edge sword that; great we are using it so much but also means we have quite a few bugs ha. Thanks for the response! Smooth sailing.

**Comment by Asutherland8219** [comment]
Great thanks!
