### ISSUE TITLE
0.4.1 release to fix missing import?

### ISSUE THREAD

**Issue by ilikerobots** [django-helpdesk/django-helpdesk#1028]
Hello, I believe the missing import issue fixed in  [6a1f4304964df6fb1c880ad02d2530a6d5b805a6] warrants a 0.4.1 release.  As far as I can tell, this affects the 0.4.0 release, preventing the fetching of emails.  I'm currently working around by pulling directly from stable in git instead of the pypi release.

**Comment by gwasser** [comment]
Yep, @ilikerobots the 0.4.1 release has been tagged and put on pypi.
