### ISSUE TITLE
Incorrect requerments

### ISSUE THREAD

**Issue by IvanovIvan1900** [django-helpdesk/django-helpdesk#1031]
**Describe the bug**
In requirements.txt not correct value

**To Reproduce**
1. Fork repo
2. clone repo to local disk
3. make venv
4. go to folder project
5. run "make rundemo"
6. all installation
**Expected behavior**
after installation go to browser open 127.0.0.1:8080

and this is did't work.
first issue - install django 4, and hey didn't work
two issue - install markdown latest version, but in version 3.0 deprecated md_global and if you open ticket to get error. 
https://github.com/Python-Markdown/markdown/blob/master/docs/change_log/release-3.0.md?ysclid=l5v68kuq2p348423531

**solution:**
replace in requirements.txt
Django>=2.2     on  Django>=2.2,<=4.0
markdown  on  markdown<3.0

sorry for my english ))

**Comment by gwasser** [comment]
See #929 . Closing this ticket as a duplicate for issues with the demo script. Thanks for reporting!
