### ISSUE TITLE
OAuth2 support for email

### ISSUE THREAD

**Issue by John-Schreiber** [django-helpdesk/django-helpdesk#1044]
Microsoft is discontinuing support for basic, password authentication, and other providers are, too. Is there a plan to allow oauth2 for SMTP and IMAP login?

**Comment by gwasser** [comment]
This is a good idea. No plan yet, but maybe we can simply add `django-oauth-toolkit` dependency to add this functionality fairly easily? (https://django-oauth-toolkit.readthedocs.io/en/latest/)

**Comment by John-Schreiber** [comment]
Here are the documents from MS: https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth

I've used the MSAL library successfully for other projects, I'll take a look.

**Comment by uhurusurfa** [comment]
Is this about user login to Helpdesk or the authentication mechanism for receiving and sending emails as part of automated Helpdesk processing? There is a move towards passwordless access to applications for users via the UI but it will require using some form of hardware device.
If you want to use OUATH for authenticating machines (sending and receiving emails on the backend), you still need an identity provider server but you must set up a shared secret token which effectively serves as your password.
OUATH is generally an SSO mechanism and requires an identity provider server to authenticate against. Small businesses will continue to use a user ID and password for years to come and adding a 2FA option for Django Helpdesk would be a benefit from a security standpoint.
It is unclear how organisations intend to support sending and receiving of emails via an app (such as what is done in Helpdesk)  in the future but for instance, Google use an app specific access token that serves the same purpose as the OAUTH shared secret and is effectively the password.

**Comment by gwasser** [comment]
I was personally thinking SSO but maybe that's not what @John-Schreiber has in mind? I'm for adding 2FA as well.

**Comment by John-Schreiber** [comment]
I'm looking for using Oauth to authenticate Helpdesk to our email provider, as they have depreciated password authentication.

**Comment by John-Schreiber** [comment]
I have a quick and dirty  test of authenticating an office365 imap account with Oauth2 working.
I will work on integrating this, and make it work with SMTP and POP. I have limited resources to test with other providers, but I will try google. 

based on:
https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth

https://msal-python.readthedocs.io/en/latest/

https://github.com/AzureAD/microsoft-authentication-library-for-python/tree/dev/sample


The configuration:
a file named config.json, with the following properties:

```json
{
    "authority": "https://login.microsoftonline.com/Enter_the_Tenant_Name_Here",
    "client_id": "your_client_id",
    "secret": "The secret generated by AAD during your confidential app registration",
    "scope": ["https://outlook.office365.com/.default"],
    "server":"outlook.office365.com",
    "port": 993
}
```
```python

#requires: https://pypi.org/project/msal/

import imaplib
import logging
import msal
import json

log = logging.getLogger()
log.setLevel("DEBUG")
config = json.load(open("config.json"))

app = msal.ConfidentialClientApplication(
    client_id=config["client_id"],
    authority=config["authority"],
    client_credential=config["secret"],
)
result = app.acquire_token_for_client(scopes=config["scope"])


if token := result.get("access_token"):
    log.info("Token Obtained")
else:
    log.info(result.get("error"))
    log.info(result.get("error_description"))
    log.info(result.get("correlation_id"))
    exit()

mail = imaplib.IMAP4_SSL(host=config["server"], port=config["port"])
mail.debug = 4
mail.authenticate(
    "XOAUTH2",
    lambda x: f"user={config['username']}\x01auth=Bearer {token}\x01\x01".encode(),
)
print(mail.list())

```

**Comment by uhurusurfa** [comment]
Note that OAUTH is an international standard and as such the implementation will be the same for any provider supporting OAUTH (specifically OAUTH2) .
So instead of using the Micorosft library, we would use the Django OAUTH toolkit which will have the OAUTH protocol implementation.
The "client_id", "scope", "authority"  and "secret" parameters in your JSON file are standard OAUTH parameters.
The Django OAUTH toolkit does support the concept of a trusted application to bypass the authorisation step that is part of the user experience for SSO.

A post on this issue which is not specifically about a trusted app connecting to the email server:
https://stackoverflow.com/questions/45289949/using-oauth-to-authenticate-office-365-graph-users-with-django

There is also the allauth django package that mentions connections to various backends:
https://django-allauth.readthedocs.io/en/latest/providers.html#microsoft-graph

**Comment by John-Schreiber** [comment]
Here is the generic version, I will try this with google. 


based on:
https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth


The configuration:
a file named config.json, with the following properties:

```json
{
    "token_url": "https://login.microsoftonline.com/Enter_the_Tenant_Name_Here/oauth2/v2.0/token",
    "client_id": "your_client_id",
    "secret": "The secret generated by AAD during your confidential app registration",
    "scope": ["https://outlook.office365.com/.default"],
    "server":"outlook.office365.com",
    "port": 993
}
```
```python
import imaplib
import json
import logging

from oauthlib.oauth2 import BackendApplicationClient
from requests_oauthlib import OAuth2Session

log = logging.getLogger()
log.setLevel("DEBUG")
config = json.load(open("config.json"))

client = BackendApplicationClient(
    client_id=config["client_id"],
    scope=config["scope"],
)

oauth = OAuth2Session(client=client)
token = oauth.fetch_token(
    token_url=config["token_url"],
    client_id=config["client_id"],
    client_secret=config["secret"],
    include_client_id=True,
)

mail = imaplib.IMAP4_SSL(
    host=config["server"],
    port=config["port"],
)
mail.debug = 4
mail.authenticate(
    "XOAUTH2",
    lambda x: f"user={config['username']}\x01auth=Bearer {token['access_token']}\x01\x01".encode(),
)
print(mail.list())
```

**Comment by IvanovIvan1900** [comment]
> Note that OAUTH is an international standard and as such the implementation will be the same for any provider supporting OAUTH (specifically OAUTH2) . So instead of using the Micorosft library, we would use the Django OAUTH toolkit which will have the OAUTH protocol implementation. The "client_id", "scope", "authority" and "secret" parameters in your JSON file are standard OAUTH parameters. The Django OAUTH toolkit does support the concept of a trusted application to bypass the authorisation step that is part of the user experience for SSO.
> 
> A post on this issue which is not specifically about a trusted app connecting to the email server: https://stackoverflow.com/questions/45289949/using-oauth-to-authenticate-office-365-graph-users-with-django
> 
> There is also the allauth django package that mentions connections to various backends: https://django-allauth.readthedocs.io/en/latest/providers.html#microsoft-graph

Hi, maybe use this is library ?
https://github.com/dolfim/django-gmailapi-backend?ysclid=l6rfojllny790800696

**Comment by gwasser** [comment]
@IvanovIvan1900 is there a reason you need a gmail-specific library? I think ideally we'd support oauth/sso so that it could  be used with any provider, microsoft, google, etc.

**Comment by IvanovIvan1900** [comment]
> @IvanovIvan1900 is there a reason you need a gmail-specific library? I think ideally we'd support oauth/sso so that it could be used with any provider, microsoft, google, etc.

I'm new to this issue, but I understand that different providers have different settings (token receiving address, etc.) is there some kind of universal solution? Otherwise, if you register for each provider, plus storing this data in a database, it will be a large amount of code

**Comment by gwasser** [comment]
I believe using an OAUTH library would be a universal solution, but I'm also not an expert in it.

**Comment by IvanovIvan1900** [comment]
> I believe using an OAUTH library would be a universal solution, but I'm also not an expert in it.

maybe you're right. This question needs clarification.

**Comment by uhurusurfa** [comment]
OAUTH is not the only SSO solution out there and not everybody uses OAUTH so it is not a universal solution. 
OAUTH itself has been adopted as an international standard (OAUTH2 is the most current implementation) and there can be a generic solution for all SSO providers that implement the OAUTH standard correctly but you still have to be able to plug in other SSO soltions.

**Comment by uhurusurfa** [comment]
This PR adds support for OAUTH thouygh only tested with Office 365: #1088

**Comment by buoncri** [comment]
It seems HELPDESK_OAUTH is not in docs ... if someone agree i will add in settings section, before or after [Default E-Mail Settings]

**Comment by uhurusurfa** [comment]
> It seems HELPDESK_OAUTH is not in docs ... if someone agree i will add in settings section, before or after [Default E-Mail Settings]

Yes that would be fine and the contribution appreciated.
