### ISSUE TITLE
Heroku may be going away, need new demo site

### ISSUE THREAD

**Issue by gwasser** [django-helpdesk/django-helpdesk#1051]
Received an email from Heroku "Starting November 28, 2022, we plan to stop offering free product plans and plan to start shutting down free dynos and data services."

We have relied on a free dyno / free starter database to run the demo site. If this indeed is true, then we will need to close the heroku account and find a different host if possible. To use heroku after November would cost something like $200 a year unless they announce some kind of support for open source projects.

Any thoughts?

**Comment by gwasser** [comment]
Here's the announcement: https://blog.heroku.com/next-chapter

**Comment by nickmccullum** [comment]
Was very sorry to see this news. 

@gwasser , my company would be willing to spin up a small DigitalOcean server to run this demo if you think that would be a feasible solution. If not, I know that Railway (railway.app) has free tiers as well, and they are friendly to open source (evidenced by their kickback program: https://railway.app/open-source-kickback). 

Happy to help with this migration however I can!

**Comment by gwasser** [comment]
thank you for the offer @nickmccullum! DigitalOcean could be a solution, I'm not familiar with it as much, but appreciate the offer. I wasn't aware of Railway, thanks for the link! Since we have until November it's not a giant rush to change from Heroku but something to keep in mind if there's any other comments from folks working on this project before we make a decision.

**Comment by Benbb96** [comment]
I first deployed my website on [PythonAnywhere](https://www.pythonanywhere.com/) with the free plan and it was ok but then I needed more feature and took the hacker plan (5$/month).

I believe [Replit](https://replit.com/) can also let you host Python/Django projects for free but I've never tested.

**Comment by Mte90** [comment]
Reading the news in the bottom it is written that for OSS projects will be still available, is enough to request it.

Another point can be that we improve the CI to push changes on heroku and also for the documentation https://github.com/django-helpdesk/django-helpdesk/issues/1042 with a switch to a different service?

**Comment by gwasser** [comment]
Thanks @Mte90 I saw the note at the bottom about open source. It wasn't clear to me that they'd still give dynos/database to open source, it sounded like it was talking about a CI pipeline. But I suppose it won't hurt for me to send an email and ask!

**Comment by gwasser** [comment]
I contacted Heroku at their open source email at the bottom and got:

"We are in the process of finalizing the selection criteria and
will contact you when we are ready to start the process; we anticipate
this as no later than Dreamforce."

So unclear if we will qualify or not.

**Comment by nickmccullum** [comment]
Dreamforce is September 20-22 this year, as an FYI.

**Comment by gwasser** [comment]
Heroku has not created any kind of free tier or open source support and is shutting down the existing free services at end of November. I have closed out our Heroku account so the demo site is now closed. If others wish to support a new demo site, please speak with maintainers here about it, but for now there is no more demo website. See #1058.

Just as a note, in the last year or two, the demo site has been filling with spam reports faster and faster, I'd have to clear out our database like once a week at this point. It would be a fantastic feature to enable some kind of anti-spam captcha on the public report page in a future release.
