### ISSUE TITLE
How to set staff_url in tickets?

### ISSUE THREAD

**Issue by aaminahassan** [django-helpdesk/django-helpdesk#1052]
Where in helpdesk admin i can set staff_url, or ticket.url to view tickets online from an email. Everytime I set it it is redirected to http://example.com/

**Comment by Mte90** [comment]
https://django-helpdesk.readthedocs.io/en/0.3/configuration.html

Point 6

**Comment by aaminahassan** [comment]
Thanks, its done, Please tell me the necessary settings for get_email, as till now i have not been able to receive email. I can send email using smtp , when i add a ticket through UI.

**Comment by Mte90** [comment]
Did you checked the documentation about how to configure the email?

**Comment by aaminahassan** [comment]
where is it plz? I did all through postfix

**Comment by Mte90** [comment]
The link I shared to you is the documentation for Django Helpdesk check there but doesn't explains how to configure a email server. For that you need to look outside this project.

**Comment by aaminahassan** [comment]
if you have followed a tutorial that helps, plz share link. Also I have only enabled smtp that is out of the box.

**Comment by Mte90** [comment]
I am closing as this is not a support request for django helpdesk

**Comment by aaminahassan** [comment]
ok, thanks for your input
