### ISSUE TITLE
Zip file as an attachment is required. 

### ISSUE THREAD

**Issue by aaminahassan** [django-helpdesk/django-helpdesk#1057]
In create new ticket, please add zip as attachment other than plain text (.txt), a document (.pdf, .docx, or .odt), or screenshot (.png or .jpg) .

**Comment by uhurusurfa** [comment]
Please feel free to submit a pull request if you have the skills to do the necessary code enhancements and add a unit test.

**Comment by uhurusurfa** [comment]
To support this you can set VALID_EXTENSIONS to the list of extensions you want to support.

By default it is:
`['.txt', '.asc', '.htm', '.html', '.pdf', '.doc', '.docx', '.odt', '.jpg', '.png', '.eml']`

**Comment by uhurusurfa** [comment]
Add this to your project settings.py file:
`VALID_EXTENSIONS=['.txt', '.asc', '.htm', '.html', '.pdf', '.doc', '.docx', '.odt', '.jpg', '.png', '.eml','.zip']`
