### ISSUE TITLE
TypeError: Signal.__init__() got an unexpected keyword argument 'providing_args'

### ISSUE THREAD

**Issue by madhav-dhungana** [django-helpdesk/django-helpdesk#1061]
File "venv\lib\site-packages\pinax\invitations\models.py", line 8, in <module>
    from .signals import invite_accepted, invite_sent, joined_independently

  File "venv\lib\site-packages\pinax\invitations\signals.py", line 3, in <module>
    invite_sent = django.dispatch.Signal(providing_args=["invitation"])

TypeError: __init__() got an unexpected keyword argument 'providing_args'

**Comment by Mte90** [comment]
What is the python version you used?

**Comment by madhav-dhungana** [comment]
I am using Python 3.8.5
and Django 4.1.2

**Comment by uhurusurfa** [comment]
Not sure how you managed to install Pinax (teams and invitations) as it is not compatible with Django 4 yet but possibly that is your problem.
https://pypi.org/project/pinax-teams/
https://pypi.org/project/pinax-invitations/

**Comment by nickmccullum** [comment]
Here are two django 4-compatible forks that you can use:
```
git+ssh://git@github.com/passiv/pinax-teams.git@d27004a2b3f88dec030c197d47c448d5852ae2ae#egg=pinax_teams
git+ssh://git@github.com/passiv/pinax-invitations.git@c3194cd1b3cc92a1d706b1f3b018d58948ed5cb2#egg=pinax_invitations
```
