### ISSUE TITLE
Excel files as Valid uploads

### ISSUE THREAD

**Issue by brucegibbins** [django-helpdesk/django-helpdesk#1065]
Hi,

I noticed that the validator module excludes other Microsoft Office files such as Excel (.xls, .xlsx), Visio, PowerPoint etc. Is/Was there a reason for this? I have discovered I can override this with the VALID_EXTENSIONS setting. But I am curious if there was a conscious decision to exclude these from the start?

Thanks in advance.

**Comment by uhurusurfa** [comment]
I don't think anyone who was part of the original software team is on this project so suspect  it will remain a mystery.

**Comment by gwasser** [comment]
Mostly just to restrict uploads to simplest file formats least likely to be security issues. But of course to do that properly it needs to be a more sophisticated check than what we have implemented right now. So the filter could probably be expanded to cover more common file formats if there is interest.
