### ISSUE TITLE
Support for Django 4+

### ISSUE THREAD

**Issue by OmerFI** [django-helpdesk/django-helpdesk#1068]
This project doesn't support Django 4+

If you try to run it with django 4+, you get this error:
```
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' 
```

I think it's time to upgrade this project to support django v4+

**Comment by uhurusurfa** [comment]
There are dependent projects that we are trying to get upgraded to support Django 4 before we can make this project support Django 4

**Comment by brucegibbins** [comment]
Hi @uhurusurfa, I was wondering if you could shed some light on the 'dependent projects' and if there was any way assistance could be provided to get them upgraded? I am also keen to move to Django 4.x.
thanks

**Comment by uhurusurfa** [comment]
It is the Pinax Teams plugin and its dependencies that are a problem.
I have managed to get myself added as a contributor and need to find the time to upgrade those apps.
If you are not using the teams plugin then Helpdesk should already work in Django 4.
If you want to raise PR's for any pof the dependent projects to make them Django 4 compatible I will be able to review and merge them

**Comment by brucegibbins** [comment]
Thanks.

I haven't seen the need for teams in our setup and don't know much about
it. But will try spinning up Django 4 anyway and see how we go without it.

If I can get my head around pinax I will see if I can help i  an effort to
get the whole thing across the line.

Cheers

**Comment by uhurusurfa** [comment]
Just finished upgrading the Pinax projects to support Django 4 
You should be able to successfully run Dgango4 with Pinax Teams plugged in.
