### ISSUE TITLE
Inconsistent username regex in urls.py

### ISSUE THREAD

**Issue by finnertysea** [django-helpdesk/django-helpdesk#1069]
**Describe the bug**
The regex to match user_name in re_path for rss_user is much more restrictive than the regex for user_name in rss_user_queue. This leads to, for example, usernames containing hyphens to raise an error for the former but not the latter.

Compare regex in urls.py on line 154 vs 159 in current stable branch.

**To Reproduce**
1. Logged in as a user with a hyphen (or any character that is non-alphanumeric, _, or .)
2. Go to /rss
3. Click on "My Open Tickets"
4. See "ERROR (EXTERNAL IP): Internal Server Error: /rss/"

**Expected behavior**
Should be redirected to /rss/user/<username>/. Note that clicking on any of the queue-specific rss links under "My Open Tickets" works fine. 

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.0.1
 - Browser: Safari
 - Version 16.1

**Additional context**
Modern Django uses "path converters" instead of hard-coded regex. See https://docs.djangoproject.com/en/3.2/topics/http/urls/#path-converters/

Maybe a future improvement could switch to using this method for urls?

**Comment by uhurusurfa** [comment]
Merged PR
