### ISSUE TITLE
Question: embedded .eml message being sent to helpdesk

### ISSUE THREAD

**Issue by brucegibbins** [django-helpdesk/django-helpdesk#1074]
Hi, I am not sure if this is a bug or 'as designed' but we have mail messages being sent into the helpdesk that we pickup with the email.py script. Sometimes these messages contain embedded email messages. For example, instead of forwarding the message a user will open a new message (in Outlook), address it to helpdesk and then drag and drop and existing message from Outlook inbox/folder into the new message for the helpdesk. This will then cause a new attachment (.eml) to be created.  My investigation seems to indicate that Django-Helpdesk correctly identifies this as a multi-part message but then gets confused about what to do with content type of 'message/rfc822' and ends up creating an empty attachment which is then ignored when creating the ticket. I am not well versed in decoding and encoding but the extract_part_data() function in email.py  doesn't seem to handle nested messages or if it does I must have a setup issue. But in my case I lose the attached .eml plus a few other odd things happen downstream with the ticket itself.

I have started to look into how to code something into the function but seem to be going in circles with decoding as I end up with a text version of the embedded message and therefore, lose all of the message headers and context. In my case I just need it to be left alone and attached as an eml file to the ticket.

Thanks for any help.

**Comment by Benbb96** [comment]
Hi @brucegibbins, I can confirm I encountered the same issue as yours. I also tried to fix it 2 years ago but had to give up and tell users to stop attaching .eml files...

I'll try to take another look if I have time, but if you find a solution, I'd be interested to see it!

**Comment by brucegibbins** [comment]
Thanks @Benbb96 , 

I can see in the standard library mail package (message.py) a docstring comment of 

> If the message is a multipart and the decode flag is True, then None is returned.

Which is the case based on about line 800 in the original helpdesk email.py module.

`files.append(SimpleUploadedFile(name, part.get_payload(decode=True), mimetypes.guess_type(name)[0]))`

My problem is that I don't know enough about email RFC etc to know... why? After hacking around with the call to get_payload() a bit I tended to make things worse and then better and then worse and it just felt brittle and I had not even considered nested emls which I guess could be possible. 

My last change reflected below - kind of worked. Except that instead of just leaving the eml alone it stripped all of the message header etc. In my case, we would typically have an end-user do this if a) they suspected the email they got to be malicious, and I can then use the message headers to do some basic forensics to help block them or b) they are passing on an email from a third party that we need to see in full. Really, in my case I can get away with just appending the untouched .EML attachment as we would review it with a text editor.

```
        if part.get_content_maintype() == "message" and part.get_content_subtype() == "rfc822":
            files.append(SimpleUploadedFile(name, part.as_bytes(), mimetypes.guess_type(name)[0]))
        else:
            files.append(SimpleUploadedFile(name, part.get_payload(decode=True), mimetypes.guess_type(name)[0]))

```

I'll keep looking.
Kind Regards

**Comment by uhurusurfa** [comment]
The code neeeds to fixed so that it identifies an embedded multipart and returns the payload of the multipart as a string.
This can be either or both of these 2 strategies:

1.  render the multipart as a string - it will require a bit of effort by the reader in the UI to find the relevant bits of text in the multipart so not ideal but it would retain its structure and no possible loss of data
2. build a prefix string containing subject, date sent and sender , invoke part.get_payload() with decode=False then iterate over the returned list prefixing each list element with the extracted prefix adding the resulting string as a file to the "file" list. This method may be confusing to the reader because there will be more than one part returned an likely to be a text based part and an HTML formatted part so essentially the same content. This may require a little experimenting to figure out the best way of processing a multipart to extract what we really are interested in for the end user

Any opinions on the preferred option?

**Comment by brucegibbins** [comment]
Hi.

I am wondering if there is third option which is not to render anything
except the body of the parent message and the attached eml is simply
attached to the ticket as a .eml and then if a 'user' who in our case is
typically a tech simply opens the .eml with the default reader (in our case
outlook) or sometimes i will download and open with a text editor so I can
look through the message header if trying to do any type of spam filtering
etc.

**Comment by uhurusurfa** [comment]
Actually the 3rd option you mention is the same as the 1st option.
If there is a helper in the browser to load a .eml file and render it correctly in the browser it will be readable.
If it is downloaded to a local drive then opened with an email tool it should render correctly.

To render the multipart as an attachment you would change this line:
`files.append(SimpleUploadedFile(name, part.get_payload(decode=True), mimetypes.guess_type(name)[0]))`

To something like this:
```
payload = decodeUnknown(part.get_charset(), part.as_bytes()) if part.is_multipart() else part.get_payload(decode=True)
files.append(SimpleUploadedFile(name, payload, mimetypes.guess_type(name)[0]))
```

**Comment by uhurusurfa** [comment]
@Benbb96 @brucegibbins - if you can confirm the 1080 PR solves this issue then please close.
