### ISSUE TITLE
New Ticket Email Template being used instead of Update Ticket Template

### ISSUE THREAD

**Issue by brucegibbins** [django-helpdesk/django-helpdesk#1078]
I noticed that when a ticket had been updated via a reply email message that the newticket_submitter template was being used rather than the updated_submitter template.

The source in email.py seems to validate this finding. Before making any changes and potentially a PR I'd like to know if I am on the right track.

I believe that line 527 should read
`'submitter': ('updated_submitter', context)`
rather than
`'submitter': ('newticket_submitter', context)`

the current code block is as follows:

 ```
 if new:
        ticket.send(
            {'submitter': ('newticket_submitter', context),
             'new_ticket_cc': ('newticket_cc', context),
             'ticket_cc': ('newticket_cc', context)},
            fail_silently=True,
            extra_headers=extra_headers,
        )
    else:
        context.update(comment=f.comment)
        ticket.send(
            {'submitter': ('newticket_submitter', context),
             'assigned_to': ('updated_owner', context)},
            fail_silently=True,
            extra_headers=extra_headers,
        )

```
Thanks

**Comment by uhurusurfa** [comment]
Makes sense to me.
@gwasser  @timthelion  - Are you aware of any reason why the above should not be changed as suggested?

**Comment by gwasser** [comment]
Nope, that looks like a typo to me, I think it should be the update template instead of new email.

**Comment by brucegibbins** [comment]
Hi. If I am able I can create a PR for this. However, as per some of my other open items I am trying to get quicktest to run error free first. The latest issue has been posted as #1079 

Thanks

**Comment by uhurusurfa** [comment]
Closing as fixed by PR
