### ISSUE TITLE
Check List Option

### ISSUE THREAD

**Issue by brucegibbins** [django-helpdesk/django-helpdesk#1087]
Coming from the Spiceworks Helpdesk platform we were used to using the Checklist addon feature for managing onboard and offboarding staff. HR would raise a ticket; we would add the appropriate checklist and then complete each item as and when necessary. This allowed us to see what still needed doing and we could use it to confirm back to HR that procedures had been followed. I was wondering if this had ever been considered or if there was something similar that I have missed?

Thanks in advance.

**Comment by Benbb96** [comment]
I believe this could be a nice feature 👍 
Do you think it would be necessary to track the evolution of a task in the checklist. For example, if I tick a task when doing a follow-up response, would it appears in `TicketChange` so we can later see when the task was done (or undone, and also created/deleted) ?

Also, would it be possible to create multiple checklists for one ticket or only a generic one is enough ?

That could be an interesting PR I might want to take 😃

**Comment by brucegibbins** [comment]
Hi @Benbb96 

Spiceworks allowed more than 1 checklist. It had a handy feature in that you couod create templated checklists and simply reuse them. So you could have a preset checklist for onboarding a new staffer and one for exiting staff and maybe one for running up a new machine etc.

I'm just not sure on the UI side how to implement.

**Comment by uhurusurfa** [comment]
@martin-marty - you are a UI fiend in Django - any interest in getting involved in this?

**Comment by martin-marty** [comment]
Hi @uhurusurfa, I don't think I'll have any available time until the last week or two of May/ early June. If a small project could be created with details of what's required, complete with screenshots of Spiceworks, I can take a look once I've got settled.

**Comment by brucegibbins** [comment]
I can do that if you like?

**Comment by martin-marty** [comment]
Hi @brucegibbins, if you could that would be awesome thank you. I've never used Spiceworks, so I'm a little unsure what would be expected.

**Comment by brucegibbins** [comment]
No Problems. Will have something shortly. I'd love to learn how to put it
into play so if you do get a chance it would be great to see how it is
done. I suspect some Javascript blackmagic in the case of SpiceWorks

**Comment by Benbb96** [comment]
For information, I started to work on this on my fork. I'll try to post something this weekend with some screenshots so that you can see how it looks. But I don't bother adapt it to match a better UI design 😉

**Comment by brucegibbins** [comment]
Hi. FWIW here are some screenshots from the Spiceworks implementation of ticket checklists.  I personally find the Spiceworks UI pretty clean, compact and functional and this feature which was at one time an optional Plugin blends in really well with the rest of the UI.

In summary the feature allows a ticket to be created with the equivalent of a "follow-up" item being created that has task items embedded within it. These tasks are rendered as checkbox items and therefore are either checked or unchecked. Spiceworks does carry some history of when items are checked therefore acting as an audit of when items are completed.  Unchecking an item is permitted as is ad hoc add addition and removal of task items.

Another feature is the ability to create 'shared' checklists that can be added to the 'follow-up' element. These are stored as 'templates' and thus carry no inferred logic or meaning. They just act as a quick way of creating a set of tasks. In my use case these allow us to have a set of tasks that need to be completed when on or off boarding staff. But with them acting as just a quick way pf creating a task list it allows us to add and remove items as maybe necessary depending on the role of the staff member. 

I also used it to create a 'daily checklist' and have an automated task that creates a ticket each day for a staff member to perform daily checks on infrastructure and services. 

After digging around it appears that the checklist data is stored as a JSON element in a table linked to the Ticket Master table. 

Hopefully the attached images will explain better. There is also information about the feature [here](https://community.spiceworks.com/appcenter/app/plugin_737)

![Ticket#1](https://user-images.githubusercontent.com/16873240/234825445-42897234-8844-4f92-bed9-c68d968006a3.png)
![Ticket#2](https://user-images.githubusercontent.com/16873240/234825478-eb154243-b7c3-4455-8aa5-ef3727c53076.png)
![Ticket#3](https://user-images.githubusercontent.com/16873240/234825501-c730cb23-778d-4da1-bc26-4960e5a0be92.png)
![Ticket#4](https://user-images.githubusercontent.com/16873240/234829021-4f313499-507a-4221-ab14-9eff8da910fc.png)

**Comment by Benbb96** [comment]
Hi all, I've worked on PR #1090 and I've added a link to a video capture of the UI if you want to take a look 😉

**Comment by brucegibbins** [comment]
Thanks
Taking a look
