### ISSUE TITLE
Pages not refreshing when Django cache enabled

### ISSUE THREAD

**Issue by brucegibbins** [django-helpdesk/django-helpdesk#1092]
Hi, I am not sure if others have experienced this or if this is something unique to my setup. 

We have the Django local memory cache enabled for our entire project which has helpdesk installed into the same virtual environment all hosted via an Apache HTTPD service on Windows.

This has been setup in settings as...
`CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'PROD',
    }
}
`

Then we disable caching at a View level if necessary so we can get current data refreshed.

Since, helpdesk is in the mix and covered by the same Apache/Django instance it is also influenced by the cache setup. The end result being  things like 'taking ownership' or using the edit form to update ticket descriptions 'appear' to not do anything until either the browser cache is refreshed or the backend Apache instance restarted.

Therefore, I experimented with adding the 'never_cache' directive to some of the Helpdesk urls and this seemed to correct the issue. But I am thinking that this is may not be the most elegant solution as it requires me to adjust the helpdesk urls.py file.

`    path("tickets/<int:ticket_id>/", never_cache(staff.view_ticket), name="view"),`

Is there a better way to do this? thanks in advance.

**Comment by uhurusurfa** [comment]
Take a look at this post:
https://stackoverflow.com/questions/25054976/how-do-you-apply-never-cache-to-a-third-party-django-apps-urls

Specifically you would use the siggestion referenced as "**_If you want to apply it to a set of urls from another app which you cannot edit then you can try:_**"

**Comment by brucegibbins** [comment]
Thanks @uhurusurfa will give it a try.

**Comment by timthelion** [comment]
Seems like a configuration error
