### ISSUE TITLE
Project Logo

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#1129]
It would be nice if the project had a logo. When I was setting up the standalone helpdesk I quickly threw together this one https://github.com/django-helpdesk/django-helpdesk/blob/main/helpdesk/static/helpdesk/img/icon512.png I don't know if ya'll like it or not. In any case, I wanted to open up this ticket to track the concept of having a logo for standalone django-helpdesk.

**Comment by timthelion** [comment]
We can use the logo for example for the icon for the github project and for the favicon in the standalone version.

**Comment by Benbb96** [comment]
IMO, it's a good idea to have a logo for the project, and your one does the job.  
Yes, it could be improved to look more professional but for now, I think it's good! And if someone wants to help with the design, it could be easily swapped later.

**Comment by Benbb96** [comment]
To make a good social preview, Github provides a template :

![repository-open-graph-template](https://github.com/django-helpdesk/django-helpdesk/assets/15046586/6029176f-8482-4f89-8d7d-bb9407d55195)

@timthelion, do you think you can make a version of the logo using this? Maybe just writing _django-helpdesk_ under the logo is enough. I think I can do it later, if ever.

**Comment by uhurusurfa** [comment]
Agree with above.

**Comment by timthelion** [comment]
Where does the repo card get shown? I am not aware of that graphic.

**Comment by Benbb96** [comment]
It's the integrated picture that get displayed when you share the repo link on sites like Facebook, X, Discord, etc.

**Comment by timthelion** [comment]
Who has admin access to this repo to change the icon?

![image](https://github.com/django-helpdesk/django-helpdesk/assets/1391608/485f7cb8-3aec-45ec-8b26-d3fea564ca6f)

**Comment by Benbb96** [comment]
I've seen that I'm able to do it. And I'm pretty sure @uhurusurfa can too.

**Comment by Benbb96** [comment]
Sorry, I tried changing it but it is the social preview image that I'm able to change.

The one you're referring to is in fact the avatar picture of the [django-helpdesk group](https://github.com/django-helpdesk), and I don't have the rights to modify it.

Preview image looks like this on Discord for example:
![image](https://github.com/django-helpdesk/django-helpdesk/assets/15046586/1e1e3af5-e1f6-4ef4-aed0-cb48ec00ab6a)

Should we keep it or try creating one with better size (following recommendations of 1280×640px) ?

**Comment by gwasser** [comment]
I can update the django-helpdesk group avatar image if there's agreement
from folks on what the new logo should be. Just tag me when the image is
ready to upload, in case you'd like to work on it some more.

**Comment by timthelion** [comment]
Seems like this is all done then :)
