### ISSUE TITLE
Fix migrations for multiple databases

### ISSUE THREAD

**Issue by tecbr** [django-helpdesk/django-helpdesk#1132]
These are my source code fixes for installing helpdesk integrated into an existing Django application with multiple databases:
[django-helpdesk-migrations-fixes.zip](https://github.com/django-helpdesk/django-helpdesk/files/13313556/django-helpdesk-migrations-fixes.zip)

**Comment by uhurusurfa** [comment]
Are you able to raise a pull request with these 2 files in it?
