### ISSUE TITLE
Conflict with allauth account

### ISSUE THREAD

**Issue by gab-luz** [django-helpdesk/django-helpdesk#1135]
**Describe the bug**

**To Reproduce**
1. Install django help desk
2. Place django help desk's apps on settings.py
3. Try to perform django's makemigrations and migrate

**Expected behavior**
When enabling helpdesk's app on django's installed apps, migrations won't work and server not able to start.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - LibreWolf
 - Version 118.0.2-1

**Additional context**
I've tried all steps, like the steps from this issue: [https://github.com/django-helpdesk/django-helpdesk/issues/912](https://github.com/django-helpdesk/django-helpdesk/issues/912). Doesn't work. I need allauth to work so I had to remove helpdesk. If you guys can fix it, it'll be great because django helpdesk seems to be a great tool.

**Comment by Benbb96** [comment]
Hi @gab-luz, can you confirm you tried what's suggested [here ](https://github.com/django-helpdesk/django-helpdesk/issues/912#issuecomment-1758136884)?

**Comment by uhurusurfa** [comment]
By default, teams functionality is enabled in Django Helpdesk.
Per the issue that @Benbb96 pointed you to, you will have to disable the (Pinax) teams feature to use the allauth app.

You best bet is to start with a fresh DB after setting your configuration correctly to omit teams unless you are comfortable with cleaning out any migrations that are already processed for Django Helpdesk.

**Comment by timthelion** [comment]
Serriously we should just dissable teams by default, I'm sorry I caused so many people problems, I really had no idea what havoc would come of that one silly dependency 😵‍💫

**Comment by gab-luz** [comment]
> Hi @gab-luz, can you confirm you tried what's suggested [here ](https://github.com/django-helpdesk/django-helpdesk/issues/912#issuecomment-1758136884)?
I did. Nothing different happened. I put that on my settings.py

**Comment by gab-luz** [comment]
> By default, teams functionality is enabled in Django Helpdesk. Per the issue that @Benbb96 pointed you to, you will have to disable the (Pinax) teams feature to use the allauth app.
> 
> You best bet is to start with a fresh DB after setting your configuration correctly to omit teams unless you are comfortable with cleaning out any migrations that are already processed for Django Helpdesk.
I've tried this and it didn't work (ISSUE 912):

```
HELPDESK_TEAMS_MODEL = 'usr.Person'
HELPDESK_TEAMS_MIGRATION_DEPENDENCIES = []
HELPDESK_KBITEM_TEAM_GETTER = lambda _: None
```

BUT, using the code below in my settings.py made all the error messages related django-helpdesk gone (also ISSUE 912, but didn't see it)

```
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "django.contrib.humanize", # Handy template tags
    "django.contrib.admin",
    "django.forms",
    "django.contrib.humanize",  # Required for elapsed time formatting
    "bootstrap4form",
    # Required for nicer formatting of forms with the default templates
    # 'account',  # Required by pinax-teams
    # 'pinax.invitations',  # Required by pinax-teams
    # 'pinax.teams',  # Team support
    # 'reversion',  # Required by pinax-teams
    "helpdesk",  # This is us!
]
```

**Comment by gab-luz** [comment]
Too early: 

SystemCheckError: System check identified some issues:

ERRORS:
helpdesk.KBItem.team: (fields.E300) Field defines a relation with model 'pinax_teams.Team', which is either not installed, or is abstract.
helpdesk.KBItem.team: (fields.E307) The field helpdesk.KBItem.team was declared with a lazy reference to 'pinax_teams.team', but app 'pinax_teams' isn't installed.

When running manage.py makemigrations, I got the error above. It depends on teams to work.

**Comment by timthelion** [comment]
Closing as duplicate https://github.com/django-helpdesk/django-helpdesk/issues/912
