### ISSUE TITLE
Should we dissable teams by default?

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#1136]
This would be a breaking change for teams users, but they could re-enable pretty easily.

**Comment by uhurusurfa** [comment]
I have already made changes that enable and disable teams with a single flag.
I will also update the installation documentatiuon to make it clear to new users.
It will remain on by default for existing users and new users will be directed to set the flag as part of the setup.

**Comment by uhurusurfa** [comment]
PR coming soon.
