### ISSUE TITLE
Can't "take" tickets from dashboard due to checklist bug

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#1138]
If you click the "take" button or go to a link like `https://helpdesk.bitswan.space/tickets/60/?take` you will end up with an error:

```
Internal Server Error: /tickets/60/

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner

    response = get_response(request)

  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view

    return view_func(request, *args, **kwargs)

  File "/opt/django-helpdesk/helpdesk/views/staff.py", line 360, in view_ticket

    return update_ticket(request, ticket_id)

  File "/opt/django-helpdesk/helpdesk/views/staff.py", line 748, in update_ticket

    new_completed_id = sorted(list(map(int, request.POST.getlist(f'checklist-{checklist.id}', []))))

AttributeError: 'dict' object has no attribute 'getlist'
```

**Comment by Benbb96** [comment]
I think I can fix that by better handling this part here : https://github.com/django-helpdesk/django-helpdesk/blob/0fc18848bced21625b05111b776297e723266d4c/helpdesk/views/staff.py#L352

I'll try to do a PR tonight.

**Comment by timthelion** [comment]
OK, I was planning on re-writing that function a bit tonight too for another reason: Right now if you post a follow up to the API it doesn't run any of the ticket update logic. We need to separate out the ticket update logic so it works with the REST API too (to send out emails)... Should I wait for your PR?

**Comment by Benbb96** [comment]
Ok, yes I understand, there's a lot of refactoring to make the ticket logic accessible from normal views and the new ones for the API (maybe centralizing it in models ?).

If you were planning on working on it, I let you do it, but I can help if needed 😃 
I was thinking on doing something like described [here ](https://stackoverflow.com/a/67368891/8439435)to have a valid `QueryDict` object.

**Comment by timthelion** [comment]
Yeah, I think I can figure it out. Cheers
