### ISSUE TITLE
Bootstrap forms version in upgrade documentation does not match requirements.

### ISSUE THREAD

**Issue by mattbuff** [django-helpdesk/django-helpdesk#1160]
**Describe the bug**
The upgrade documentation mentions django-bootstrap5, but the installation documentation and requirements mention django-bootstrap4.

https://github.com/django-helpdesk/django-helpdesk/blob/f379bbe80e52f4470755b78c2fad91a59fa213ed/docs/upgrade.rst?plain=1#L14-L17

https://github.com/django-helpdesk/django-helpdesk/blob/f379bbe80e52f4470755b78c2fad91a59fa213ed/docs/install.rst?plain=1#L68

https://github.com/django-helpdesk/django-helpdesk/blob/f379bbe80e52f4470755b78c2fad91a59fa213ed/requirements.txt#L2

https://github.com/django-helpdesk/django-helpdesk/blob/f379bbe80e52f4470755b78c2fad91a59fa213ed/requirements-no-pinax.txt#L2

**Comment by Benbb96** [comment]
Fixed by #1203
