### ISSUE TITLE
logout stops working with Django >4.0

### ISSUE THREAD

**Issue by jorge-leon** [django-helpdesk/django-helpdesk#1174]
**Describe the bug**

Since Django 4.1 the contributed `LogoutView` requires the POST method, see:

https://docs.djangoproject.com/en/4.1/releases/4.1/#log-out-via-get

Find attached a patch which replaces the logout link (`<a href=`...) with a form. In order to maintain formatting
a label with a hidden submit button is used. I do not know if this works for all browsers.
 
[django_logout_post.patch.txt](https://github.com/django-helpdesk/django-helpdesk/files/15129648/django_logout_post.patch.txt)

Note: in `urls.py`  the `next_page` parameter uses a plain `../` which might not do what is meant in all situations. It could be
replaced by `reverse_lazy("helpdesk:home")`, however I plan to integrate a more general solution in a future PR for improving
integration of django-helpdesk into a django-project with other apps.

**To Reproduce**
1. Install django-helpdesk with a Django version greater or equal to 4.1
2. Set up a user and login
3. Click on the "Logout" link in the user dropdown
4. Click on the back button of the browser and optionally reload
5. The user is still logged in.

**Expected behavior**

The user is logged out

**Comment by uhurusurfa** [comment]
👍  Look forward to the PR

**Comment by jorge-leon** [comment]
> 👍 Look forward to the PR

Hi uhurusurfa: please consider the attached patch, it's almost trivial, and my resources are bound. I have more enhancements with broader scope in preparation on which I'd like to focus.
