### ISSUE TITLE
Make parent tickets visible in ticket view, improve handling of dependencies

### ISSUE THREAD

**Issue by jorge-leon** [django-helpdesk/django-helpdesk#1184]
**Is your feature request related to a problem? Please describe.**

I want to use  "milestone tickets", where individual tickets to be resolved are added.

While I can see the dependent tickets on the milestone, there is no way to see the milestone(s) a ticket belongs to.

**Describe the solution you'd like**

The ticket description should have an additional field which contains a list of 'parent' tickets, i.e. tickets which depend
on the current one.

**Describe alternatives you've considered**

Filtering, but this is easily ruled out as very inefficient.

**Additional context**

A PR will be supplied.

**Comment by lonewolve24** [comment]
Hello @uhurusurfa I will like to work on this bug if this issue can be assigned to me thanks

**Comment by jorge-leon** [comment]
> Hello @uhurusurfa I will like to work on this bug if this issue can be assigned to me thanks

Sorry, that one is already resolved. will close this issue now.
