### ISSUE TITLE
/admin/helpdesk/queue/ is timing out

### ISSUE THREAD

**Issue by samsplunks** [django-helpdesk/django-helpdesk#1192]
**Describe the bug**
/admin/helpdesk/queue/ page is timing out.

**To Reproduce**
1. Go to the admin interface
2. Click on Helpdesk Queue
3. Wait until timeout

**Expected behavior**
Show the list of queues

**Additional context**
On a small dev server with about 30.000 tickets with follow-ups, the Queue admin view has to calcultate the 'time_spent' field (which is a dynamic property) summing up the 'time_spent' dynamic property of tickets.

A quick fix is to remove the 'time_spent' field in the admin.py file for QueueAdmin.
A more elaborate one would be to use SQL aggregations to speed things up in the time_spent function.
Another one would be to have time_spent as a ModelField.

**Comment by samsplunks** [comment]
I'd like to try out modifying the time_spent queries:
```
FollowUp.objects.filter(ticket__queue=q).aggregate(Sum('time_spent'))
{'time_spent__sum': datetime.timedelta(days=6602, seconds=42625)}
```

**Comment by samsplunks** [comment]
Proposed PR: https://github.com/django-helpdesk/django-helpdesk/pull/1194

**Comment by uhurusurfa** [comment]
Totally onboard with moving it to the database.
There are many places where post processing of a resultset is a huge waste of processing time and will not scale.
