### ISSUE TITLE
Updating a ticket fails because of invalid year

### ISSUE THREAD

**Issue by george-silva** [django-helpdesk/django-helpdesk#148]
File "/home/atlassig/webapps/ouvidoria/lib/python2.7/django/core/handlers/base.py", line 111, in get_response
   response = callback(request, _callback_args, *_callback_kwargs)

 File "/home/atlassig/lib/python2.7/django_helpdesk-0.1.7b-py2.7.egg/helpdesk/views/staff.py", line 263, in update_ticket
   int(due_date_day))

ValueError: year is out of range

Steps:
1. Create ticket WITHOUT defining due date;
2. Create a followup and do NOT define a due date;
3. Error should occur;

Django helpdesk is treating due date as a mandatory field in the "update/followup" form. Instead of validating it nicely, it's letting a nasty exception to blow up on users.

**Comment by gwasser** [comment]
I agree, this appears to already be fixed, I'll go ahead and close this.

**Comment by hnjogu** [comment]
cronjob to run the escalation command .how can i set an escalation to automatically assign a ticket within 5 minutes if the person who is responsible to handle that ticket is busy and is not able to handle that ticket.

**Comment by gwasser** [comment]
@hnjogu the documentation has a few examples on how to set up a cronjob: https://github.com/django-helpdesk/django-helpdesk/blob/master/docs/configuration.rst. Just change the numbers to whatever number of minutes you prefer.
