### ISSUE TITLE
Again non-ascii characters in attachments: silently failing or "value too long"

### ISSUE THREAD

**Issue by ghost** [django-helpdesk/django-helpdesk#167]
Sorry to bring this up again, but I'm the guy from Germany getting attachements with those characters. :)

I'll try to figure it out myself but here's what I know so far: 

Attachments with short file names:
Via form: ok, those characters left out.
Via e-mail: ignored. No error, but also not present in the ticket, attachments folder or database. 

Attachments with longer file names (49 characters in my example):
Ok when file renamed, e. g. ä=ae, but when not:
Via form: value too long for type character varying(30)
Via e-mail: value too long for type character varying(100)
When failing, these attachements are not in the ticket and database, but in the attachments folder with a name like 
iso-8859-1QFILENAMEE4fi_iso-8859-1Qxe2EEXTENSION where E4fi_ replaces the non-ascii character and the file name is cut there. 
Another anoying thing: An e-mail is not deleted and imported repeatedly while every time saving that broken attachement to the folder. 

As far as I can figure out till now:
- importing attachements via form or e-mail is handled differently
- non-ascii characters are count more than one character (surprise!) ;)
- leaving non-ascii chars out works only for form submission

**Comment by RafaelOrtiz** [comment]
I believe this is also happening for titles, encoding issues. 

DataError('value too long for type character varying(200)\\n', )"

**Comment by reduxionist** [comment]
This may well no longer be relevant to those who first encountered this bug three years ago, but for the record, the part that remained after filename length was fixed, we now believe to have finally completely solved via PR #463; we are thus also finally closing this ticket.
