### ISSUE TITLE
Problem installing fixture: Incorrect string value

### ISSUE THREAD

**Issue by chrisspen** [django-helpdesk/django-helpdesk#184]
I tried installing django-helpdesk 0.1.11 from pypi, and running `manage.py migrate helpdesk` fails with:

```
Warning: Problem installing fixture '/usr/local/myproject/.env/local/lib/python2.7/site-packages/helpdesk/fixtures/initial_data.json': Incorrect string value: '\xD0\x97\xD0\xB0\xD1\x8F...' for column 'heading' at row 1
```

So I tried installing master with:

```
pip install -U https://github.com/rossp/django-helpdesk/archive/master.zip
```

but this also fails with:

```
Downloading/unpacking https://github.com/rossp/django-helpdesk/archive/master.zip
  Downloading master.zip (853Kb): 853Kb downloaded
  Running setup.py egg_info for package from https://github.com/rossp/django-helpdesk/archive/master.zip
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: invalid command 'egg_info'
```

What are causing these errors? I'm using MySQL as my db backend. Please let me know if I'm doing anything incorrectly.

**Comment by mrkiwi-nz** [comment]
As @chrisspen  says, utf8_general_ci is a safe choice for collation. This error will occur whenever you have created your db using a collation that can't handle the characters in the fixture.

For example these wont work; "big5", "cp-1251" 
These do work : utf8_general_ci or utf16_general_ci

If you really want to keep your current collation, and you don't mind editing the fixtures file, you can delete the russian and german email templates (lines 194 to 386) in the file emailtemplate.json
These templates contain a number of unicode characters which cause the error when trying to shove them into fields which have an incompatible database collation.

Maybe a line in the installation notes would help?

**Comment by gwasser** [comment]
Added documentation to the installation notes as part of #507 so closing. Let us know if I missed anything!
