### ISSUE TITLE
Tests and tests coverage?

### ISSUE THREAD

**Issue by pombredanne** [django-helpdesk/django-helpdesk#188]
This app is mighty nice, but it scares me that there are so few tests and so few new tests added as new code is being added ...
This is a bit a chicken and egg issue: I may not use it because of the lack of tests and therefore I am not contributing tests either (because I do not use it because of teh lack of tests)

Could I suggest adding coveralls for a start to highlight the tests coverage issue to everyone?
Any plan to improve things on that front?

**Comment by reduxionist** [comment]
Thanks to @flinz's commits, we now have coverage reports from codecov as part of our CI, and thanks to his leadership, increasing our test coverage has been promoted from issue to [project status](https://github.com/django-helpdesk/django-helpdesk/projects/1)!

Although it has taken us a while to find the needed resources, we're grateful for the encouragement and suggestions you gave @pombredanne! :cake: And, of course, thanks once again for giving us such testing momentum @flinz! 🎉

**Comment by flinz** [comment]
Thanks! 

I would very much recommend to make what @pombredanne wrote something like PR guidelines:
> 1/ no patches or new commit without unit tests
> 2/ a new test for each new ticket fixed or new features
> 3/ as you work on the codebase, and want to do some refactorings, start by writing a few tests that could break with the changes

Especially as we accept pull requests for features and refactoring we should make them conditional on providing proper tests.
