### ISSUE TITLE
Replace API with django-rest-framework or similar

### ISSUE THREAD

**Issue by rossp** [django-helpdesk/django-helpdesk#198]

**Comment by rossp** [comment]
On further thought - API should be removed entirely. Not our job to provide IMO - people can address this with multiple external means (tastyppie, django-rest-framework, SQL, custom Python code). I'm going to add deprecation warnings then remove it entirely next month.

**Comment by TauPan** [comment]
I can recommend https://github.com/izimobil/django-rest-framework-datatables if you want to migrate your datables views to django-rest-framework as well. I'm in the process of converting legacy datatables views to rest framework and the resulting code  is usually much simpler.

**Comment by gwasser** [comment]
Wasn't aware of that django app, thanks for the recommend! Sounds like something to be considered in the future when get to tackling the API.

**Comment by Mte90** [comment]
Any updates on this?
If can be helpful a rest documentation from another OSS helpdesk https://www.opensupports.com/apidoc/

**Comment by gwasser** [comment]
@Mte90 I personally have not had time to investigate or implement this, I welcome volunteers to work on it and submit a PR though!

**Comment by Mte90** [comment]
So it is moving on :-D

To me is enough to add the user rest endpoints and I am fine :-D

**Comment by gwasser** [comment]
Yes an API based on django-rest-framework should be available in the next release `0.3.4` which should come soon once we've cleaned up some testing and what not.

**Comment by gwasser** [comment]
Will close this ticket as part of getting ready for the next release. Thanks!
