### ISSUE TITLE
No public Ticket-updates via web possible?

### ISSUE THREAD

**Issue by mxrt** [django-helpdesk/django-helpdesk#210]
I wonder if/how a user (ticket creator) without account in the ticket-system can update his ticket via web?

Via mail this works fine out-of-the box, but via web i don't see how this is possible (e.g. attach some files later etc.)?!? :-(

here is a demo-ticket on the demo herukoapp to show what i mean:

http://django-helpdesk-demo.herokuapp.com/view/?ticket=demo-543&amp;email=jata.84asdasd%40sdas.es

assuming the link is sent to the user created the ticket:  he can see it's state etc., but how can he update it via the web-frontend?

thank you!

**Comment by timthelion** [comment]
This is fixed with the ticket private keys and magic links
