### ISSUE TITLE
Email Message-ID, In-Reply-To, and References Handling

### ISSUE THREAD

**Issue by issackelly** [django-helpdesk/django-helpdesk#224]
I've made a in-project hard-fork of helpdesk this week to do a big refactor on matching emails to helpdesk tickets.  I'm making this ticket to discuss the changes that I'm making, and if they're helpful to the project at-large.

I'm building a system where interaction with the customer is primarily via email, and the helpdesk is used as a shared inbox managment. 

I've dropped the regex matching in the subject of emails in favor of matching tickets to "References", "In Reply To" and "Message ID" email headers.

It's sort of... naive right now, but it appears to be working for us.  Customers and staff are transparently communicating via email, and as long as the support desk queue email is CCed, we have a record of the communication.

If outgoing emails properly set the headers, this has the added benefit of not breaking customer threads for outbound replies/responses. I think it's sort of a win-win.

I am going to keep trying to contribute back to the project where I can, but I'm personally definitely going to keep moving forward with this approach.

Also, we may have talked about this before... I had a fork from several years ago where I started some work in this direction but I don't think I ever got anything working. Thanks for all your work and open source stewardship.  Django-helpdesk is a hell of a good project.

**Comment by timthelion** [comment]
This is done.
