### ISSUE TITLE
New / Unaddressed Tickets feature

### ISSUE THREAD

**Issue by brian-labelle** [django-helpdesk/django-helpdesk#243]
First, I would just like to thank everyone for the work they have been doing on django-helpdesk recently. This is a great project. 

I have been making several customizations for my helpdesk system. One simple addition that I have been working on is a section on the dashboard for new / unaddressed tickets -- open tickets that have been submitted, but have not had a staff member reply yet. I required this feature because my helpdesk system will span 3 websites with frequent ticket submissions. I needed a ticket to appear in its own section when the submitter posts a reply.

I did this by writing a function that loops through a ticket's followups and chooses the followup with the last(most recent) date. If the last followup does not have a user(or in my case, comes from the api user, since my helpdesk system heavily uses the api), then the ticket has a new comment that has not been addressed by the staff member. 

If the staff member or submitter closes the ticket, it no longer appears in this section. I have provided my code below in case anyone feels like this is a useful addition. I would make a pull request, but I have made many customizations for my specific system. 

In **staff.py** dashboard method:

```
tickets_with_unread_followups = Ticket.objects.filter(
        #My custom filters, add your filters or get back all tickets. 
    ).select_related('queue', 'followup_set').exclude(
        status=Ticket.CLOSED_STATUS,
)

unread_tickets = []
for ticket in tickets_with_unread_followups:
    last_followup = ticket.get_last_followup()
    if not last_followup.user:
        unread_tickets.append(ticket)
    elif last_followup.user.username == 'api':
        unread_tickets.append(ticket)
```

unread_tickets is passed back in the RequestContext method.

In **dashboard.html**

```
{% if unread_tickets %}
    {% trans "All tickets with new comments" as ticket_list_caption %}
    {% trans "There are no new tickets" as no_new_tickets %}
    {% include 'helpdesk/include/tickets.html' with ticket_list=unread_tickets ticket_list_empty_message=no_new_tickets %}
{% endif %}
```

I actually have my own new.html file that I include on my dashboard that formats the table with my customizations, but this should work.  

In **models.py** Ticket model:

```
    def get_last_followup(self):
        last_followup_date = None
        last_followup = None

        for f in self.followup_set.all():
            if not last_followup_date:
                last_followup_date = f.date
                last_followup = f
            else:
                if f.date > last_followup_date:
                    last_followup_date=f.date
                    last_followup = f
        return last_followup
```

I'm sure there is a way to improve this method.

**Comment by mrkiwi-nz** [comment]
Brian - Did you get any further with this?

**Comment by timthelion** [comment]
There is now an unassigned tickets section in the dashboard
