### ISSUE TITLE
create_ticket.html TemplateSyntaxError at /helpdesk/tickets/submit/ 'bootstrap' is not a valid tag library: Template library bootstrap not found

### ISSUE THREAD

**Issue by iboulard** [django-helpdesk/django-helpdesk#245]
TemplateSyntaxError at /helpdesk/tickets/submit/
'bootstrap' is not a valid tag library: Template library bootstrap not found

Only when creating a new ticket, the rest is fine

**Comment by JayTurnr** [comment]
Maybe this should be in the documentation!
