### ISSUE TITLE
Django 1.7 Update

### ISSUE THREAD

**Issue by danie1k** [django-helpdesk/django-helpdesk#255]
Thanks for the update! But I have two more things.
1. Is **django.contrib.markup** still required (via http://django-helpdesk.readthedocs.org/en/latest/install.html#adding-to-your-django-project)? It's deprecated since Django 1.5 (source: https://docs.djangoproject.com/en/1.5/ref/contrib/markup/). Instead that I've found https://pypi.python.org/pypi/django-markup-deprecated
2. Django 1.7 raises warning:
   
   > WARNING:py.warnings:[...]/site-packages/helpdesk/forms.py:523: **RemovedInDjango18Warning**: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form EmailIgnoreForm needs updating
   > class EmailIgnoreForm(forms.ModelForm):

**Comment by mittfran** [comment]
`django.contrib.markup` is mentioned in docs/install.rst to be put in `INSTALLED_APPS`
Maybe remove that reference to make it clear.
