### ISSUE TITLE
Creating Custom Form Fields based on Queue rather than Ticket Model

### ISSUE THREAD

**Issue by JJediny** [django-helpdesk/django-helpdesk#293]
Testing on this app in another django project and it's integrated well; however there is one last project requirement not supported. Considering supporting this myself but ignorant to whether its practical in the context of the apps current logic/scheme. I need to be able to customize the form based on the Queue rather than how it's currently setup; appended to the Ticket model using a Mixin. Before diving deeper I'm wondering if there are any fatal flaws to changing/relating the CustomMixin to Queue model vs the Ticket model? The basic idea would be to make the user select the Queue field first and tie a separate view/form to render based on the selection {{ Ticketfields }} + {{ QueueCustomMixin }}

**Comment by rossp** [comment]
Like most changes like this I think it's feasible, IF the normal use-case of system-wide custom fields stays the same. The biggest impact is that it obviously impacts the flow for creating a new ticket for both the public and staff views.

To keep it simple for end users, can we load the remainder of the form dynamically with JavaScript when the queue is changed? Need to ensure that a no-JS version also works (ie redirect to a second page with the new form).

**Comment by JJediny** [comment]
@rossp was able to do some work towards this https://github.com/JJediny/django-helpdesk/compare/rossp:master...master. Code is still fragmented as I'm still prototyping/debugging but here is the basic approach I'm taking (so far - any feedback would be appreciated)... 

## Approach for Feedback
### Adding a New Model TicketType 

`Queue` seems more akin to Office/Department/Mailbox than the "type" of ticket/customfields, so for this reason and so I wouldn't disturb the existing framework I created a new abstract model class called `tickettype`. I stole heavily from [django.blog.zinnia](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/models/category.py) 'category' which uses mptt model class (already a dependance in django-helpdesk) to create an abstract/flexible/hierarchical model. 

### Relationships to Existing Models

The current setup (as i read it) is that `customfields` are an abstract model used to append form fields to the ticket the resulting user input gets stored in a stand-alone long table using a simple foriegnkey to the `ticket` model (this could be a performance issue long term with heavy use but i like its simplicity and that it allows admins not to have to deal with field changed/missing/added for historical tickets (as there's no relation back to a form model) which also allows users to iterate versions of the form/fields as they go. I tried to create the `ticketype` model along the same lines so that it only relationship to the rest of helpdesk would be as a ManytoMany w/ `CustomField` so users/admin could model it as a hierarchy and relate an one or multiple customfields to apply to any parent or child tickettype. The end result being a clean filter controlled by a tickettype field and some JS to reload the customfields based on a users selection. Could be a stand-alone field or somehow tied to Queue as another level of filtering/customization...Thoughts or Feedback?

**Comment by flinz** [comment]
Hi https://github.com/JJediny. I didn't have time to look over your code yet, but I agree that some functionality along the same lines would be great.

My 2 cents: Not only would it be nice to specify ticket types with custom field bindings, but maybe generalize the current way that fields are assigned to tickets to a degree where you could also selectively disable some of the default fields for some of the ticket types or have more control of their being available to users etc.. E.g., I personally had the issue I did not want to display to anonymous users some of the more advanced fields.

**Comment by rossp** [comment]
@JJediny Thanks for your contribution here! like @flinz I haven't had a chance to thoroughly review your code, but have a few quick thoughts and questions as they come to mind... sorry the below is a mix of direct questions and abstract rambling :)

1. Is it worthwhile having a `Queue` and a `Ticket Type` as two separate concepts? Can they be one and the same? Like you say the general intent of this is for different departments (ie accounts vs tech support vs developer relations), but I'd be interested to hear how people are using this in the wild.
2. Is a multi-level `Ticket Type` with `mptt` an important thing to include, or is it unnecessary complexity and additional dependencies?
3. `django-helpdesk` doesn't currently use `django-mptt` anywhere I'm aware of.
4. I originally designed `django-helpdesk` to have a basic structure. A ticket is new, then assigned, then resolved, and finally closed. Within this there's a basic high/low priority structure, and a way to separate tickets based on who is working on them (ie using Queues). The existing structure and views are based on these assumptions. Could we perhaps update the custom field logic to allow for searching and filtering, and move Status and Priority into a default set of custom fields? If an admin then deleted eg the default status field, how would the dashboard  / ticket list defaults work? Might need a bit of further thought
5. Can we quantify the potential performance impact of custom fields, both with the current model and with what you're proposing?
6. Should we also consider custom fields that can be seen by ticket owners / staff but not end users?

**Comment by JJediny** [comment]
Made a mockup of my proposed approach... taking your comments into count to reduce the amount of JS involved and to leave the current default usage unimpeded. Let me know what you think:
![image](https://cloud.githubusercontent.com/assets/6350035/6380345/f3c6915a-bd06-11e4-94ad-1e805237d7cd.png) & 
![image](https://cloud.githubusercontent.com/assets/6350035/6380369/1e3ce560-bd07-11e4-9bfd-964cfe999362.png)

**Comment by rossp** [comment]
To be honest I'd rather not see this break down into three steps. I think that selecting the queue first should show the standard form plus all custom fields for that queue shown in a single form.

At present if you add custom fields they show on the initial submission form - I'd like to see this form structure stay as-is, but with the queue selector beforehand if necessary (if there is only one queue, the ticket form should be shown right away per #289)

Having 3 steps seems overly complex to me... thoughts?

**Comment by JJediny** [comment]
Probably shouldn't have used "steps" as I'm envisioning it as all one consolidated view. One thing I noticed in testing out the form and asking some people to do the same is that having the standard/general ticket fields first causes the user to put everything in those fields and they get to the customfields (where we want them to then split all that information out/down runs against the grain of what people are used to... that having the custom fields (part of the same form but split out by column) allows them to better intuit what to put where and that moving the general ticket form *visually last reserves those fields to be used as anything they didn't input in the fields (i.e. notes, comments, concerns, special considerations, etc)... The actually layout of what I'm thinking is two have two <div>wrappers for a django template ~20/80% with the control Queues as Buttons to render to another view with the same layout but updated filter/queryset for the customfields/queue... The settings I was thinking about would hide the btn control. The only change to the "as is" would be to split the form into two columns (1 form w 2 columns) could see if we could wrap the form internal with div tags that way users would have the ability to control the layout Custom (left) x General (right) vis-versa AND/OR General (top) x Custom (bottom) vis versa...

**Comment by HolzmanoLagrene** [comment]
i assume this thread is dead?

**Comment by timthelion** [comment]
To create custom flows you can now use the iframe integration and queryparams to configure which fields are shown/prefilled: https://github.com/django-helpdesk/django-helpdesk/blob/main/docs/integration.rst
