### ISSUE TITLE
Error on initial migration

### ISSUE THREAD

**Issue by andybak** [django-helpdesk/django-helpdesk#306]
Django 1.7. Custom user model called 'Contact'

The error is:

```
django.db.utils.ProgrammingError: column crm_contact.job_title does not exist
```

Fails at this line:

```
File "/Users/andybaker/.virtualenvs/hireable/src/django-helpdesk/helpdesk/migrations/0003_populate_usersettings.py", line 33, in populate_usersettings
    for u in User.objects.all():
```

One migration back I'd removed the job_title field from the Contact model. I managed to fix this by adding it back in, migrating crm, then migrating helpdesk.

Happy for you to ignore this as I found a workaround. It's odd though...

**Comment by rossp** [comment]
To be honest I'm not 100% sure if this is an issue with `django-helpdesk` or if it's a quirk of migrations when you change a custom user model...  What do you think? Happy for a more permanent fix to make it into our migrations if that's the correct way to fix this.

**Comment by gwasser** [comment]
@andybak We've made some improvements to our migration files and its been quite some time, so I'm going to go ahead and close this out for now, but please feel free to file a new ticket if you're still getting trouble or have a suggestion for fixing up or migrations further!
