### ISSUE TITLE
Links in emails should use customizable scheme

### ISSUE THREAD

**Issue by malemburg** [django-helpdesk/django-helpdesk#310]
The emails currently use hardcoded "http://" schemes for ticket addresses:

https://github.com/rossp/django-helpdesk/blob/master/helpdesk/models.py

It would be better to be able to configure this, since most helpdesk installations will use HTTPS nowadays.

**Comment by rossp** [comment]
Suggest relying `settings.SECURE_SSL_REDIRECT` as we don't have a `request` at time of sending many of these emails. Will need to ensure we've got documentation that reflects this.

**Comment by timthelion** [comment]
This is already done: https://github.com/django-helpdesk/django-helpdesk/blob/761b91d2fe55d42ff767b8dc617925425f27fa6f/helpdesk/models.py#L733
