### ISSUE TITLE
Add possibility to configure an "always BCC" address

### ISSUE THREAD

**Issue by malemburg** [django-helpdesk/django-helpdesk#311]
This is useful to keep an archive of all incoming and outgoing email.

**Comment by rossp** [comment]
Can you configure this via a custom Django email backend? Alternatively, if you use a mail delivery service like Mandrill they allow you to configure a constant BCC.

**Comment by malemburg** [comment]
This is all possible, yes, but since the helpdesk is already using a central send_templated_mail() function which does support BCC, I think it's easier to add the default to that function and have it pull the BCC address default from the settings.

**Comment by rossp** [comment]
My personal take is that this is a very low priority given the number of ways of achieving it. That said, if it's important to you I am happy to receive a pull request to add this functionality.

**Comment by timthelion** [comment]
This is already possible to do using a custom mail backend and IMO it would be harmful to complicate the helpdesk with functionality that is duplicated elsewhere.
