### ISSUE TITLE
Adding more capabilities to mail threads and replies

### ISSUE THREAD

**Issue by alexbarcelo** [django-helpdesk/django-helpdesk#375]
It would be nice if the tickets could be more integrated with the mail responses. Use case:
- Mail received from alpha@example.net, sends to Queue (queue_name@example.com) and also puts as CC bravo@example.net
- Bravo sends a response to both alpha@example.net and the Queue
- Charlie is staff and replies directly to the mail sent by helpdesk
- Delta is staff and puts a public comment through the web interface.

Desired behaviour:
- First Alpha mail opens a ticket. (No mail outbound). By default, no CC is added (although maybe it would be a feature? Detect bravo@example.net as a CC and add it to CC?)
- Bravo reply is stored as a comment to the ticket. (No mail outbound)
- Charlie reply is resent to Alpha. Helpdesk sends the update mails as a **mail reply** to those.
- Delta comment is also sent as a mail reply.

Internal mechanism:
- When the ticket is opened by Alpha, the Mail-ID is stored somewhere. This would be the main ID for all outgoing mails on this ticket. (The In-Reply-To mail header).
- When Bravo sends a reply, the Mail-ID is stored, and it will be added in the References mail header.
- Charlie receives a mail from helpdesk with Reply-To something like queue_name+ticket_identifier@example.com --this ensures that the Charlie reply is associated to the ticket. To avoid more guessing and more robust behaviour. The outgoing mail has In-Reply-To and References correctly populated.
- Delta comment is sent as a mail reply, in a similar fashion to the last one.

Final goal:
- The mail integration would be nicer, the end-user will see the tickets just as a regular mail thread (whatever client or webmail are they using).
- The staff are able to reply directly from mail. Don't know if there should be a mechanism to add options --like a [close] tag in the subject to force a ticket close? But, at least, it would be more easy to address simple tickets.

There will be issues, and maybe there are some problems with this approach. Do you feel that I am overlooking something?

**Comment by rossp** [comment]
Generally speaking I like the idea of having more powerful email integration.

What I *don't* want to do is have email addresses that are controlled by `django-helpdesk` - ie your example of *queue_name+ticket_identifier@example.com*. This requires integrating with incoming email in ways that I have done in the past and am not in a rush to support again - every set up is completely different. I'd prefer a single email address per queue (per current functionality) and use of the subject, which seems to work in most cases already.

To address your sample scenario:
1. I think adding Bravo as a CC on ticket create is a good idea
2. Setting `in-reply-to` etc is useful as it'll enable end user threading
3. Alpha and Bravo both get the updates that are sent by Charlie and Delta

Sound reasonable?

**Comment by alexbarcelo** [comment]
Sounds completely reasonable :)

I will soon start working on it (I hope). Thanks for the feedback!

**Comment by brunotikami** [comment]
Hi @alexbarcelo, I'm reading your description and implementing this feature :)

I'm right now wondering why you wouldn't want Alpha to be notified over email when the ticket is created ?

**Comment by alexbarcelo** [comment]
@brunotikami Nice to see it! I will follow it.

In my production environment, seemed superfluous to receive a mail if you have just sent one. But maybe I was focusing too much in our use case and is not a general thing.

**Comment by brunotikami** [comment]
Hey @alexbarcelo and @rossp do you have anything against using the TicketCC model to connect Bravo and the issue ? 

I'm asking this because nowadays TicketCC instances may have empty emails if a user instance is linked to it (which is fine) but then I'd add a validation and require at least one of them before creating a new TicketCC instance.

**Comment by alexbarcelo** [comment]
Setting it as a CC was an afterthought, and every time I think about it I find it makes sense to do so. So, IMHO, is a good thing to do.

By that validation you mean that TicketCC must have either `user` field not null or `mail` field not null? It makes sense, if I understood correctly.

If that is what you were saying, then that would need a Validator for the form-based TicketCC, doesn't it?. I have seen no "dangerous" usage of TicketCC creation, only the `subscribe_staff_member_to_ticket` which is inherently valid (maybe check that `user` param is not `None`, just to be sure). The other usages seems to work through TicketCCForm, which will use the validation.

**Comment by brunotikami** [comment]
@alexbarcelo I've added this validation to the <clean> method on the TicketCCForm. Would you mind taking a look at my fork ?

**Comment by gwasser** [comment]
Merged this in via #385 manually to the `develop` branch for the 0.3 release. Was in pretty good shape and I don't think needed very major changes despite the update to Py3/Django2 and so forth. Thanks for the PR!
