### ISSUE TITLE
The documentation's description of TEMPLATE_CONTEXT_PROCESSORS is out-of-date for Django >= 1.8

### ISSUE THREAD

**Issue by thecardcheat** [django-helpdesk/django-helpdesk#384]
In the documentation [settings section](docs/settings.rst), the usage of TEMPLATE_CONTEXT_PROCESSORS is no longer current as of Django 1.8 ([1.7](https://docs.djangoproject.com/en/1.7/ref/settings/#template-context-processors), [1.9](https://docs.djangoproject.com/en/1.9/ref/settings/#template-context-processors), [upgrade guide](https://docs.djangoproject.com/en/1.9/ref/templates/upgrading/)) and the location of the context_processors module has moved. It would be nice to clarify to users the appropriate method for their version.

**Comment by mrkiwi-nz** [comment]
Hi. Would this PR clarify the situation?
https://github.com/rossp/django-helpdesk/compare/master...mrkiwi-nz:patch-2#diff-f47f8ca652dac550c8bc9d449ca0d253

**Comment by thecardcheat** [comment]
I'd think so, thanks!

**Comment by flinz** [comment]
@mrkiwi-nz Your PR shows no differences, however https://github.com/django-helpdesk/django-helpdesk/blob/0d8e81d7f0cb706b59715fc502b37173b9935aaa/docs/settings.rst still shows the deprecated use of ``TEMPLATE_CONTEXT_PROCESSORS``. Could you open a PR with the proper branch please?
