### ISSUE TITLE
Refactor required in query logic?

### ISSUE THREAD

**Issue by mrkiwi-nz** [django-helpdesk/django-helpdesk#404]
In staff.py, ticket_list (line 742) the logic says;
`queue, id = query.split('-')`

however in public.py, line 81 the logic is
`parts = ticket_req.split('-')`
`queue = '-'.join(parts[0:-1])`
`ticket_id = parts[-1]`

The latter accounts for queue names with a dash in them. The former does not.

I haven't tried it yet, but i would infer from this that looking up a ticket in a queue with a dash in the queue's slug would not be possible if you were logged in (and therefore exercising the code in staff.py)

Is it worth refactoring this logic into the ticket object, something like 
`@class method`
`def queue_and_id_from_query(query):`
`parts = query.split('-')`
`queue = '-'.join(parts[0:-1])`
`return queue, parts[-1]`

**Comment by rossp** [comment]
Sounds like a winner to me,

**Comment by gwasser** [comment]
The `queue_and_id_from_query` function appears to have already been implemented and in use in staff.py and public.py, so closing this. Thanks for the suggestion, @mrkiwi-nz !
