### ISSUE TITLE
Admin page for follow ups doesn't show enough information

### ISSUE THREAD

**Issue by mrkiwi-nz** [django-helpdesk/django-helpdesk#414]
What happens:
The admin page only shows the **str** of the followup ;
![helpdesk](https://cloud.githubusercontent.com/assets/17169553/16551313/407f26ee-420b-11e6-9e35-a8d99f8f37db.png)
This makes it almost impossible to find a particular followup amongst the list

What should happen:
These fields should be shown: 
[ticket.ticket_for_url], [ticket.title?], [title], [date], length-limited abstract of [comment], [new_status]

**Comment by rossp** [comment]
For most follow-ups, I wouldn't expect the Admin needs to be used much if at all. I would strongly recommend using the `django-helpdesk` staff views. I'm happy to merge a pull request for this, though.

**Comment by mrkiwi-nz** [comment]
Good point - i'll see if the staff views cover my use-case. D

**Comment by mrkiwi-nz** [comment]
Hi Ross,
I've looked at the use-case, and some issues with tickets (actually followups) cannot be fixed via the staff views, for example a helpdesk tech adds a followup to a ticket and attaches a screenshot of the error, however he accidentally picks the wrong image file and rick-rolls the entire helpdesk team.
AFAIK you can't remove an attached file?
You can fix this via the admin interface, but to find the right followup via a list of followups that all have the same string as their clickable link is hard.
This works;
select followup_id, file from helpdesk_attachment where file like '%rickroll%';
... then use the admin to get to that followup and delete the attachment.

If i submitted a PR that expands the columns in the admin, and adds a search field in tickets and followups, would this be accepted? 

As far as I can see, making the admin more usable has the downside of encouraging some users to bypass the non-admin interface, which AFAIK contains some important code paths, and this may lead to more tickets being submitted to make the admin interface as functional as the non-admin interface.
For sites that don't use the admin interface, I can't see this having any drawbacks.
For sites that sometimes use the admin interface, I can see this being very valuable.

**Comment by rossp** [comment]
Thanks for following up. I think a PR to improve `contrib.admin` support would be welcomed. Personally I see no issue making it more useful as a *system administration* tool. In most scenarios the UX for ticket management via the admin just isn't that great so users aren't likely to rely on it for day to day use.

**Comment by gwasser** [comment]
I concur with @rossp , improvements to system administration is welcome!
