### ISSUE TITLE
how can i configure to send emails for every update to ticket

### ISSUE THREAD

**Issue by farooq-ahmed** [django-helpdesk/django-helpdesk#422]
I have configured helpdesk app for queues and i am running get_email to create new tickets for incoming emails on pre configured queue email ids. The issue i am facing is when ever a new ticket is created the submitter does not get email about his ticket number and updates, same goes at the time of any updates or closure of the ticket.

I am still not very clear whether helpdesk supports sending emails to the users who sent initial email for which ticket was created. 
1) How can we configure helpdesk to send email to the ticket submitter(ticket opened via web / via email) when a new ticket is created.

I have included following settings to me settings.py file:

EMAIL_HOST = '####'
EMAIL_HOST_USER = '####'
EMAIL_HOST_PASSWORD = '#####'

HELPDESK_DEFAULT_SETTINGS = {
        'use_email_as_submitter': True,
        'email_on_ticket_assign': True,
        'email_on_ticket_change': True,
        'login_view_ticketlist': True,
        'email_on_ticket_apichange': True,
        'tickets_per_page': 25
        }

HELPDESK_AUTO_SUBSCRIBE_ON_TICKET_RESPONSE = True
HELPDESK_SUBMIT_A_TICKET_PUBLIC=True

I am using python2.7.10 and django 1.8

Regards,
Farooq

**Comment by rossp** [comment]
Emails are only sent to people who are not the actor. For example, updates will only be sent to the submitter, IF the ticket was updated by somebody other than the submitter. Likewise, ticket owner only gets an email if somebody else updates the ticket. 

Can you confirm that the submitter and actor are different users?

**Comment by gwasser** [comment]
You maybe need to import the default email template fixture first before this will work. Something like:
`python manage.py loaddata email_template.json`
on your main project.

I believe this was one thing I ran into and maybe the documentation should be a little more explicit about it.

**Comment by reduxionist** [comment]
@farooq-ahmed If the previous comment do not fully address your issue, is it something addressed by PR #385 ? That PR enhances a lot of the email functionality, and should definitely cover the use-case you describe if it is not already provided for as described by @rossp above. If that branch is what you need, then although it will be proposed for public use once I have had a chance to update the test-suite for it, in the meantime there is an updated and rebased version of it in a private repo I could make available to you.

**Comment by reduxionist** [comment]
In  the absence of any feedback to suggest otherwise, I'm assuming that our suggestions were met your needs in regards to dealing with this problem and so I am closing this ticket. Please feel free to re-open it if you still need help with this particular issue, but please open a new ticket for help with any other issue, thank you.
