### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by rossp** [django-helpdesk/django-helpdesk#424]
For various reasons I am unable to commit much time to `django-helpdesk` these days. In addition, I don't really use it that much so I am not well placed to guide things into the future.

Does anybody want to step up to guide the project into it's version 1.0 and beyond? I am happy to keep merging pull requests but I think it really deserves better stewardship.

Please post and discuss publicly here if possible. I'm happy for you to email me with questions or thoughts if you need to keep things quiet for now, but that feels a little against the idea of open-source software :)

**Comment by flinz** [comment]
@rossp I am still following the project a little, unfortunately I do not have much time on the side these days. I would be happy to help out if the new maintainer needs a litte bit of support.

**Comment by rossp** [comment]
I should add that I am happy to answer questions or provide assistance to the new maintainer. I would just love to see django-helpdesk grow and prosper, rather than languish without attention as it does right now. :)

Thanks @flinz for your offer of support for whoever comes next.

**Comment by gwasser** [comment]
I am using django-helpdesk for an internal project so I've grown somewhat familiar with it. I am interested in maintaining it. (with a bit of help from @rossp and @flinz for questions!).

I settled on using django-helpdesk because I need a ticketing system. I recently tested a bunch of them. JIRA is too expensive and heavy-handed (plus too focused on developers, a helpdesk can be IT or other types too... and I never quite feel comfortable using proprietary software anyway). For open source, many of them are too hard to get into developing (large complicated projects) and just plain look and feel old. Python and Django is easy to understand and contribute to, and I see a lot of potential in an open source django-based helpdesk.

**Comment by gwasser** [comment]
I'm happy to defer to you as maintainer @reduxionist, that's much more experience than I! I'm glad to assist.

**Comment by flinz** [comment]
@reduxionist great!

**Comment by rossp** [comment]
What do you guys think about creating a new GitHub organisation to own the code?
We can then set @reduxionist as an owner and both @flinz and @gwasser as contributors if that sounds reasonable. You have all made useful contributions to the project previously and I see no reason not to give a commit bit. It also helps share the load.

There's probably a few things like Travis CI, ReadTheDocs, and PyPi that need ownership and links transferred but not sure what best process is right now... I'll keep digging.

**Comment by rossp** [comment]
By the way - you are all fantastic humans for putting your hand up to help. Thank you.

**Comment by reduxionist** [comment]
That sounds good to me!

**Comment by flinz** [comment]
For me too!

**Comment by reduxionist** [comment]
Adding Transifex (translations) to externals list for your reference:

1. Travis CI
2. ReadTheDocs
3. PyPio
4. Transifex

**Comment by gwasser** [comment]
I'm happy to be a contributor, thanks. Sounds like a good plan.

**Comment by rossp** [comment]
To make this a little easier to keep track of...

- [ ] @rossp Pull in latest Transifex translations & commit to Git (just in case... plus, it's been a while)
- [ ] @reduxionist @flinz @gwasser to provide PyPi usernames to @rossp
- [ ] @reduxionist @flinz @gwasser to provide Transifex usernames to @rossp
- [ ] @reduxionist @flinz @gwasser to provide Travis CI usernames to @rossp
- [ ] @reduxionist @flinz @gwasser to provide ReadTheDocs usernames to @rossp
- [ ] @rossp Migrate code to new *django-helpdesk* organisation
- [ ] @rossp Add owners and contributors to new organisation
- [ ] @rossp Migrate Travis CI setup to non-rossp ownership
- [ ] @rossp Update Travis CI config to point to new GitHub location
- [ ] @rossp Migrate ReadTheDocs setup to non-rossp ownership
- [ ] @rossp Update ReadTheDocs setup to point to new GitHub locatoin
- [ ] @rossp Change PyPi ownership and add contributors to enable future PyPi releases
- [ ] @rossp Migrate Transifex project to new django-helpdesk organisation
- [ ] @rossp Add relevant contributors and owners to Transifex org
- [ ] @rossp Make sure Transifex is pointing to new GitHub org
- [ ] @reduxionist to check able to eg update setup.py, commit, and `upload sdist` to PyPi (commit should also cascade to RTD, Travis)

**Comment by flinz** [comment]
@rossp I sent usernames per email to ross@rossp

**Comment by gwasser** [comment]
I use the @gwasser username for all those services. Thanks!

**Comment by reduxionist** [comment]
PyPI, ReadTheDocs: jonathanbarratt
Transifex: jonathan.barratt
Travis: CI: reduxionist

**Comment by rossp** [comment]
Alright, all done I think! I am unable to see how to change Transifex to get .po files from the new GitHub path but not sure if I need to. Similarly I can't see a way to change ownership on Travis, but I'm not sure if such a thing exists (it's pulling code from the django-helpdesk organisation on GitHub, though).

Whenever you're ready to do a new release, you should be able to check in code and release to PyPi via `python setup.py sdist upload`. New strings should be visible in Transifex, and new commits should trigger a build on Travis CI. Fingers crossed!

I'm not really going anywhere in a rush so will still be around to answer questions etc if anything comes up. Thanks again for your help everybody :)

**Comment by reduxionist** [comment]
I will try a PyPI update once I'm back in the office on Wednesday or Thursday, depending on how fast I recover from the twelve hours of Eastward jet-lag I incur on Monday. ;)

**Comment by rossp** [comment]
Just a quick note to say that I am in absolute awe at the speed in which you have all picked this project up, nurtured it, and tidied up what in hindsight was a real lack of clarity and ownership.

I want you to know this has been a big mental burden off my shoulders. I no longer have the guilt of a good project languishing due to my inaction. Things look healthy. :)

**Comment by reduxionist** [comment]
After the sdist upload of v0.1.18 to PyPI, both a fresh "pip install" and a "pip install --upgrade" ran to succesful completion. RTD correctly updated the stable version of the docs to the new 0.1.18 tag, and Travis has continued to respond to commits by launching new builds as appropriate.

**Comment by Pauldic** [comment]
Big Thank You... to all of you!!! I am in love with your level of commitments  

    On Friday, October 28, 2016 9:09 PM, Jonathan Barratt <notifications@github.com> wrote:
 

 After the sdist upload of v0.1.18 to PyPI, both a fresh "pip install" and a "pip install --upgrade" ran to succesful completion. RTD correctly updated the stable version of the docs to the new 0.1.18 tag, and Travis has continued to respond to commits by launching new builds as appropriate.—

**Comment by rossp** [comment]
Thanks @reduxionist! I think we can pretty safely close this now, just ping me with any new questions or updates.

**Comment by reduxionist** [comment]
PyPI ownership conferred to @gwasser
