### ISSUE TITLE
Can non staff user reply to tickets and reopen closed tickets ? 

### ISSUE THREAD

**Issue by Nicoloren** [django-helpdesk/django-helpdesk#425]
Just quick questions I can't find an answer for : 

1) Can non staff user add elements or reply to a ticket already submited ?
2) Can a user (staff or no) reopen a ticket set as "closed" ?

Thank you very much for this great django app !

**Comment by reduxionist** [comment]
Hi Nicolas,

I'm on my mobile right now so please excuse my brevity.

1) As per http://django-helpdesk.readthedocs.io/en/latest/settings.html#options-that-change-ticket-updates, you can allow non-staff users to update existing tickets by setting HELPDESK_ALLOW_NON_STAFF_TICKET_UPDATE to true.

2) Staff should be able to re-open a closed ticket, but non-staff would at least require the above setting to be enabled.

**Comment by Nicoloren** [comment]
Thank you for your answer. 
It partially solved my problem. 
But if I set HELPDESK_ALLOW_NON_STAFF_TICKET_UPDATE to True, the non staff users have also access to the dashboard (with url "/helpdesk/"). 
I will figure out how to remove that access and allow them to send tickets the "classic" way.
