### ISSUE TITLE
Add coverage generation to testing

### ISSUE THREAD

**Issue by flinz** [django-helpdesk/django-helpdesk#431]
In general I feel we need to increase test coverage for this project - several bugs [recently popped up](https://github.com/django-helpdesk/django-helpdesk/projects/1) that would have benefited from this.

In order to give us a little incentive, I would like to add test coverage generation, and integrate this in the CI build.

**Comment by gwasser** [comment]
Totally agree, the testing framework should get beefed up before too many large changes are made.

**Comment by flinz** [comment]
Closing since the PR was merged.
