### ISSUE TITLE
Things which may be dropped in new 0.2

### ISSUE THREAD

**Issue by alexbarcelo** [django-helpdesk/django-helpdesk#437]
Here a quick list of stuff that I think might be considered for the 0.2. I am not advocating for removing (all of) them, but having a list may be a good idea. Tell me if I have left something out.
- [x] **Django 1.7** Ok, this seems almost done with #436, already commented in #433 
- [x] **API** According to itself, it is deprecated and would be removed on January. #198 --edit: merged in #441 
- [x] **south_migrations** and support for south in general. I am not sure on that, I have myself never used south_migrations, but given that Django 1.8 has native migrations... Is it still being used? Is it worth keeping? Sorry for my ignorance.
- [x] ~~**squash migrations** Not exactly "drop". There are not a lot of migrations, but there is some old stuff (and very bad style). A unique squashed migration may be worth doing? This would potentially mean that updates from 0.1 into 0.2 should be done in two steps, and this may be a deal breaker.~~ No. Leave the migrations for upgrading users.

**Comment by rossp** [comment]
south_migrations shouldn't be necessary if Django 1.7 is being dropped. When Django 1.7 migrations were released they needed the 'migrations' folder; the final version of South for <1.7 included code to look in south_migrations first. Having both in django-helpdesk allowed for both Django 1.6 and 1.7 compatibility.

Unsure how practical it is to squash the migrations, but the worst of them was in the South days so should be much tidier once you drop those.

**Comment by gwasser** [comment]
Do older releases (1.6 and below) need to use south_migrations to get up to 1.7 BEFORE they can use django migrations to get up to 1.10? I'm thinking of the full upgrade path here. If someone on say 1.6 needs it to upgrade up to a supported django, I would suggest that we deprecate the south_migrations in 0.2, stick a big warning in the README to upgrade/migrate ASAP, and remove in 0.3 release (as a tentative suggested date, maybe we can drop the south_migrations when django 1.11 LTS is out in April 2017).

**Comment by rossp** [comment]
The answer to that probably depends on whether the `south_migrations` are in check with the `migrations` up to the point where a Django release is no longer supported - ie could somebody on 1.6 use `south_migrations` to get to a schema state that is identical to somebody who is on 1.9 using `migrations`?

Unfortunately I do not know the answer to that, and controlling Django version deprecation and enforcing concurrent `migrations` and `south_migrations` through the transition process wasn't properly done by me. Sorry :(

I think my recommendation would be to remove `south_migrations` in 0.2 and continue with `migrations` as that has been the norm now for 4 major Django releases across 2 years. If somebody needs to update and isn't able to use the included migrations, they can always install 0.1.x as an interim step. It would be nice to formally document this but I am not sure there is an easy answer.

**Comment by gwasser** [comment]
Thanks! I'm relatively new to django so have only ever known django migrations. Given your recommendation, I'm fine with the plan to drop it in 0.2. If so, I lean toward also squashing the django migrations while we're at it in 0.2, and keeping them in sync from now on.

**Comment by rossp** [comment]
Squashing might be confusing for existing users on Django >=1.7. Say they have Django 1.9 and are up to migration 0008 (so don't yet have 0009 thru 0012), and we squash them all into a single .py file, what happens when they `./manage.py migrate helpdesk`?

It might be a non-issue, but it might also be very tricky for them to migrate.

Is there a reason not to leave the `migrations` folder as-is, especially given it's mostly Django-generated code?

**Comment by gwasser** [comment]
True. I'm fine with leaving the folder as-is as well. I don't know enough about migrations so defer to the other contributors :-)

**Comment by reduxionist** [comment]
I once asked django-users about migration-squashing best-practices and @carljm (of Django core fame) gave me this excellent advice:

"You can [squash migrations], but you should keep the old migrations around as well, 
for the sake of your existing upgrading users ... The migration-squashing system is designed to make it easy to squash migrations for new users but also keep the old ones around for upgrading 
users; it automatically takes care of making sure the right migrations are used in each case."

**Comment by alexbarcelo** [comment]
Not enough migrations to justify a squash, and given @carljm advice, then definetely leave them there. Good to know :)

Not sure about `south-migrations` folder, though. I have never used it, and I don't know how would users from South migrate.

**Comment by flinz** [comment]
I would favor dropping south migrations, since they're of no use for django>1.7. anybody needs them, the earlier versions are still around.

**Comment by alexbarcelo** [comment]
All my initial bulletpoints have been addressed, closing comment.
