### ISSUE TITLE
Error on attachement files

### ISSUE THREAD

**Issue by Nicoloren** [django-helpdesk/django-helpdesk#439]
It seems a user can't attach a file with a reply : 

`Internal Server Error: /helpdesk/tickets/2/update/

TypeError at /helpdesk/tickets/2/update/
cannot use a string pattern on a bytes-like object

Request Method: POST
Request URL: http://xxxxxxxxx.xx/helpdesk/tickets/2/update/
Django Version: 1.9.2
Python Executable: /usr/local/bin/python3.5
Python Version: 3.5.2
Python Path: ['/app', '/usr/local/bin', '/usr/local/lib/python35.zip', '/usr/local/lib/python3.5', '/usr/local/lib/python3.5/plat-linux', '/usr/local/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/site-packages', '/usr/local/lib/python3.5/site-packages/newrelic-2.70.0.51']
Server time: lun, 24 Oct 2016 15:51:13 +0200
Traceback:  

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
1.                     response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)

File "/usr/local/lib/python3.5/site-packages/helpdesk/views/staff.py" in update_ticket
1.                 mime_type=mimetypes.guess_type(filename)[0] or 'application/octet-stream',

File "/usr/local/lib/python3.5/mimetypes.py" in guess_type
1.     return _db.guess_type(url, strict)

File "/usr/local/lib/python3.5/mimetypes.py" in guess_type
1.         scheme, url = urllib.parse.splittype(url)

File "/usr/local/lib/python3.5/urllib/parse.py" in splittype
1.     match = _typeprog.match(url)

Exception Type: TypeError at /helpdesk/tickets/2/update/
Exception Value: cannot use a string pattern on a bytes-like object
Request information:
GET: No GET data

POST:
due_date_year = '2016'
new_status = '2'
csrfmiddlewaretoken = '7w8xgnOiUeKJlYD2kCA3xGkF44sDoRXe'
owner = '0'
comment = 'Voici une photo de moi'
priority = '3'
title = "Demande d'étude de raccordement"
public = '1'
due_date_day = '20'
due_date_month = '11'

FILES:
attachment = <InMemoryUploadedFile: 22053586.jpeg (image/jpeg)>
`

The problem seems to be with the file staff.py (in views) and the instruction to get the file name : 

`filename = file.name.encode('ascii', 'ignore')`

If we analyse the situation globaly, in the file forms.py we have another instruction to get the right filename : 

`filename = file.name.replace(' ', '_')`

PS : we use the last release

**Comment by reduxionist** [comment]
Thanks for the thorough bug report! It looks like it's just a case we missed during Python 2 to 3 conversions so it shouldn't take me long to come up with a patch. :)

**Comment by reduxionist** [comment]
PR #463 was merged to fix this bug so I am closing this issue. Please feel free to reopen it if you still encounter this particular problem, but please open a new issue for help with any other bug. Thanks again for report!
