### ISSUE TITLE
Proper testing for get_email.py functionality

### ISSUE THREAD

**Issue by flinz** [django-helpdesk/django-helpdesk#444]
At the moment large chunks of [get_email.py](https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/management/commands/get_email.py) remain largely untested.

Problem areas are:
- [imap and pop3 functionality](https://codecov.io/gh/django-helpdesk/django-helpdesk/src/d54017f69f75d933c357a9f49b836de748972082/helpdesk/management/commands/get_email.py#L153)
- [SOCKS proxy support](https://codecov.io/gh/django-helpdesk/django-helpdesk/src/d54017f69f75d933c357a9f49b836de748972082/helpdesk/management/commands/get_email.py#L125)

Particularly, to which degree we should test or mock imap and pop3 with socks sockets escapes me for now. I will look at extending this incrementally, but if anybody wants to help out, feel welcome.

Edit: sorry for formatting errors

**Comment by flinz** [comment]
See https://github.com/flinz/django-helpdesk/tree/tests/get-email for my active branch.

**Comment by flinz** [comment]
@gwasser something I just noticed during writing a little on tests: 
in [this line and before](https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/management/commands/get_email.py#L101), even if you set logging_type = 'none', you still add a filehandler to the default directory ``/var/log/helpdesk/``.
Thus, I think as it is it is impossible to disable logging.

I think a possible fix would be this (at least it makes it runnable in tests for me)
```python
logger = logging.getLogger('django.helpdesk.queue.' + q.slug)

if not q.logging_type or q.logging_type == 'none':
    logging.disable(logging.CRITICAL)  # disable all messages
else:
    if q.logging_type == 'info':
        logger.setLevel(logging.INFO)
    elif q.logging_type == 'warn':
        logger.setLevel(logging.WARN)
    elif q.logging_type == 'error':
        logger.setLevel(logging.ERROR)
    elif q.logging_type == 'crit':
        logger.setLevel(logging.CRITICAL)
    elif q.logging_type == 'debug':
        logger.setLevel(logging.DEBUG)
    
    logdir = q.logging_dir or '/var/log/helpdesk/'
    handler = logging.FileHandler(logdir + q.slug + '_get_email.log')
    logger.addHandler(handler)

if quiet:
    logger.propagate = False  # do not propagate ...
```
If this is correct, mind opening a quick PR to fix it?

Besides this quick fix, we should think about possibly not adding the file handler here.. I believe by defining the handlers and loggers in the django settings, you can do exactly what you're trying to do already, without hardcoding the ``FileHandler`` in the get_email method.

**Comment by gwasser** [comment]
I think what you have is the right idea in principle, but I had made it work by passing the logger to later functions; I think some extra control flow tests would be needed to check if logger is None before we can fully change it.

I'm not familiar with django's logging system, that might be the best way to re-do this. Or do you mean move the logger code already in get_email into the django app config python file?

I'm happy to take a look at this and clean it up, but I'm traveling so may not be for another week or so if that's ok.

**Comment by flinz** [comment]
@reduxionist regarding the comment here https://github.com/django-helpdesk/django-helpdesk/issues/376#issuecomment-255328840

> After looking at the socket._socketobject assignment's potential impact in the commit where it first appeared and in a current stable release, I'm led to believe that it has never actually served any purpose at all.
> [...] it might be helpful if switching back between SOCKS and vanilla sockets, but we don't

I am currently writing some tests for this, and it seems like the lines in question indeed are needed to switch the sockets between vanilla and SOCKS. This also does indeed occur, (``but we don't`` is not correct IMHO) if you have one queue configured with SOCKS and one without.

The way it is implemented at the moment dirtily hacks the default ``socket.socket`` to use either SOCKS or vanilla, which persists to the next use of socket. I would propose changing this to a proper subclassing along the lines of http://stackoverflow.com/a/3387230/1382740: it's cleaner and wouldn't cause any interference should we use ``socket`` in any other part in the future.

**Comment by reduxionist** [comment]
Good catch @flinz, my trials were all-or-nothing SOCKS usage for all queues; I completely overlooked this mixed-use case. :bowing_man: Of course, I'm all in favor of supporting it, especially through the cleaner subclassing approach you've directed us to! :smile:

**Comment by reduxionist** [comment]
@flinz, looking into implementing the cleaner SOCKS-proxy support we discussed, I thought I'd first check with you as to whether the tests/get-email branch on GitHub is current with your local one, just in case there's any further SOCKS test development I should incorporate before branching. Thanks!

**Comment by flinz** [comment]
@reduxionist yes its current but far from complete. I didnt have much time to put into this recently, so feel free to extend upon.

**Comment by gwasser** [comment]
Thanks @flinz and @reduxionist for looking into this more, all sounds good to me. I'm assuming you're working on this @reduxionist ? If so, I'll take a look at some of the other tickets. (I think you know more about the issue than I, so I appreciate it :-)

**Comment by reduxionist** [comment]
I read the code again thoroughly to make sure I could wrap my head around it, and have a rough plan in mind of how to get started. I'll branch off of @flinz's test branch as soon as I finish my own tests for the attachments refactoring/fixes -- shouldn't take much longer... 😹

**Comment by flinz** [comment]
Thanks @reduxionist for continuing the work. Seems at least now we have a proper first version in place. Closing the issue. 👍
