### ISSUE TITLE
[Errno 10061]  error at /helpdesk/tickets/submit/

### ISSUE THREAD

**Issue by JeongyongShin** [django-helpdesk/django-helpdesk#448]
After submit new ticket, below error log was show..
How can I fix it?

Request Method:
POST 

Request URL:
http://localhost:8000/helpdesk/tickets/submit/ 

Django Version:
1.10.3 

Exception Type:
error 

Exception Value:
[Errno 10061] 
 

Exception Location:
c:\anaconda\Lib\socket.py in create_connection, line 575 

Python Executable:
C:\dir\myvenv2\Scripts\python.exe 

Python Version:
2.7.12 

Python Path:
['C:\\dir\\myvenv2\\tqm',
 'C:\\dir\\myvenv2\\lib\\site-packages\\pyopenssl-0.15.1-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\ndg_httpsclient-0.4.2-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\django_disqus-0.5-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\django_markdown_deux-1.0.5-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\markdown2-2.3.1-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\django_chartit-0.2.7-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\flake8-3.0.4-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\configparser-3.5.0-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\mccabe-0.5.2-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\pycodestyle-2.0.0-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\pyflakes-1.2.3-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\django_allauth-0.28.0-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\requests-2.11.1-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\requests_oauthlib-0.7.0-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\python_openid-2.2.5-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\oauthlib-2.0.0-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\django_compressor-2.1-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\django_helpdesk-0.2.0-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\simplejson-3.10.0-py2.7-win32.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\email_reply_parser-0.5.9-py2.7.egg',
 'C:\\dir\\myvenv2\\lib\\site-packages\\django_bootstrap_form-3.2.1-py2.7.egg',
 'C:\\dir\\myvenv2\\Scripts\\python27.zip',
 'C:\\dir\\myvenv2\\DLLs',
 'C:\\dir\\myvenv2\\lib',
 'C:\\dir\\myvenv2\\lib\\plat-win',
 'C:\\dir\\myvenv2\\lib\\lib-tk',
 'C:\\dir\\myvenv2\\Scripts',
 'c:\\anaconda\\Lib',
 'c:\\anaconda\\DLLs',
 'c:\\anaconda\\Lib\\lib-tk',
 'C:\\dir\\myvenv2',
 'C:\\dir\\myvenv2\\lib\\site-packages']
 

Server time:
Tue, 8 Nov 2016 14:39:10 +0900

**Comment by reduxionist** [comment]
At the moment, all I can tell you is that the exception message you received is the [Windows code for socket connection refused](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx), so the first thing I would check is that your [django.contrib.sites](https://docs.djangoproject.com/en/1.10/ref/contrib/sites/) Site object has a valid domain setting that can be used to reach your Django project at (possibly localhost:8000 based on the reported request URL). If that doesn't work, then please provide more information, such as a stacktrace and relevant Django and environment settings, and we'll try to help you resolve this as best we can.

**Comment by reduxionist** [comment]
Although it's not simple to reason about this without a stacktrace, another likely suspect worth checking is any email settings that may be used by your installation: if you haven't explicitly configured a SMTP server, and you don't happen to have one configured to Django's default expectations, then ticket submission could trigger this error when it tries to send any applicable notifications.

**Comment by reduxionist** [comment]
As we provided a suggested fix more than thirty days ago but haven't heard anything back, I'm assuming all is good and closing this ticket. Please feel free to re-open it if you still need help with this issue, but please open a new ticket for help with any other issue. Thanks!

**Comment by Nguy3nImprovd** [comment]
Hi,

I have followed the suggested fix where I updated my SITE domain to localhost and currently added imap email to my queue and still getting this error.

Is there any patches that I can apply.

django - 3.2
python - 3.9
helpdesk - 0.3.2
