### ISSUE TITLE
Update Contribution Guidelines

### ISSUE THREAD

**Issue by reduxionist** [django-helpdesk/django-helpdesk#449]
As suggested in #188 strengthen contribution test requirements:
1. provide stricter guidelines such as:
    - no patches or new commits without unit tests
    - new test(s) for each new feature added or issue fixed
    - start refactorings by adding tests that would be sensitive to any related breaking changes 
2. consider moving or paraphrasing `docs/contributing.rst` to a root-level `CONTRIBUTING` file
3. possibly add potential guidance on unit vs. integration test balance

**Comment by gwasser** [comment]
I agree with all of these ideas.

**Comment by gwasser** [comment]
Since the CONTRIBUTING file was updated and merged in #486, I'll close this ticket for now, but certainly welcome any other ideas for updating the policy!
