### ISSUE TITLE
ticket list view - order by creation time bug

### ISSUE THREAD

**Issue by reduxionist** [django-helpdesk/django-helpdesk#450]
I haven't even begun to look at the JS behind our beautiful new UI but we seem to be using lexicographical, rather than chronological, sorting for this column.

**Comment by gwasser** [comment]
Hmm, so it makes use of DataTables (https://datatables.net/reference/option/order) and as far as I can tell, there's no option to sort by non-lexicographical order (I'm guessing our numbered tickets is a bit of a corner case?).

Rather than mess with the library, I wonder if we could have some magic to insert leading zeros into the displayed numbers so they're compatible with lexicographical order? Or would that be too confusing?

**Comment by reduxionist** [comment]
when sorting by ctime, an example would be that 20 mins was ranked < 30 seconds.

I didn't even think to check effect of our ticket naming scheme!

You may be pointing to the solution though - disable time-ago humanization if it's coming from server-side...

**Comment by gwasser** [comment]
Oh I apologize, misread something and thought you were looking at a different column. My bad!

I think my comment still applies though. Should it by default list as "0 mins 30 seconds" so it gets sorted before 20 mins? A bit more wordy, but maybe ok.

**Comment by reduxionist** [comment]
While normalizing with zeroes like that works in the examples used so far, applied to a wider range of creation times (seconds to months is 6 units) I think it gets so wordy that it's not worth using humanization any more. It might look cleaner to just output a standard javascript date type since DataTables can sort those correctly out-of-the-box.

Alternatively, we could use the absolute datetime value (which is stored in the title attribute of the span enclosing the relative value), as an orthogonal data source to sort by as per [this DataTables example](https://datatables.net/manual/data/orthogonal-data#Predefined-values). We'd probably need to adjust the absolute datetime format to be numeric-sort-friendly (e.g. epoch time), or use one of the [DataTables date sorting plugins](https://datatables.net/plug-ins/sorting/#Plug-ins), too.

As a user, sometimes I appreciate relative dates and sometimes I want to know exactly when something occurred and find the coarse-grained months/years -ago format frustrating, so any approach is OK with me really as long it sorts correctly in the end! 😈

**Comment by gwasser** [comment]
Turns out the solution seemed much simpler than I was worried about, thanks for doing some preliminary research! See PR #455 .

**Comment by reduxionist** [comment]
Fixed by #455 (sub-second precision not required IMO!)

Really loving the new front-end, well done @gwasser!!
