### ISSUE TITLE
Requirements for release of 0.2.0

### ISSUE THREAD

**Issue by gwasser** [django-helpdesk/django-helpdesk#458]
So I was thinking, how's 0.2.0 going for everyone? What tasks need done before we declare it OK to use and release it (and push to PyPI)?

At the moment, #376 seems like it should be resolved before pushing out. Agree? #444 too possibly while resolving #376 though since its just more testing. Maybe #413 too.

Those are just bugfixes, what are your thoughts on new features?

**Comment by reduxionist** [comment]
I just issued a PR for the IMAP and POP3 components of 444, but not for the SOCKS portion.
Fixes for 376 and 413, and some other small bugs, are ready and a part of the next PR I'll issue once the current one has made it through the review process and its code finalized for me to rebase on.  
As for features, the new UI is a big enough one for me to justify the 0.2 release on its own, but we've also got your support for local/filesystem-backed email queues too! 😀   While the refactoring of attachment-handling that I will submit for review next isn't a huge change, it touches enough different modules, and is connected to enough different issues, that personally, I will be focussed only on additional testing until until there's some real-world feedback on whether it provides the intended improved stability or not.

**Comment by pawelmarkowski** [comment]
I have additional request regarding to lack of functionality. In my opinion if unregistered user authorise and get access to its task (confirmed by email and task #) - he/she should get access to all unresolved tasks list. It is not user friendly and confusing when you have requested 10 tasks and to check status online you must find proper email in your mailbox. It is other possibility to setup other user group that has a permission to check own requests.

**Comment by gwasser** [comment]
@pawelmarkowski To make sure I understand correctly, you want to make sure that when a submitter follows up on a ticket using the public web interface, the submitter can view all tickets submitted from the same email address, correct?

If so, I agree! The public web portal is probably some of the most untouched code at the moment, it needs an overhaul for sure! I like your idea and definitely think it should get documented for a future release. However, I suspect the public web portal is a little more down the road (beyond version 0.2.0, which I think we mostly dedicated to the improved web interface and improved unit testing so it is easier to make big changes later without breakage).

I wonder if it would be better to start a dev wiki so that we can better track ideas for a roadmap from current version (0.1) to 0.2 and beyond.

**Comment by pawelmarkowski** [comment]
@gwasser yes, you understand correctly. I am not sure, is user able to add comment via public web interface - in my opinion it should be possible to add a comment after authorisation.

**Comment by gwasser** [comment]
I believe the user can add a comment via public web interface, but to be honest not even sure. The public interface isn't a feature I use much. It definitely needs an overhaul! Thanks for the feedback, will definitely look at that feature if it isn't already implemented.

**Comment by gwasser** [comment]
@reduxionist on #502 you mentioned dropping Django < 1.11. I slightly feel like we should keep all Django > 1.8 for the 0.2 release and tarball it very soon (after a few more get_mail bug fixes) so it can get in public hands for testing soon. Branch it off in git to its own 0.2 branch, and switch master to 0.3 development which would target only Django >= 1.11. Any thoughts?

**Comment by reduxionist** [comment]
In that case, I mis-spoke because the issue was caused only by Dj.1.8 and Py.2, so there was no reason to suggest dropping support for 1.9 and 1.10. It was also my intention to point out that dropping 1.8 would be in keeping with our official support policy of always supporting most recent LTS, perhaps that is where I confused the issue as I did not mean to say only from current LTS up, just that we did not have to go all the way back to including the previous LTS as well. In fact, off the top of my head, I'm not aware of any maintenance burden it would cause to (un)officially support Dj1.8 under Py3, it's only under Py2 that I am eager to drop (only) Dj 1.8. :)

**Comment by gwasser** [comment]
I think we could fall back to Django 1.11+ on Py2 and Py3 for the 0.2 release, makes sense to me.

I went thru and labeled all the tickets based on their type, we have about a dozen outstanding bug tickets, many of them not too complex, so my proposal is that we consider 0.2 in "feature freeze" and get those bugs ironed out and more unit tests, to get 0.2 out the door for usage and testing soon.

**Comment by gwasser** [comment]
Someone left a comment (and I think deleted it? can't find it) that https://djangopackages.org/packages/p/django-helpdesk/ shows we don't support Py3. Look into updating that page after release 0.2.

**Comment by gwasser** [comment]
For some rationale on why it's ok to require Django 1.11 without hurting past installs, see [Django's deprecation policy](https://docs.djangoproject.com/en/dev/internals/release-process/#deprecation-policy).

**Comment by gwasser** [comment]
Going to close this issue as I believe the outstanding issues for 0.2.0 were resolved, at least sufficiently for the new release. Will be good to have a python 3 compatible release out finally!
