### ISSUE TITLE
Error when integrating with other apps (usersettings name clash) [FIX proposal]

### ISSUE THREAD

**Issue by radeksvarz** [django-helpdesk/django-helpdesk#460]
When used e.g. with xadmin - both applications are having User 1-1 relation in the model class UserSettings.

This can happen when integrating with other applications as well.

I propose to change the related_name of UserSettings into something like "helpdesksettings".

**Comment by reduxionist** [comment]
Thanks for reporting this, I love xadmin so I'm very disappointed we don't play nicely with it. 

You're right, of course, we should definitely namespace our user settings. We only recently namespaced our URLs so I'm glad you pointed this out now! 😁

**Comment by flinz** [comment]
Opened a PR with the proposed fix! Sorry for stealing work from you @reduxionist :)

**Comment by reduxionist** [comment]
@flinz please always feel free to steal work from me... No really, anytime! 😉 

@radeksvarz Thanks again for bringing this to our attention, @flinz graciously provided the needed code and we hope to be compatible with other 1-1 UserSettings containing apps; but please do let us know if you encounter any further issues. 😃
