### ISSUE TITLE
Datatable Issue With Empty Table

### ISSUE THREAD

**Issue by Pauldic** [django-helpdesk/django-helpdesk#470]
This error `jquery.min.js:2 Uncaught TypeError: Cannot set property '_DT_CellIndex' of undefined` only occurs if the record is empty. It can be replicated using a newly installed instance of HelpDesk. `http://localhost:8000/helpdesk/tickets/` ...../helpdesk/templates/helpdesk/ticket_list.html lines 237-238 have
`{% empty %}
<tr><td colspan='7'>{% trans "No Tickets Match Your Selection" %}</td></tr>`

**Solution:**
- Delete lines 237-238 (ticket_list.html)
- Replace line 12 (`responsive: true`) with `"oLanguage": {"sEmptyTable": "No Tickets Match Your Selection"}, responsive: true`

**NOTE**: DataTables currently doesn't support colspan or rowspan in the tbody. 
@jonathanbarratt Please help implement this fix

REF:  [How to Change datatable default empty table message](http://stackoverflow.com/questions/31983492/how-to-change-datatable-default-empty-table-message)

**Comment by reduxionist** [comment]
Thanks for the bug report, and for the suggested fix! We will patch ASAP...

**Comment by Pauldic** [comment]
Thanks @reduxionist I love the work you guys are doing #ILoveDjangoHelpdesk

**Comment by reduxionist** [comment]
Thanks @Pauldic! You make it easy by including a fix with an issue, so we're grateful to have users like yourself!

As implemented in PR #471, your fix solved it for me so I'm closing this issue, but if it doesn't work for you then please do let us know here.
