### ISSUE TITLE
Unable to create new Queue because of multiple content_type

### ISSUE THREAD

**Issue by Pauldic** [django-helpdesk/django-helpdesk#472]
`get() returned more than one ContentType -- it returned 4!`

This can be replicated if you deploy django-helpdesk by adding the source to an existing Django Project which possibly has other apps with one or more models named queue.

In my case:
select * from django_content_type where model = 'queue'; returns 4 records.

Trace this to ....../helpdesk/models.py line 323 `content_type=ContentType.objects.get(model="queue"),`

**My Proposed Solution**
Replace line 323 with content_type = ContentType.objects.get_for_model(self.__class__)

**Comment by reduxionist** [comment]
Thanks for the bug report and especially for the proposed fix! Although I'm currently traveling and still not yet able to implement immediately, I should be able to examine this within 24hours, and appreciate your patience on this.

**Comment by reduxionist** [comment]
Your proposed solution fixed the issue for me too so it has been implemented as PR #475 , currently awaiting review before merger into master. Hope it makes helpdesk play nice with other apps that have queues, like Asterisk queues maybe? 😉 

Thanks for the contribution! 🍰

**Comment by flinz** [comment]
Merged the fix, thanks for the work guys!
