### ISSUE TITLE
Problem with collectstatic and jquery-ui/images?

### ISSUE THREAD

**Issue by adrianboyko** [django-helpdesk/django-helpdesk#479]
With Django 1.10, whitenoise 3.2.1, and helpdesk 0.1.18, I get the following error when running `collectstatic`:

`Post-processing 'helpdesk/jquery-ui-1.12.0.min.css' failed! [...] The CSS file 'helpdesk/jquery-ui-1.12.0.min.css' references a file which could not be found: helpdesk/"images/ui-icons_555555_256x240.png"`

The css is located at `helpdesk/static/helpdesk/`
The png is located at `helpdesk/static/helpdesk/vendor/jquery-ui/images/`
Should the `images` folder actually be `helpdesk/static/helpdesk/images/`?

**Comment by reduxionist** [comment]
Hi, thanks for reporting this bug! The new frontend was the biggest change in this version, in fact it's what earned the bumped minor-version instead of just another point release, so I'm pleasantly surprised that what frontend bugs we are having are this small. I know that's of no consolation to you, but we will still look into this right away, so although I can't confirm your analysis off the top of my head you should at least get an answer, if not a patch, within 24hours. Apologies for the inconvenience! 🙇

**Comment by adrianboyko** [comment]
Oops, looks like a false alarm! `images` *is* in the correct location in the 0.1.18 release although it looks out of place in master.

**Comment by reduxionist** [comment]
Cool! Well thanks for taking the time to report it to us anyway; we know there must still be bugs hiding out there somewhere, so every effort is appreciated! 🍰

**Comment by adrianboyko** [comment]
In case anybody else runs into this, it seems that Django's collectstatic chokes on url patterns that it finds in the comments of jquery-ui-1.12.0.min.css. Specifically, strings like
`url(%22images%2Fui-icons_555555_256x240.png%22)`
are matched and then processed into bogus file names like 
`helpdesk/"images/ui-icons_555555_256x240.png"`

The collectstatic error went away after I deleted the offending comments from jquery-ui-1.12.0.min.css.

**Comment by gwasser** [comment]
I removed the comment in jquery-ui-1.12.0.min.css as part of #507 so hopefully fixes the issue in 0.2.0 and beyond.

**Comment by adrianboyko** [comment]
Looks like there are offending comments in 0.2.3 too. On a tangent, while looking at some alternate solutions to this problem (none of which have panned out, yet), I noticed some apparent duplicates in the repository. E.g.:

    1) django-helpdesk/helpdesk/static/helpdesk/jquery-ui-1.12.0.min.js
    2) django-helpdesk/helpdesk/static/helpdesk/vendor/jquery-ui/jquery-ui.min.js

Is this intentional? The first doesn't have a corresponding "images" directory so the image links in it cause problems.

**Comment by gwasser** [comment]
It was briefly intentional while I was moving scripts into the vendor directory to clean it up. Should have removed the top level one a while back though :-) thanks for reminding me, I'll reopen this to remind me to do it before the 0.2.4 release.

**Comment by gwasser** [comment]
I removed the comment again, as well as cleaned up the duplicate jquery static files, so should be all good in `master` now. Bugfix release should come shortly. Thanks!

**Comment by somesmart** [comment]
I just installed 0.2.4 and I'm getting the same error message on /helpdesk/static/helpdesk/vendor/jquery-ui/jquery-ui.css

**Comment by gwasser** [comment]
Thanks @somesmart I updated that file as well, and expect to push out a 0.2.5 soon to fix that. Sorry about the error!

**Comment by somesmart** [comment]
Thanks! Looks like it's happening on  /helpdesk/static/helpdesk/vendor/jquery-ui/jquery-ui.theme.css as well.

**Comment by gwasser** [comment]
Thanks! Interesting, I had done a `collectstatic` and did not receive any errors. I removed the comment on that file and committed to `master`. I suppose I'll need another small bugfix release, oops.
