### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by J-A-M** [django-helpdesk/django-helpdesk#480]
The install document states when you want django_helpdesk to be at the root of the url patterns to use

`url(r'', include('helpdesk.urls', namespace='helpdesk')),`
In django 1.10.5 This does not work and produces a reverse lookup failure for helpdesk_home.
Changing this to 
`url(r'', include('helpdesk.urls')),`
solves the issue.

**Comment by gwasser** [comment]
Hmm, my test cases use `namespace='helpdesk'` with Django 1.10.5 and it seems to work fine. I believe we did some work to namespace django-helpdesk so it plays nicely with other apps, but that work might mostly be in v0.2. Which version of django-helpdesk are you using?

**Comment by J-A-M** [comment]
Django 1.10.5 with the release version of Django Helpdesk version 0.1.18 from https://pypi.python.org/pypi/django-helpdesk
i.e. pip install django-helpdesk as per instructions.

**Comment by reduxionist** [comment]
I believe this is fixed in master, aka v0.2. I'll leave this issue open until I have the time to double-check with a manual test, however.

**Comment by gwasser** [comment]
Our demo project for v0.2 uses the config as provided in the instructions, so I believe it works fine. I'm going to close it for now but if you still run into trouble, let me know!
