### ISSUE TITLE
Install documentation missing SITE_ID

### ISSUE THREAD

**Issue by J-A-M** [django-helpdesk/django-helpdesk#481]
I previously mentioned a documentation issue, there is still a problem.

To get it to work I had to remove     'django.contrib.sites',  from INSTALLED_APPS.
With this missing I can login and configure (after making the change in the [previous post](https://github.com/django-helpdesk/django-helpdesk/issues/480))

However when I press submit on a new ticket I get
`RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

But, if I restore django.contrib.sites I get

`DoesNotExist: Site matching query does not exist.`
for /login/

**Comment by J-A-M** [comment]
According to [This answer](http://stackoverflow.com/questions/35388637/runtimeerror-model-class-django-contrib-sites-models-site-doesnt-declare-an-ex/35389220) you need to add
`SITE_ID = 1` to settings.py
This seems to work

**Comment by gwasser** [comment]
Yes now that you mention it, I had to use `SITE_ID = 1` on my testing project and it somehow slipped my mind to add this to documentation. Good catch!

**Comment by reduxionist** [comment]
Thanks for the report @J-A-M and thanks again for the fix @gwasser! 

Closed by #485
