### ISSUE TITLE
Update project settings on github

### ISSUE THREAD

**Issue by gwasser** [django-helpdesk/django-helpdesk#492]
Specifically, I see other projects adding tags on github, and setting their license to be displayed on the status bar with the number of branches, etc. I don't think I have access to update those.

**Comment by gwasser** [comment]
@reduxionist @rossp Would you be ok with setting me as a project manager or whatever the permission set is to make these level of changes? General clean-ups and streamlines :-)

**Comment by rossp** [comment]
Sounds good to me - you should now be able to make changes to the org & repository.
