### ISSUE TITLE
internal error 500 on save query

### ISSUE THREAD

**Issue by pprolancer** [django-helpdesk/django-helpdesk#493]
when save a query we will face with internal error:
seems we have an error decoding in views/staff.py line 818:
https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/views/staff.py#L818

        try:
            query_params = json.loads(b64decode(str(saved_query.query)))
        except ValueError:
            # Query deserialization failed. (E.g. was a pickled query)
            return HttpResponseRedirect(reverse('helpdesk:list'))

![image](https://cloud.githubusercontent.com/assets/13080577/23833484/a328eb3e-075b-11e7-8a11-cb46d570a134.png)

**Comment by gwasser** [comment]
Merged in your #494 to address this in python 3, and I added extra patch in #544 to support python 2. Thanks! Let me know if you still run into trouble.
