### ISSUE TITLE
 Queue email submission settings

### ISSUE THREAD

**Issue by manishhub9** [django-helpdesk/django-helpdesk#495]
I know this is not a real issue or bug but i am stuck so i posted here. First i follow the docs install commands and run the helpdesk project but when i create tickets its give me connection refuse error because my email is not configured for queues.

So please post example for queue email configuration. 

Right now i get this error when i create tickets

```
error at /
[Errno 111] Connection refused
Request Method:	POST
Request URL:	http://xxx.xxx.xx.xx:8000/
Django Version:	1.9.2
Exception Type:	error
Exception Value:	
[Errno 111] Connection refused
Exception Location:	/usr/lib/python2.7/socket.py in create_connection, line 575
Python Executable:	/home/ekodev/djago_helpdesk/bin/python
Python Version:	2.7.12
Python Path:	
['/home/ekodev/djago_helpdesk/myhelpdesk',
 '/home/ekodev/djago_helpdesk/lib/python2.7',
 '/home/ekodev/djago_helpdesk/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/ekodev/djago_helpdesk/lib/python2.7/lib-tk',
 '/home/ekodev/djago_helpdesk/lib/python2.7/lib-old',
 '/home/ekodev/djago_helpdesk/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/ekodev/djago_helpdesk/local/lib/python2.7/site-packages',
 '/home/ekodev/djago_helpdesk/lib/python2.7/site-packages']

```

**Comment by gwasser** [comment]
Hi there, sorry about the trouble! In the Queue management screen, be sure you have all of the following fields set up, if you are using IMAP or POP:

- Email Address : set field to whatever the email is (manishhub9@example.com) that you are trying to access over IMAP or POP.
- Email Box Type : select either IMAP or POP3 from the drop down
- Email Hostname : select hostname or IP address for your mail server (maybe you want imap.google.com or something similar)
- Email Port : leave it blank for defaults, but you may need to enter a port number here, check your mail server documentation
- Use SSL For Email? : check it to use SSL. This may be required if you're using a mail provider like google, I'm not sure.
- Email Username / Password : be sure this is filled out with your credentials
- IMAP Folder : probably the default is fine, but double check if you need to select a different folder apart from 'INBOX'

That should be all you need to get started. If you have all that, then try to ping the email server hostname or IP address to make sure there's no firewall or other problem. If you need to use a proxy, you also need to select the SOCKS options at the bottom of the Queue configuration.

Does that help? If not, maybe you can share your configuration and errors with us.

**Comment by manishhub9** [comment]
Thanks for your reply. 

Here is my project structure :
My setting.py file of helpdesk which is :
/home/user/djago_helpdesk/lib/python2.7/site-packages/helpdesk/settings.py:-
```
"""
Default settings for django-helpdesk.

"""

from django.conf import settings


try:
    DEFAULT_USER_SETTINGS = settings.HELPDESK_DEFAULT_SETTINGS
except:
    DEFAULT_USER_SETTINGS = None

if not isinstance(DEFAULT_USER_SETTINGS, dict):
    DEFAULT_USER_SETTINGS = {
        'use_email_as_submitter': True,
        'email_on_ticket_assign': True,
        'email_on_ticket_change': True,
        'login_view_ticketlist': True,
        'email_on_ticket_apichange': True,
        'tickets_per_page': 25
    }


HAS_TAG_SUPPORT = False

##########################################
# generic options - visible on all pages #
##########################################

# redirect to login page instead of the default homepage when users visits "/"?
HELPDESK_REDIRECT_TO_LOGIN_BY_DEFAULT = getattr(settings,
                                                'HELPDESK_REDIRECT_TO_LOGIN_BY_DEFAULT',
                                                False)

# show knowledgebase links?
HELPDESK_KB_ENABLED = getattr(settings, 'HELPDESK_KB_ENABLED', True)

# show extended navigation by default, to all users, irrespective of staff status?
HELPDESK_NAVIGATION_ENABLED = getattr(settings, 'HELPDESK_NAVIGATION_ENABLED', False)

# use public CDNs to serve jquery and other javascript by default?
# otherwise, use built-in static copy
HELPDESK_USE_CDN = getattr(settings, 'HELPDESK_USE_CDN', False)

# show dropdown list of languages that ticket comments can be translated into?
HELPDESK_TRANSLATE_TICKET_COMMENTS = getattr(settings,
                                             'HELPDESK_TRANSLATE_TICKET_COMMENTS',
                                             False)

# list of languages to offer. if set to false,
# all default google translate languages will be shown.
HELPDESK_TRANSLATE_TICKET_COMMENTS_LANG = getattr(settings,
                                                  'HELPDESK_TRANSLATE_TICKET_COMMENTS_LANG',
                                                  ["en", "de", "fr", "it", "ru"])

# show link to 'change password' on 'User Settings' page?
HELPDESK_SHOW_CHANGE_PASSWORD = getattr(settings, 'HELPDESK_SHOW_CHANGE_PASSWORD', False)

# allow user to override default layout for 'followups' - work in progress.
HELPDESK_FOLLOWUP_MOD = getattr(settings, 'HELPDESK_FOLLOWUP_MOD', False)

# auto-subscribe user to ticket if (s)he responds to a ticket?
HELPDESK_AUTO_SUBSCRIBE_ON_TICKET_RESPONSE = getattr(settings,
                                                     'HELPDESK_AUTO_SUBSCRIBE_ON_TICKET_RESPONSE',
                                                     False)


############################
# options for public pages #
############################

# show 'view a ticket' section on public page?
HELPDESK_VIEW_A_TICKET_PUBLIC = getattr(settings, 'HELPDESK_VIEW_A_TICKET_PUBLIC', True)

# show 'submit a ticket' section on public page?
HELPDESK_SUBMIT_A_TICKET_PUBLIC = getattr(settings, 'HELPDESK_SUBMIT_A_TICKET_PUBLIC', True)


###################################
# options for update_ticket views #
###################################

# allow non-staff users to interact with tickets?
# this will also change how 'staff_member_required'
# in staff.py will be defined.
HELPDESK_ALLOW_NON_STAFF_TICKET_UPDATE = getattr(settings,
                                                 'HELPDESK_ALLOW_NON_STAFF_TICKET_UPDATE',
                                                 False)

# show edit buttons in ticket follow ups.
HELPDESK_SHOW_EDIT_BUTTON_FOLLOW_UP = getattr(settings,
                                              'HELPDESK_SHOW_EDIT_BUTTON_FOLLOW_UP',
                                              True)

# show delete buttons in ticket follow ups if user is 'superuser'
HELPDESK_SHOW_DELETE_BUTTON_SUPERUSER_FOLLOW_UP = getattr(
    settings, 'HELPDESK_SHOW_DELETE_BUTTON_SUPERUSER_FOLLOW_UP', False)

# make all updates public by default? this will hide the 'is this update public' checkbox
HELPDESK_UPDATE_PUBLIC_DEFAULT = getattr(settings, 'HELPDESK_UPDATE_PUBLIC_DEFAULT', False)

# only show staff users in ticket owner drop-downs
HELPDESK_STAFF_ONLY_TICKET_OWNERS = getattr(settings, 'HELPDESK_STAFF_ONLY_TICKET_OWNERS', False)

# only show staff users in ticket cc drop-down
HELPDESK_STAFF_ONLY_TICKET_CC = getattr(settings, 'HELPDESK_STAFF_ONLY_TICKET_CC', False)

# allow the subject to have a configurable template.
HELPDESK_EMAIL_SUBJECT_TEMPLATE = getattr(
    settings, 'HELPDESK_EMAIL_SUBJECT_TEMPLATE',
    "{{ ticket.ticket }} {{ ticket.title|safe }} %(subject)s")

# default fallback locale when queue locale not found
HELPDESK_EMAIL_FALLBACK_LOCALE = getattr(settings, 'HELPDESK_EMAIL_FALLBACK_LOCALE', 'en')


########################################
# options for staff.create_ticket view #
########################################

# hide the 'assigned to' / 'Case owner' field from the 'create_ticket' view?
HELPDESK_CREATE_TICKET_HIDE_ASSIGNED_TO = getattr(
    settings, 'HELPDESK_CREATE_TICKET_HIDE_ASSIGNED_TO', False)


#################
# email options #
#################


# default Queue email submission settings
QUEUE_EMAIL_BOX_TYPE = getattr(settings, 'QUEUE_EMAIL_BOX_TYPE', None)
QUEUE_EMAIL_BOX_SSL = getattr(settings, 'QUEUE_EMAIL_BOX_SSL', None)
QUEUE_EMAIL_BOX_HOST = getattr(settings, 'QUEUE_EMAIL_BOX_HOST', None)
QUEUE_EMAIL_BOX_USER = getattr(settings, 'QUEUE_EMAIL_BOX_USER', None)
QUEUE_EMAIL_BOX_PASSWORD = getattr(settings, 'QUEUE_EMAIL_BOX_PASSWORD', None)


# only allow users to access queues that they are members of?
HELPDESK_ENABLE_PER_QUEUE_STAFF_PERMISSION = getattr(
    settings, 'HELPDESK_ENABLE_PER_QUEUE_STAFF_PERMISSION', False)

```

My project /home/user/djago_helpdesk/myhelpdesk/myhelpdesk/setting.py :-

```
"""


Django settings for myhelpdesk project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
# from myhelpdesk.utils.variables import _POSTGRES_HOST, _POSTGRES_PORT, _POSTGRES_USERNAME, _POSTGRES_PASSWORD, _POSTGRES_DBNAME
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$^wi3eb=vpqz_u=d2a!kv#7s(s&3f8ysc15^j$2iw&hy9h^n=_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for determining domain url for use in emails
    'django.contrib.humanize',  # Required for elapsed time formatting
    'markdown_deux',  # Required for Knowledgebase item formatting
    'bootstrapform', # Required for nicer formatting of forms with the default templates
    'helpdesk',  # This is us!
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myhelpdesk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myhelpdesk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'django_helpdesk',
        'USER': 'postgres',
        'PASSWORD': 'xxxxxxxx',
        'HOST': 'xxx.xxx.xx.xx',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_PATH = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'


SITE_ID = 1

LOGIN_URL = '/helpdesk/login/'


```

My Queue setting are at admin pannel of app:

E-Mail Address : myadav@hub9.io
Locale : en
Escalation Days:
New Ticket CC Address:
Updated Ticket CC Address:
E-Mail Box Type: IMAP (I check both POP3 and IMAP and i enable IMAP form my gmail account)
E-Mail Hostname:imap.gmail.com(i use pop.gmail.com for POP3)
E-Mail Port: 993 (for POP3 995)
E-Mail Username:myadav
E-Mail Password: my password of gmail
IMAP Folder:
E-Mail Check Interval:
Socks Proxy Type:
Socks Proxy Host:
Socks Proxy Port:


But still my problem is same when i create new ticket and submit it gives me error:
```
error at /
[Errno 111] Connection refused
Request Method:	POST
Request URL:	http://000.000.00.00/
Django Version:	1.9.2
Exception Type:	error
Exception Value:	
[Errno 111] Connection refused
Exception Location:	/usr/lib/python2.7/socket.py in create_connection, line 575
Python Executable:	/home/ekodev/djago_helpdesk/bin/python2
Python Version:	2.7.12
Python Path:	
['/home/ekodev/djago_helpdesk/myhelpdesk',
 '/home/ekodev/djago_helpdesk/bin',
 '/home/ekodev/djago_helpdesk/lib/python2.7',
 '/home/ekodev/djago_helpdesk/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/ekodev/djago_helpdesk/lib/python2.7/lib-tk',
 '/home/ekodev/djago_helpdesk/lib/python2.7/lib-old',
 '/home/ekodev/djago_helpdesk/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/ekodev/djago_helpdesk/local/lib/python2.7/site-packages']
Server time:	Sat, 18 Mar 2017 07:54:40 +0000
```

Django Version: 1.9.2
Python Version: 2.7.12
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.humanize',
 'markdown_deux',
 'bootstrapform',
 'helpdesk']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/home/ekodev/djago_helpdesk/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/home/ekodev/djago_helpdesk/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/ekodev/djago_helpdesk/local/lib/python2.7/site-packages/helpdesk/views/public.py" in homepage
  45.                 ticket = form.save()

File "/home/ekodev/djago_helpdesk/local/lib/python2.7/site-packages/helpdesk/forms.py" in save
  469.             files=files,

File "/home/ekodev/djago_helpdesk/local/lib/python2.7/site-packages/helpdesk/lib.py" in send_templated_mail
  155.     return msg.send(fail_silently)

File "/home/ekodev/djago_helpdesk/local/lib/python2.7/site-packages/django/core/mail/message.py" in send
  292.         return self.get_connection(fail_silently).send_messages([self])

File "/home/ekodev/djago_helpdesk/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py" in send_messages
  100.             new_conn_created = self.open()

File "/home/ekodev/djago_helpdesk/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py" in open
  58.             self.connection = connection_class(self.host, self.port, **connection_params)

File "/usr/lib/python2.7/smtplib.py" in __init__
  256.             (code, msg) = self.connect(host, port)

File "/usr/lib/python2.7/smtplib.py" in connect
  316.         self.sock = self._get_socket(host, port, self.timeout)

File "/usr/lib/python2.7/smtplib.py" in _get_socket
  291.         return socket.create_connection((host, port), timeout)

File "/usr/lib/python2.7/socket.py" in create_connection
  575.         raise err

Exception Type: error at /
Exception Value: [Errno 111] Connection refused

@gwasser  Please help me out i am stuck at this point. And i am new to Django Devlopment.

**Comment by gwasser** [comment]
Hi @manishhub9 so a couple of things to mention:

- First, you shouldn't need to change the settings.py file in the helpdesk app itself. Those are the defaults. If you need to change something, you override the setting with a new value in your project settings.py file.
- Second, according to the [Google support page](https://support.google.com/mail/answer/7126229?hl=en), your Email account name should be your full email address, so you may need to update that (use myadav@hub9.io as the user name and not just myadav).
- The Google support page also says to enable SSL. You didn't mention if you have it checked or not, so make sure SSL is enabled for the queue.

It just now occurs to me that this shouldn't make a difference for normal operation, I believe these settings are only used by the `get_mail.py` script to poll email for new tickets and comments.

Since you are running into trouble when creating tickets, it may be having trouble sending outbound email. In your project `settings.py` file, add the following:
`EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'`
This will cause any email to be printed to the console instead of sent out via SMTP. Try again and see if you can make tickets and get an email message on the console. If that works, then we will need to configure your EMAIL_BACKEND some more but at least in the right direction!

Django docs have more info on how to set up an EMAIL_BACKEND for a project: https://docs.djangoproject.com/en/1.8/topics/email/

**Comment by manishhub9** [comment]
@gwasser  Thanks for your reply

**Comment by gwasser** [comment]
You're welcome! Hope you were able to get it working.

**Comment by mrkiwi-nz** [comment]
Also, a note for gmail users; AFAIK gmail requires that in some situations an "application password" is set[0] - this is especially true if you use 2fa (2 factor authentication) which you absolutely should be using.
Because get_email.py (or more correctly, the management command) can't handle 2fa, you need to set up an application password and use that in your config.

[0]https://support.google.com/accounts/answer/185833?hl=en
