### ISSUE TITLE
Spanish(MX) translation

### ISSUE THREAD

**Issue by andresf01** [django-helpdesk/django-helpdesk#496]
Hello
I've finished the translation for Spanish Language.
Regards

**Comment by gwasser** [comment]
Thank you @andresf01 for the contribution! I've pulled the es_MX file off of transifex and will do a pull request momentarily on your behalf.

**Comment by reduxionist** [comment]
Thanks very much for the contribution @andresf01! 🏅 I know how much work the translations are, our UI changes whenever I get to 95% of mine! 😆 

@gwasser processed this in PR #497, so I'm going to close this issue accordingly -- but don't hesitate to re-open it if I missed or messed-up anything in the merge! 😄
