### ISSUE TITLE
user_passes_test function creates infinite loop with django_cas_ng

### ISSUE THREAD

**Issue by willstott101** [django-helpdesk/django-helpdesk#505]
It seems if `user_passes_test` detects the user doesn't pass the test it sends the user to the login page. However the login page notices they're logged in and sends them right back...

```
login?next=/tickets/submit/
submit/
login?next=/tickets/submit/
submit/
login?next=/tickets/submit/
submit/
login?next=/tickets/submit/
submit/
login?next=/tickets/submit/
submit/
login?next=/tickets/submit/
submit/
login?next=/tickets/submit/
submit/
login?next=/tickets/submit/
```

**Comment by gwasser** [comment]
Infinite loops are never good :-) do you have an example/instructions of how to trigger this bug?

**Comment by willstott101** [comment]
Sorry, that was a very vague issue.

I'm a non-admin user trying to access an admin-only page. Instead of receiving a 403, I get redirected to the login page. However my login page has no way to know that it's being asked for an admin user. It just sees that I'm logged in and sends me right back. And after enough redirects chrome simply says:

**This page isn’t working**

_xxx.xxx redirected you too many times._

**Comment by willstott101** [comment]
I suppose all this app can do is switch to raising PermissionDenied instead of redirecting. In some cases (when the project has no `403.html` specified) this might be uglier than redirecting to login. However in the ideal case (when the project has a good `403.html`) then we can specify a reason `raise PermissionDenied("You must be an admin to access this page.")` which seems far superior to anything that can be achieved with Django's generalised login redirection.

I've noticed that `django_cas_ng` specifies it's [own view decorators](https://github.com/mingchen/django-cas-ng/blob/master/django_cas_ng/decorators.py) for this. I don't think there's any existing shortcut in Django proper (non-CBV style anyway). So I suppose we can just add our own simple equivalent.

If that sounds reasonable I'll be happy to make a PR (and this time hopefully with tests).

**Comment by gwasser** [comment]
Yeah I looked into it a little and wasn't happy with anything I came up with. Your plan sounds good, please feel free to work on it and send a PR when ready. Thanks!
