### ISSUE TITLE
I cannot see new email templates

### ISSUE THREAD

**Issue by andresf01** [django-helpdesk/django-helpdesk#510]
Months ago I finished the translation from English to Spanish(MX) however I cannot find the new email templates with 'es' locale, I could write my owns templates, but I want to know whether there is a way for access to the translation.

Best regards

**Comment by gwasser** [comment]
Hello @andresf01 , thanks again for your Spanish translations!

The email templates get loaded from a JSON-format fixture and I don't believe any `es` translations of the templates were added. I'm not sure if there's a way to automatically generate them from the translations you provided. I'm leaning on @reduxionist or @rossp here. I'm new to internationalization tools :-)

Worst case, if you write your own templates, send them and it's easy to add them to the fixtures, but let's see what they say first.

**Comment by gwasser** [comment]
I will close this ticket since @andresf01 provided translations in the JSON fixture direct via PR #515 . Thanks @andresf01 for providing, and let us know if you have any problems/need to reopen this.
