### ISSUE TITLE
Ticket numbers not converted to links in ticket description

### ISSUE THREAD

**Issue by mrkiwi-nz** [django-helpdesk/django-helpdesk#513]
On line 32 of templates/helpdesk/ticket_desc_table.html there is no "num_to_link" in the chain of template tags.
The result of this is that tickets submitted that reference other tickets don't get a handy link in the description.
eg "Foo crashes when parameter 1 is "bar", note this is not a dupe of ticket #3333"

Is there a reason why this template_tag is omitted?

**Comment by gwasser** [comment]
Thanks for the report! I believe this was an oversight when the templates and styles were overhauled for the 0.2.0 release. There's a few other bug reports on `num_to_link` (#511 and #512) so I'll take a look and see about addressing them all in one swoop.

**Comment by gwasser** [comment]
I think this issue was fixed in PR #532 so I will go ahead and close this, but please file a new ticket if you still spot any problems. Thanks!
