### ISSUE TITLE
get_email Command not have EmailReplyParser in get_email.py line26

### ISSUE THREAD

**Issue by crazyqipython** [django-helpdesk/django-helpdesk#514]
The email_reply_parser.EmailReplyParser is gone.

**Comment by gwasser** [comment]
What version are you using? I have 0.5.9 from https://github.com/zapier/email-reply-parser and it works fine.

**Comment by crazyqipython** [comment]
Thanks.  I lost the email-reply-parse package in my python lib, It's work fine when I install that package.

**Comment by gwasser** [comment]
Ok cool! Let me know if you have any other problems, I'll close it for now.
