### ISSUE TITLE
Is mock a requirement?

### ISSUE THREAD

**Issue by mrkiwi-nz** [django-helpdesk/django-helpdesk#520]
while running 
`python quicketst.py helpdesk`

`/helpdesk/tests/test_attachments.py", line 20`
`import mock`
`ImportError: No module named mock`

I can't see mock in either requirements.txt or requirements-testing.txt

Maybe mock is usually pulled in by another of the packages in requirements-testing.txt, but it didn't work for me.
pip install mock
fixes it for me (also pulls in pbr)

After that, 46 tests run fine.

So the fix is just adding mock to requirements-testing.txt ?

**Comment by gwasser** [comment]
Based on the command you used, I think you're running this on python 2. `mock` is a standard package for python 3, so I think what happened is the requirements-testing.txt reflects python 3 dependencies.

Maybe we can make a separate requirements-testing.txt file for each version of python?

**Comment by gwasser** [comment]
Actually I just tried it and it seems to work fine for python 3 to list `mock`. So I'll just make the change in my next PR. Thanks!

**Comment by gwasser** [comment]
This was added in #522 so I believe it was resolved, but let me know if there's still an issue.
