### ISSUE TITLE
Update setup.py

### ISSUE THREAD

**Issue by mrkiwi-nz** [django-helpdesk/django-helpdesk#521]
Travis is testing django 1.8.18, 1.9.13, 1.10.7, 1.11
In the "classifiers" list, setup.py mentions
        "Framework :: Django",
        "Framework :: Django :: 1.8",
        "Framework :: Django :: 1.9",
        "Framework :: Django :: 1.10",

Should "Framework :: Django :: 1.11" be added here?

**Comment by gwasser** [comment]
Yep, we should include 1.11 too. It's not a super big deal, but I'm planning on a little commit to update the third party stuff so I'll toss this in too.

**Comment by gwasser** [comment]
Was resolved in PR #522.
