### ISSUE TITLE
Images received via get_emails are stored as base64 string

### ISSUE THREAD

**Issue by jonasschnelli** [django-helpdesk/django-helpdesk#523]
I just send some images to the IMAP polled email address and they where successfully stored in the `/attachments` dir.
But, the images where not base64 decoded and the support users can view them.

Is there a quick way to fix this?

**Comment by jonasschnelli** [comment]
I guess the relevant part must be here: https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/management/commands/get_email.py#L335

**Comment by gwasser** [comment]
So a base64-encoded attachment wasn't properly decoded before being attached? Am I understanding correctly?

**Comment by jonasschnelli** [comment]
The file on the disk in the `attachment/` folder has a base64 content (the filename has the correct `.png` ending).
This happens if `get_emails` creates tickets from emails where the attachments IS base64 encoded.
I guess there is a missing decode before writing to the filesystem.

If a support user clicks on the attachment in a ticket that was created via `get_emails` the file won't be displayed because the mime type is PNG but the content base64.

**Comment by gwasser** [comment]
Yeah sounds like we're not doing the base64 checks and decoding. I don't think we have any email tests for base64 attachments either so that's a gap! Thanks, I'll take a look at it.

**Comment by gwasser** [comment]
I merged in #526 so I believe this issue is resolved, but let me know if you still have any more concerns!

**Comment by thefuzzyjew** [comment]
It looks like I'm running into this issue in 0.2.21

A user emailed to the imap account and when viewing the ticket that was generated in the web interface the body of the ticket contained what looked to be base64 encoded data.

**Comment by gwasser** [comment]
@thefuzzyjew could you create a new ticket if so? You can refer to this one in the new ticket, but a new ticket helps track what needs to go in the next update release.

**Comment by thefuzzyjew** [comment]
@gwasser Sure I'll open a new issue. I wasn't sure if you would want to reopen this issue or not but after more digging, it's not quite the same.
