### ISSUE TITLE
Feature Request: Changing the title of the ticket pages

### ISSUE THREAD

**Issue by mrkiwi-nz** [django-helpdesk/django-helpdesk#525]
When i have more than a dozen tabs open (which is almost all the time) all i see on each tab is "View Ticket De..."
The title string is this;
`<title>View Ticket Details :: Powered by django-helpdesk</title>`

Would it be better to be similar to this?
`<title>x18-2484 - Ticket Details</title>`

That way you can see the queue and ticket number (ie ticket.ticket_for_url )

**Comment by gwasser** [comment]
This seems reasonable to me, to put the ticket number first ahead of other information so that's the first thing visible on each tab. (As an aside, I never personally understood having so many tabs at once :-) but I'm happy to support such workflows anyway!)

**Comment by gwasser** [comment]
This fix was merged in as part of #532, so I'll close the ticket but reopen or file a new one if there's still trouble. Thanks!
