### ISSUE TITLE
Heroku demo is not working

### ISSUE THREAD

**Issue by andresf01** [django-helpdesk/django-helpdesk#528]
Hi
I wanted testing a feature in Heroku demo, but I think email settings are not properly.

**Comment by gwasser** [comment]
Hi @andresf01 what feature did you want to test? In my mind the demo is more of a "look and feel" test demo for people that want to just check it out what it looks like, I don't think it can be properly configured for a full installation without other settings. I'm certainly open to ideas on how to improve it though!

**Comment by andresf01** [comment]
@gwasser I wanted test how to works replies from email because I have some problems now with my mail service.

**Comment by gwasser** [comment]
Yeah the demo isn't really meant to do that. However, it is a starting point! Feel free to copy the demo project and configuration into your own folder and add settings for your mail service or other customizations, it should work with minimal setup and changes ideally. If you think the demo is missing any important defaults, let me know or send a PR!
