### ISSUE TITLE
Only updates by email

### ISSUE THREAD

**Issue by andresf01** [django-helpdesk/django-helpdesk#530]
I wanna receive updates by email, however I dont want create new Tickets if I received a mail without associated ticket. It could be performance by an option in settings.

In get_email.py (line 371):

```
...
if ticket is None:
  if settings.QUEUE_EMAIL_BOX_UPDATE_ONLY:
    return None
  new = True
...
```
I did a version in [https://github.com/andresf01/django-helpdesk/commit/d1f35f1299046010094b1ebe33d798cd76e16f5b](url)

**Comment by gwasser** [comment]
This was merged in as part of #529 . I don't see any problem with this since it's not default. I think this code would completely throw away all email without an associated ticket it though, is that OK? Mind if I ask what your use case is, to better understand what you're going for?

**Comment by andresf01** [comment]
Yes, it's ok. Now I use a email address to send mail from different apps, then I need only tracking that mails about tickets opened via web.

**Comment by gwasser** [comment]
I updated the documentation for this issue as part of #532, so I'll close the ticket but reopen or file a new one if there's still trouble. Thanks!
