### ISSUE TITLE
UnicodeDecodeError when send a attachment in reply

### ISSUE THREAD

**Issue by andresf01** [django-helpdesk/django-helpdesk#531]
I got UnicodeDecodeError when send an answer with an attachment (whatever file, with filenames in English) in Ticket details.

> Environment:
> 
> 
> Request Method: POST
> Request URL: http://host:port/tickets/30/update/
> 
> Django Version: 1.11
> Python Version: 3.5.2
> Installed Applications:
> ['django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'django.contrib.sites',
>  'django.contrib.humanize',
>  'markdown_deux',
>  'bootstrapform',
>  'helpdesk']
> Installed Middleware:
> ['django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware']
> 
> 
> 
> Traceback:
> 
> File "/home/user/tickets/py3/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
>   41.             response = get_response(request)
> 
> File "/home/user/tickets/py3/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
>   249.             response = self._get_response(request)
> 
> File "/home/user/tickets/py3/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
>   187.                 response = self.process_exception_by_middleware(e, request)
> 
> File "/home/user/tickets/py3/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
>   185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
> File "/home/user/tickets/py3/lib/python3.5/site-packages/helpdesk/views/staff.py" in update_ticket
>   548.                 files=files,
> 
> File "/home/user/tickets/py3/lib/python3.5/site-packages/helpdesk/lib.py" in send_templated_mail
>   120.             msg.attach(filename, open(filefield.path).read())
> 
> File "/home/user/tickets/py3/lib/python3.5/codecs.py" in decode
>   321.         (result, consumed) = self._buffer_decode(data, self.errors, final)
> 
> Exception Type: UnicodeDecodeError at /tickets/30/update/
> Exception Value: 'utf-8' codec can't decode byte 0xcf in position 9: invalid continuation byte

**Comment by andresf01** [comment]
I think that it could be related with #502 and #466

**Comment by gwasser** [comment]
Yeah there's a couple tickets with attachment issues that are works in progress :-)

Is this a new problem since we merged in #529 ?

**Comment by gwasser** [comment]
I merged in #545 that I think might handle any leftover issues. I'm rebasing version 0.2 to require Django 1.11 to handle email attachment issues that were in Django 1.8 and messing us up. I'm going to close this ticket for now because of the PR changes, but please file a new ticket if you run into problems on helpdesk 0.2. Thanks!
