### ISSUE TITLE
Heroku demo is out of date, and approaching Postgres size limit

### ISSUE THREAD

**Issue by rossp** [django-helpdesk/django-helpdesk#534]
In the project handover I'd forgotten we had an [instance of django-helpdesk hosted on Heroku](https://django-helpdesk-demo.herokuapp.com/). It is likely out of date and needs a refresh. However it is also approaching Heroku's free tier database limit (email copy below).

Would you like me to clean up the data as-is, or reassign the Heroku app to a current django-helpdesk maintainer? I could possibly update the version of django-helpdesk that the demo is using sometime in the next week or two if you like. 

> From: Heroku Notifications <bot@heroku.com>
> To: ross@rossp.org
> Subject: [Warning] Approaching row limit for hobby-dev database on Heroku app django-helpdesk-demo
> Date: Tue, 25 Jul 2017 18:18:38 +0000
> 
> The database HEROKU_POSTGRESQL_CYAN_URL on Heroku app django-helpdesk-demo is approaching its allocated storage capacity.
> 
> The database contains 7,149 rows. The Hobby-dev plan allows a maximum of 10,000 rows. If the databases exceeds 10,000 rows then INSERT privileges will be revoked, preventing more data from being written. INSERT privileges are automatically reinstated if rows are removed and the database once again complies with the plan limit.

**Comment by gwasser** [comment]
Hi @rossp , Either way works for me. If you have time I'd appreciate your help cleaning up the data, but I'm happy to do it too if you want to reassign to me. Thanks!

This is good to keep in mind, hopefully 0.2 will be released soon and we should update the heroku demo at that time.

**Comment by RamezIssac** [comment]
On the same page of house keeping.. on djangopackages.com, django-helpdesk is marked as NOT supporting Python 3.

**Comment by rossp** [comment]
I've taken a brute force approach to cleanup for now; there were tickets with ids in range 599-2284. I've removed everything < 2000:

```
$ heroku pg:psql
django-helpdesk-demo::CYAN=> delete from helpdesk_ticketchange where followup_id in (select id from helpdesk_followup where ticket_id < 2000);
DELETE 39
django-helpdesk-demo::CYAN=> delete from helpdesk_attachment where followup_id in (select id from helpdesk_followup where ticket_id < 2000);
DELETE 127
django-helpdesk-demo::CYAN=> delete from helpdesk_followup where ticket_id < 2000;
DELETE 1882
django-helpdesk-demo::CYAN=> delete from helpdesk_ticketdependency where ticket_id < 2000 or depends_on_id < 2000;
DELETE 48
django-helpdesk-demo::CYAN=> delete from helpdesk_ticketcc where ticket_id < 2000;
DELETE 24
django-helpdesk-demo::CYAN=> delete from helpdesk_ticket where id < 2000;
DELETE 885
django-helpdesk-demo::CYAN=> \q
$ heroku pg | grep Rows
Rows:        4315/10000 (In compliance)
$
```

**Comment by rossp** [comment]
Re a deleted comment from Ramez, it appears the djangopackags Py3 flag is driven by the PyPi listing. Updating that should fix it I believe.

**Comment by rossp** [comment]
@gwasser Can you please PM me the email address you use for Heroku so I can change repo ownership to you? You can then add other collaborators as necessary.

**Comment by gwasser** [comment]
@rossp not sure if can PM here anymore, but you can use my username @ gmail for Heroku.

**Comment by gwasser** [comment]
Thanks! I have Heroku access now and can add it for others as needed.

**Comment by rossp** [comment]
@gwasser Done - you should now have full access to the `django-helpdesk-demo` Heroku app. I'll leave it with you for now re a 0.2 upgrade when that's ready, please let me know if you have any problems or if you need a copy of my deployment script etc? It's about as simple as a Heroku deployment can get, albeit on a 2-year-old stack... happy to spend a bit of time getting it up to date if you need me to.

**Comment by gwasser** [comment]
Thanks @rossp I'll give you a shout if I need anything.

**Comment by rossp** [comment]
@gwasser Howdy!
I've just received a Postgres size-limit-approaching email from Heroku along the lines of [the one I posted above](https://github.com/django-helpdesk/django-helpdesk/issues/534#issue-245961815).

Did you get a copy of it, and are you able to refresh the demo database? Or do you want me to help out with it?

- Ross

**Comment by gwasser** [comment]
Hey there @rossp yes I was just investigating Heroku. I'm a little unclear on how to reduce the number of used rows, was hoping an easy way in the web interface. I appreciate help if you have the time! Thanks!

**Comment by rossp** [comment]
```
django-helpdesk-demo::HEROKU_POSTGRESQL_CYAN=> delete from django_session where expire_date < now();
DELETE 6568
django-helpdesk-demo::HEROKU_POSTGRESQL_CYAN=> \q
$ heroku pg | grep Rows
Rows:                  816/10000 (In compliance)
```

Ideally this would be done regularly with the above query or with `manage.py clearsessions`. We can't add the Scheduler addon without adding a credit card, but that seems like a failsafe way to do it. Worst case we can run clearsessions every year or two when this occurs :)

**Comment by rossp** [comment]
I've setup a cronjob on my home server to run `heroku run --app django-helpdesk-demo python manage.py clearsessions` weekly. Should be safe to consider this a permanent fix.

**Comment by gwasser** [comment]
Thank you very much @rossp! If your home server situation changes let me know and I'll set up something similar. Thanks for the example heroku/sql command.

**Comment by rossp** [comment]
FYI the row limit was hit again due to spam submissions :(  I've just deleted about 4000 records via the helpdesk UI.

**Comment by gwasser** [comment]
Thanks for handling! Any thoughts on dealing with spam?

**Comment by rossp** [comment]
@gwasser To be honest not particularly. We were filtering incoming emails or comments against a spamcheck API but I don't know how good it is. A captcha on submission may assist? I'm not sure how big an issue this is in the install base.

For the demo, a nightly rebuild with some representative demo data might be a better solution if someone has the time and inclination to create tickets / followups / edits etc in a way that shows off the capabilities of helpdesk.

**Comment by rossp** [comment]
I have turned off my home server and this was one of the few casualties of doing so :( Heroku notified me this week that the DB had reached the free limit of 10k rows. 

```
=== HEROKU_POSTGRESQL_CYAN_URL
Plan:                  Hobby-dev
Status:                Available
Connections:           0/20
PG Version:            9.6.20
Created:               2014-07-04 00:33 UTC
Data Size:             22.3 MB
Tables:                51
Rows:                  10914/10000 (Above limits, access disruption imminent)
Fork/Follow:           Unsupported
Rollback:              Unsupported
Continuous Protection: Off
Add-on:                gazing-vastly-6997
```

I followed the pg:psql path above to clear out a huge number of tickets and associated history:

```sql
django-helpdesk-demo::HEROKU_POSTGRESQL_CYAN=> select max(id) from helpdesk_ticket;
  max  
-------
 14666
(1 row)
django-helpdesk-demo::HEROKU_POSTGRESQL_CYAN=> delete from helpdesk_ticketchange where followup_id in (select id from helpdesk_followup where ticket_id < 13000);
DELETE 65
django-helpdesk-demo::HEROKU_POSTGRESQL_CYAN=> delete from helpdesk_followupattachment where followup_id in (select id from helpdesk_followup where ticket_id < 13000);
DELETE 83
django-helpdesk-demo::HEROKU_POSTGRESQL_CYAN=> delete from helpdesk_followup where ticket_id < 13000;
DELETE 5324
django-helpdesk-demo::HEROKU_POSTGRESQL_CYAN=> delete from helpdesk_ticketdependency where ticket_id < 13000 or depends_on_id < 13000;
DELETE 7
django-helpdesk-demo::HEROKU_POSTGRESQL_CYAN=> delete from helpdesk_ticketcc where ticket_id < 13000;
DELETE 2
django-helpdesk-demo::HEROKU_POSTGRESQL_CYAN=> delete from helpdesk_ticket where id < 13000;
DELETE 962
```

End result:

```
% heroku pg --app django-helpdesk-demo                                                                    
=== HEROKU_POSTGRESQL_CYAN_URL
Plan:                  Hobby-dev
Status:                Available
Connections:           0/20
PG Version:            9.6.20
Created:               2014-07-04 00:33 UTC
Data Size:             22.2 MB
Tables:                51
Rows:                  4379/10000 (In compliance)
Fork/Follow:           Unsupported
Rollback:              Unsupported
Continuous Protection: Off
Add-on:                gazing-vastly-6997```

I'm assuming you also get the notifications that the database is approaching the row limit, but I can probably do this again in a year or so when the DB grows too big.

**Comment by gwasser** [comment]
Thank you @rossp for cleaning it up! I did get the notice but hadn't yet reacted, I think they gave 7 days to take action and I was procrastinating a little haha. Thanks for your help!
