### ISSUE TITLE
AttributeError: type object 'User' has no attribute 'objects'

### ISSUE THREAD

**Issue by django-user** [django-helpdesk/django-helpdesk#535]
Im trying to migrate app and getting following error-

File "/opt/myvirtual/proj_virtualenv/lib/python3.5/site-packages/helpdesk/migrations/0002_populate_usersettings.py", line 35, in populate_usersettings
    for u in User.objects.all():
AttributeError: type object 'User' has no attribute 'objects'

because apps.get_model() in that file returning <class '__fake__.User'>

**Comment by gwasser** [comment]
Are you starting a completely new instance, or migrating from an older release of django-helpdesk?

Offhand it sounds like you might not have any users created. Please note that django-helpdesk requires an already working instance of django to get started. More details are in the installation documentation (check the `doc/` folder).

Also I see you're using Python3. Be aware the current release (0.1.18) doesn't officially support py3. You can use the `master` branch as it is beta for upcoming 0.2 release.

**Comment by django-user** [comment]
Now I am using 0.1.18
When will you release 0.2?

**Comment by gwasser** [comment]
I don't think there's a firm date yet but I expect it fairly soon (on the order of a few weeks maybe?). We're expanding our test coverage to try to ensure there's no regressions and iron out Py2->Py3 bugs.

**Comment by gwasser** [comment]
Were you able to migrate successfully to 0.2? I'm going to close this for now as part of prep for 0.3 release but please reopen if you have trouble and I can try to help. Thanks!
