### ISSUE TITLE
How are attachments submitted by users via the web checked for spam?

### ISSUE THREAD

**Issue by ddwaraka** [django-helpdesk/django-helpdesk#537]
Users can submit attachments in two ways:
1. Email
2. Web

When they're using the web interface to attach files, is django-helpdesk checking for viruses or spam or malicious content? If not, is there some way to route this submission through the email? Because through email (We use Gmail for our emails), Gmail will scan the attachments

**Comment by gwasser** [comment]
`django-helpdesk` on its own does not do any type of scanning. For spam, you can optionally enable `akismet` support for detecting spam, check the documentation for more details. I don't personally use it, so if you give it a try and find any problems let us know. That said, I believe `akismet` will only scan the text of comments. To my knowledge it still won't scan the actual attachments.

One option is to have your ticket mail sent to a Gmail account so Google does the spam/virus checking for you, and then setup `django-helpdesk` to use IMAP to pull email from the Gmail account.

**Comment by ddwaraka** [comment]
Oh, yeah, askismet is already enabled. Cool, I'll route web submissions through gmail! Thanks!

**Comment by gwasser** [comment]
Cool! I will close the ticket for tidyness, but please let me know if you run into trouble and I can try to help.

**Comment by ddwaraka** [comment]
Will do, thank you for all the help!
