### ISSUE TITLE
404 in Submit Ticket Button

### ISSUE THREAD

**Issue by andresf01** [django-helpdesk/django-helpdesk#538]
Hello

The problem is that when I clicked "Submit ticket"without login before the link try to access "../accounts/login.." and It is not in urls. The button can hide when I am not logged or redirect to right login.

Regards

**Comment by gwasser** [comment]
Hmm, I don't get this error when using the demo project (0.2.0). Can you provide some more details? Which version are you using? Are you using the ticket submit form on the main page? I notice that the link at the top of the screen sends you to the login page (which is maybe a bug).

**Comment by timthelion** [comment]
You need to have

    LOGIN_URL = '/login/'
    LOGIN_REDIRECT_URL = '/login/'

set just like in the settings in the demo.

**Comment by gwasser** [comment]
Thanks @timthelion, does that fix the problem @andresf01?

**Comment by andresf01** [comment]
Problem is fixed now
