### ISSUE TITLE
`AttributeError` while staff user does a mass update in some tickets using the `Close (Send E-mail)` action

### ISSUE THREAD

**Issue by msaelices** [django-helpdesk/django-helpdesk#539]
`AttributeError: "'Queue' object has no attribute 'get'"`

**Comment by msaelices** [comment]
PR ready for review: https://github.com/django-helpdesk/django-helpdesk/pull/540

**Comment by gwasser** [comment]
Confirmed this issue using the demo project. Selecting multiple tickets then picking Close (Send E-Mail) results in an error. Without email works fine.

**Comment by gwasser** [comment]
Merged in #540. Thanks for the contribution!
