### ISSUE TITLE
`UnicodeEncodeError` when ticket has an special char using python 2

### ISSUE THREAD

**Issue by msaelices** [django-helpdesk/django-helpdesk#541]
If you access to the admin detail page of a ticket with some special char in the title, you will get this error:

    Request Method: GET
    Request URL: http://localhost:8001/admin/helpdesk/ticket/61/

    Django Version: 1.8.6
    Python Version: 2.7.12
    Installed Applications:
    ['django.contrib.admin',
     'django.contrib.auth',
    ...
    Exception Type: UnicodeEncodeError at /admin/helpdesk/ticket/61/
    Exception Value: 'ascii' codec can't encode character u'\xe1' in position 4: ordinal not in range(128)

**Comment by gwasser** [comment]
Thanks! I've been focusing on the switch to python 3 so some python 2 issues slipped thru the cracks.
