### ISSUE TITLE
Allow helpdesk to be invisible to anon users 

### ISSUE THREAD

**Issue by msaelices** [django-helpdesk/django-helpdesk#543]
It's not a bug but a feature proposal.

Some sites use help desk as an internal issue tracker, more than a customer service public site.

It would be great to have a `HELPDESK_ANON_ACCESS_RAISES_404` or similar setting, `False` by default, and if enabled, any anon user which accesses to some `/helpdesk/*` URL will get a 404 error.

If this feature request is accepted I would implement this feature on my fork.

**Comment by gwasser** [comment]
Hi! Thanks for the feature proposal.

Have you tried `HELPDESK_REDIRECT_TO_LOGIN_BY_DEFAULT=True`? This prevents anyone from seeing the public portal. Anonymous users will be redirected to the login page, only logged in users can see tickets. Does that accomplish what you need? Is the documentation lacking?

**Comment by msaelices** [comment]
I do not want to redirect to any login page. I would consider the helpdesk as hidden by non-anon users. Consider it like when you access to some private repo in github as an anonymous user. You will get a 404 error. I propose something similar.

**Comment by gwasser** [comment]
You would still need a login page so you don't lock yourself out right? So you want any request other than directly to the login page to just go to a 404? Would the 404 have a link to the login page? I may not fully understand your use case.

**Comment by gwasser** [comment]
Since it would be an optional feature I don't see any harm in including it if you wanted to work an example. If you could give up a mock up picture of what you're looking for, that would help a lot!

**Comment by gwasser** [comment]
Since this was merged as part of #558 I'll close the ticket.
