### ISSUE TITLE
Viewing Ticket: Error during template rendering

### ISSUE THREAD

**Issue by chrisgilldc** [django-helpdesk/django-helpdesk#549]
Good afternoon, all.
I'm kicking the tires on django-helpdesk as a potential in-house replacement to some hosted helpdesk solutions, and am running into a significant issue - I can't view tickets.
When selecting a ticket, I get the following:

`TemplateSyntaxError at /helpdesk/tickets/1/
Invalid filter: 'num_to_link'
Request Method:	GET
Request URL:	http://192.168.1.201:8000/helpdesk/tickets/1/
Django Version:	1.11.5
Exception Type:	TemplateSyntaxError
Exception Value:	
Invalid filter: 'num_to_link'
Exception Location:	/root/testhd/testhdenv/lib/python3.4/site-packages/django/template/base.py in find_filter, line 606
Python Executable:	/root/testhd/testhdenv/bin/python
Python Version:	3.4.5
Python Path:	
['/root/testhd',
 '/root/testhd/testhdenv/lib64/python34.zip',
 '/root/testhd/testhdenv/lib64/python3.4',
 '/root/testhd/testhdenv/lib64/python3.4/plat-linux',
 '/root/testhd/testhdenv/lib64/python3.4/lib-dynload',
 '/usr/lib64/python3.4',
 '/usr/lib/python3.4',
 '/root/testhd/testhdenv/lib/python3.4/site-packages',
 '/root/testhd/testhdenv/lib/python3.4/site-packages/django_helpdesk-0.2.0-py3.4.egg',
 '/root/testhd/testhdenv/lib/python3.4/site-packages/six-1.10.0-py3.4.egg',
 '/root/testhd/testhdenv/lib/python3.4/site-packages/simplejson-3.11.1-py3.4.egg',
 '/root/testhd/testhdenv/lib/python3.4/site-packages/django_markdown_deux-1.0.5-py3.4.egg',
 '/root/testhd/testhdenv/lib/python3.4/site-packages/email_reply_parser-0.5.9-py3.4.egg',
 '/root/testhd/testhdenv/lib/python3.4/site-packages/django_bootstrap_form-3.3-py3.4.egg',
 '/root/testhd/testhdenv/lib/python3.4/site-packages/markdown2-2.3.4-py3.4.egg',
 '/root/testhd/testhdenv/lib/python3.4/site-packages']
Server time:	Tue, 12 Sep 2017 20:46:38 +0000`

It appears this is related to the num_to_link function, because I get this as well:
`Error during template rendering

In template /root/testhd/testhdenv/lib/python3.4/site-packages/django_helpdesk-0.2.0-py3.4.egg/helpdesk/templates/helpdesk/ticket_desc_table.html, error at line 32`

System is Centos 7.3 with Python 3.4, Djanto 1.11.5 installed via pip and helpdesk straight from the current git repo.
I'm not a django expert, so maybe there's something simple I'm missing. This seems related to some issues opened back in May, #511, #512, #513, although those were all closed out.

**Comment by gwasser** [comment]
Yes, you're correct. This bug snuck in when I was merging several pull requests recently. There was a missing load statement in that template, so it couldn't find the `num_to_link` function. Just pushed an update to `master` to fix this. Let me know if it works for you!

**Comment by chrisgilldc** [comment]
Pulled, installed, appears to work just fine. Thank you!
