### ISSUE TITLE
TemplateSyntaxError at /helpdesk/tickets/2/  Invalid filter: 'num_to_link'

### ISSUE THREAD

**Issue by KeshavZbhide** [django-helpdesk/django-helpdesk#557]
In template /usr/local/lib/python3.5/dist-packages/django_helpdesk-0.2.0-py3.5.egg/helpdesk/templates/helpdesk/ticket_desc_table.html, error at line 32

Getting this error while trying to view the ticket.

**Comment by gwasser** [comment]
That page works in the demo project on my end. Try a few things:

- Update to 0.2.1, which I think might have fixed a bug like this (I made a mistake when pushing out 0.2.0)
- What version of Django are you using? We require Django 1.11.

If that doesn't do it, could you please provide more info? Probably a debug page output. Thanks!

**Comment by KeshavZbhide** [comment]
That resolved the problem but now I am getting:

ConnectionRefusedError at /helpdesk/tickets/1/update/

with/

Environment:


Request Method: POST
Request URL: http://localhost:8000/helpdesk/tickets/1/update/

Django Version: 1.11
Python Version: 3.5.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.humanize',
 'bootstrapform',
 'markdown_deux',
 'helpdesk']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware']



Traceback:

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.5/dist-packages/django_helpdesk-0.2.0-py3.5.egg/helpdesk/views/staff.py" in update_ticket
  550.                 files=files,

File "/usr/local/lib/python3.5/dist-packages/django_helpdesk-0.2.0-py3.5.egg/helpdesk/lib.py" in send_templated_mail
  142.         return msg.send()

File "/usr/local/lib/python3.5/dist-packages/django/core/mail/message.py" in send
  342.         return self.get_connection(fail_silently).send_messages([self])

File "/usr/local/lib/python3.5/dist-packages/django/core/mail/backends/smtp.py" in send_messages
  104.             new_conn_created = self.open()

File "/usr/local/lib/python3.5/dist-packages/django/core/mail/backends/smtp.py" in open
  64.             self.connection = self.connection_class(self.host, self.port, **connection_params)

File "/usr/lib/python3.5/smtplib.py" in __init__
  251.             (code, msg) = self.connect(host, port)

File "/usr/lib/python3.5/smtplib.py" in connect
  335.         self.sock = self._get_socket(host, port, self.timeout)

File "/usr/lib/python3.5/smtplib.py" in _get_socket
  306.                                         self.source_address)

File "/usr/lib/python3.5/socket.py" in create_connection
  711.         raise err

File "/usr/lib/python3.5/socket.py" in create_connection
  702.             sock.connect(sa)

Exception Type: ConnectionRefusedError at /helpdesk/tickets/1/update/
Exception Value: [Errno 111] Connection refused

**Comment by gwasser** [comment]
Looks like an SMTP error. Is your instance properly configured on the network to send mail? Django doesn't provide a mail server itself, you need to connect something else that does it for you (Gmail could work). Make sure you spelled your username and password correct, have the SMTP server URL correct, and that the firewall isn't blocking your requests.

**Comment by KeshavZbhide** [comment]
I added this to my settings.py but still am getting 
`HELPDESK_DEFAULT_SETTINGS` = {
        'use_email_as_submitter': True,
        'email_on_ticket_assign': True,
        'email_on_ticket_change': True,
        'login_view_ticketlist': True,
        'tickets_per_page': 25
        }
`

`
Environment:


Request Method: POST
Request URL: http://localhost:8000/helpdesk/

Django Version: 1.11
Python Version: 3.5.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.humanize',
 'bootstrapform',
 'markdown_deux',
 'helpdesk']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware']



Traceback:

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.5/dist-packages/django_helpdesk-0.2.0-py3.5.egg/helpdesk/views/public.py" in homepage
  46.                 ticket = form.save()

File "/usr/local/lib/python3.5/dist-packages/django_helpdesk-0.2.0-py3.5.egg/helpdesk/forms.py" in save
  391.                             files=files)

File "/usr/local/lib/python3.5/dist-packages/django_helpdesk-0.2.0-py3.5.egg/helpdesk/forms.py" in _send_messages
  250.                 files=files,

File "/usr/local/lib/python3.5/dist-packages/django_helpdesk-0.2.0-py3.5.egg/helpdesk/lib.py" in send_templated_mail
  142.         return msg.send()

File "/usr/local/lib/python3.5/dist-packages/django/core/mail/message.py" in send
  342.         return self.get_connection(fail_silently).send_messages([self])

File "/usr/local/lib/python3.5/dist-packages/django/core/mail/backends/smtp.py" in send_messages
  104.             new_conn_created = self.open()

File "/usr/local/lib/python3.5/dist-packages/django/core/mail/backends/smtp.py" in open
  64.             self.connection = self.connection_class(self.host, self.port, **connection_params)

File "/usr/lib/python3.5/smtplib.py" in __init__
  251.             (code, msg) = self.connect(host, port)

File "/usr/lib/python3.5/smtplib.py" in connect
  335.         self.sock = self._get_socket(host, port, self.timeout)

File "/usr/lib/python3.5/smtplib.py" in _get_socket
  306.                                         self.source_address)

File "/usr/lib/python3.5/socket.py" in create_connection
  711.         raise err

File "/usr/lib/python3.5/socket.py" in create_connection
  702.             sock.connect(sa)

Exception Type: ConnectionRefusedError at /helpdesk/
Exception Value: [Errno 111] Connection refused

`

**Comment by KeshavZbhide** [comment]
By the way the login is not working either. We have custom login but helpdesk is not able to login with that.

**Comment by gwasser** [comment]
For the first error, did you add your SMTP settings to your `settings.py` file? Please see the documentation, item 7: https://github.com/django-helpdesk/django-helpdesk/blob/master/docs/configuration.rst. Did you check that you otherwise have network access to your SMTP server?

For the login, if you are using some custom login stuff, I'm not sure I know how to help. Can you give more details? Do you get any errors when you try to login?

**Comment by KeshavZbhide** [comment]
How will this SMTP settings work with our gmail account?

**Comment by gwasser** [comment]
I haven't recently tested it, but you should be able to drop in the following in your `settings.py` for your gmail account and it will work:
`EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'youremail@gmail.com'
EMAIL_HOST_PASSWORD = 'yourpassword'`

This info for using gmail SMTP services comes from https://support.google.com/a/answer/176600?hl=en, check it for further details if you run into trouble. Here's the Django SMTP settings page too: https://docs.djangoproject.com/en/1.11/topics/email/#smtp-backend.

**Comment by KeshavZbhide** [comment]
I have these settings:

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'keshav.bhide.009@gmail.com'
EMAIL_HOST_PASSWORD = '+09ulbsacs8'


HELPDESK_NAVIGATION_ENABLED = True
HELPDESK_CREATE_TICKET_HIDE_ASSIGNED_TO = False
HELPDESK_ALLOW_NON_STAFF_TICKET_UPDATE = True
HELPDESK_SUBMIT_A_TICKET_PUBLIC = False
HELPDESK_DEFAULT_SETTINGS = {
    'use_email_as_submitter': True,
    'email_on_ticket_assign': True,
    'email_on_ticket_change': True,
    'login_view_ticketlist': False,
    'tickets_per_page': 25
}

After commenting on  a ticket I get 
smtplib.SMTPAuthenticationError: 
Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 s9sm95983pgc.18 - gsmtp')

**Comment by flinz** [comment]
@keshavzbhide If you just posted your plaintext password above you should IMMEDIATELY change it.

**Comment by flinz** [comment]
@keshavzbhide i saw you edited the post, but i still got an email containing the original password. It is compromised. Change it immediately.

**Comment by gwasser** [comment]
Yes @KeshavZbhide please change your password if  you haven't yet.

I take it that new error means some progress! So it means Google isn't letting you log in for some reason. I'm not sure how things like 2FA affect this, you might need to enable IMAP support and create an "App Password" for django-helpdesk to use. Please read the google link in that error message and see what might work for you. I unfortunately can't help much from here on since it depends on your Google account settings, and I haven't used that feature much myself. It's also a Django email thing and not specifically anything from django-helpdesk at this point. Good luck! Hopefully someone else in the community might know a bit more on how to set this up correctly.

**Comment by KeshavZbhide** [comment]
Thanks for letting me know. I changed it.

**Comment by gwasser** [comment]
Hi I hope you were able to set it up! I'm going to close the ticket for housekeeping purposes, but please file a new ticket if you run into any other trouble.
