### ISSUE TITLE
Unable to login with custom login view.

### ISSUE THREAD

**Issue by KeshavZbhide** [django-helpdesk/django-helpdesk#559]
When viewing help desk it shows the user name but when I click on "Tickets" or "Dashboard" it redirects to custom login screen even though the user is logged in. This I assume is a bug.

https://imgur.com/a/4wxzj

This only happens with non admin users.

**Comment by gwasser** [comment]
Sounds like some kind of bug. I believe many of the views do not currently use proper permissions checks, and so in practice there may be difficulties for non-admin staff members. Sort of a hold-over from older versions of Django. Permissions are planned to get overhauled for the next release. I'll keep this open to ensure it gets addressed.

**Comment by Mte90** [comment]
It is still valid after all this years? Without information to replicate it I think that can be closed.

**Comment by gwasser** [comment]
I agree @Mte90 I'll close this one since we can't replicate. Other tickets document the need for better permissions.
