### ISSUE TITLE
Staff view ticket template issues on mobile

### ISSUE THREAD

**Issue by ddwaraka** [django-helpdesk/django-helpdesk#561]
The template for viewing a ticket as staff, `ticket.html` has a follow-up section that does not show properly on mobile. I'm not sure if mobile support is active objective of this project, if not, please ignore this issue. 

If it is, please read on. The follow-ups section of the staff view ticket comes from `ticket.html` goes off screen when viewed on a mobile device (I tried Firefox's iPhone 6 plus preview). Here's a screenshot I've attached to help put things in perspective. I have tested this on Chrome and Firefox and both seem to exhibit the same kind of behavior. 

![capture](https://user-images.githubusercontent.com/12834479/31406120-4d0087ac-adce-11e7-8126-c8555054e654.PNG)

**Comment by gwasser** [comment]
Thanks for the report! The templates have been a little refreshed but are still largely based on some older non-mobile-aware templates and CSS.

So what I would say is that so far we haven't tried to make it particularly mobile friendly, but I do think it's important that it becomes mobile friendly.

I'll mark this as a feature request as something to work on for the next release.

**Comment by gwasser** [comment]
The new bootstrap4 UI should fix this issue, it seems good in testing. It's gone back to a single stream instead of the directional thing that caused problems here. Fix is in `develop` and will be in the next release!
