### ISSUE TITLE
Tickets table: dynamic table sorting overrides query sort order?

### ISSUE THREAD

**Issue by powderflask** [django-helpdesk/django-helpdesk#562]
Forgive me if is obvious, but I searched the other tickets carefully and did not see this reported.
It looks like the new dynamic sorting on the Tickets table (provided by dataTables?) overrides the sort order specified by the Ticket Query.   The Tickets are always sorted by ascending pk, regardless of the sort order filter.  Here's a screenshot -- you can see regardless of whether the sort order is reversed, the table is always sorted by pk.  As far as I can tell, this always happens.
<img width="185" alt="screen shot 2017-10-21 at 2 08 25 pm" src="https://user-images.githubusercontent.com/451398/31855916-cda88596-b669-11e7-8254-e58d0da2e6ee.png"> <img width="121" alt="screen shot 2017-10-21 at 5 23 04 pm" src="https://user-images.githubusercontent.com/451398/31856938-972b92a4-b684-11e7-8756-c3f2e2483d00.png">

I noticed you can see this bug in the screenshots shared last year when this feature was first released: https://github.com/django-helpdesk/django-helpdesk/pull/419#issuecomment-246574490

I'm happy with the dynamic sorting - the new UI is fabulous, thank-you!  But did find this confusing.

**Comment by gwasser** [comment]
Yes the sorting is in DataTables now! I think you found an oversight :-) thanks!

Since you can sort directly in the table by clicking the little arrows, does it make sense to simply remove the Sorting option from the form so it's less confusing?

**Comment by powderflask** [comment]
Depends...  is the JS sorting applied to entire result set or just page of results at the client-side?
What the back-end sort gives you is ability to decide what gets loaded on page 1 of results.
Assuming it's a client-side only sort, be nice if they worked together.  Want me to look into it?

**Comment by gwasser** [comment]
Ah yes, gotcha. Been a while since I worked on it :-) I believe it's client side sort, so I can see how it would still be useful to fix the form option for pages. If you have time and would like to send a PR, I'd greatly appreciate it! Been busy last few weeks but planning to work some more on tickets soon. Thanks!

**Comment by powderflask** [comment]
Sure thing.  I can make a PR, but the mod to fix this is trivial:
Add DataTable option:  `"order": [],`  
See:  https://datatables.net/reference/option/order#Examples

So, in template ticket_list.html:

    $('#ticketTable').DataTable({
            "oLanguage": {
                "sEmptyTable": "{% trans 'No Tickets Match Your Selection' %}"
            },
            "order": [],
            responsive: true
    });

Thanks again for all your efforts on this @gwasser -- so awesome to get this fresh look and new functionality.

**Comment by gwasser** [comment]
Ah I'm glad it was such a simple fix, I hadn't looked into it yet :-) thanks for the patch! Committed to master, to be rolled into next 0.2.x bugfix release.

**Comment by powderflask** [comment]
Cool.  thanks @gwasser
