### ISSUE TITLE
Change Query - Cannot Add Queue Box in Firefox 56.0.1

### ISSUE THREAD

**Issue by ddwaraka** [django-helpdesk/django-helpdesk#563]
![capture](https://user-images.githubusercontent.com/12834479/32121823-2aa19104-bb2c-11e7-96e3-dcfb3efcf820.PNG)

So, in that image, taken on Firefox, when I select "Queue" from the dropdown box and hit the "Plus" icon, 
the page reloads and I don't see a "Queue" box below, as opposed to chrome, where on clicking "Plus", a nice little animation happens and I see a box with all my queue options. 

![capture2](https://user-images.githubusercontent.com/12834479/32121892-787a6040-bb2c-11e7-9b78-9f47d87c2bbe.PNG)

I don't know if this a firefox specific bug or my computer being weird, but can someone please let me know if they're seeing this as well?

**Comment by gwasser** [comment]
I tried it locally with Firefox 56.0.1 and it works as expected (the Queue box does show up). The demo site (http://django-helpdesk-demo.herokuapp.com/tickets/) also works properly in Firefox as far as I can tell.

Are you running any Firefox plugins that might be interfering? I'm also doing this on linux, so maybe there's some error in the windows/mac version if you're using one of those.

**Comment by ddwaraka** [comment]
Oh, that's strange, I'm on a Windows 7 machine, I also have a local version of helpdesk, I tried it on that, no box shows up, I tried it on the heroku site, no box there either and I tried with all my addons disabled and still nothing. It definitely works on Chrome and for now that's enough for me! Thanks!

**Comment by gwasser** [comment]
Very odd. Glad it works for you in Chrome! But makes me wonder what's going on. I'll leave it open and see if I can test on Windows. I know Firefox 56/57 are making some significant changes to the layout engine, there might be some incompatibility between the javascript we're using (like jquery) and latest versions of Firefox.

**Comment by gwasser** [comment]
I tried it with Windows 10 and Firefox 57 and it works. Can you try the demo site in Firefox 57 and see if it works? Do you use any special Firefox extensions/plugins that might be interfering?

**Comment by ddwaraka** [comment]
Yes, it works for me on FF 57.0. I tried it on my Macbook, a personal Windows 10 laptop (also running FF 57.0), but here's the weird part, it did not work on my office laptop, running FF 57.0 as well on Windows 7. Works everywhere else, except that laptop.

I took your advice, disabled all add-ons and started FF in safe mode, still same problem. Windows 7 Firefox maybe the issue. I don't have access to another laptop running Windows 7, but I want to try it there as well. But, I guess for all purposes of this ticket, if no else has reported this issue, you can close it. Thanks!

**Comment by gwasser** [comment]
I tried FF 57 on Windows 7 finally and couldn't recreate the issue. If it is an office laptop, do you know if IT put anything extra on it? Sometimes they require extra firewalls and protections and stuff that could be interfering. I haven't seen any other reports of problems so I'll close the ticket for now but please leave a comment or reopen if you figure out the problem and it's something we can fix. Thanks!
