### ISSUE TITLE
demo site error when creating a ticket

### ISSUE THREAD

**Issue by monkeypants** [django-helpdesk/django-helpdesk#564]
I tried to use the demo site, and it gave me error like:
![dj-helpdesk_error](https://user-images.githubusercontent.com/532596/32142828-1232f964-bcf3-11e7-9c74-09e69e888d1d.png)

**Comment by gwasser** [comment]
Sorry, forgot to run migrations on the heroku instance when I upgraded it to latest `django-helpdesk`. Should work now!

**Comment by monkeypants** [comment]
Yep, works for me (thanks)
