### ISSUE TITLE
I am fetching emails from POP3 server. Expecting strings receiving bytes.

### ISSUE THREAD

**Issue by rjuppa** [django-helpdesk/django-helpdesk#565]
I want to use `get_email` mng.command. Emails are successfully received and processed in `def process_queue()`. 

```
for msg in messagesInfo:
  msgNum = msg.split(" ")[0]
  logger.info("Processing message %s" % msgNum)
  full_message = encoding.force_text("\n".join(server.retr(msgNum)[1]), errors='replace')
  ticket = ticket_from_message(message=full_message, queue=q, logger=logger)
```
`msg` is not a `str`, but `bytes`.  
Is it a bug?
django==1.10   
Python 3.6.0

**Comment by jbmyre** [comment]
I have had the same problem. I ended up editing the  script and using
beautiful soup to parse HTML emails. It's probably not the best solution
but it is very stable. The other benefit is it puts the text in the ticket
body as well, great for the notification emails. I'd be more than happy to
share my code if anyone is interested.

**Comment by gwasser** [comment]
The `get_email` script has gone under heavy revision to work with Python 3 because of the differences in `str` vs `bytes`, so not surprised if there's a bug. @jbmyre if you can send in the code as a comment or a PR, that would help! I've been meaning to explore using beautiful soup more but haven't yet.

**Comment by jbmyre** [comment]
Here is what has been working for me:


`pip install lxml==3.6.0 beautifulsoup4==4.4.1`


Line 28 of get_email.py-

`from bs4 import BeautifulSoup`


Line 359 of get_email.py-

    if not body:    
       mail = BeautifulSoup(part.get_payload(), "lxml")
        if ">" in mail.text:
            message_body = mail.text.split(">")[1]
            body = message_body.encode('ascii', errors='ignore')
        else:
            body = mail.text
        #body = _('No plain-text email body available. Please see attachment "email_html_body.html".')

**Comment by gwasser** [comment]
Thanks @jbmyre ! That seems to be a different issue than what was originally raised by @rjuppa . But I committed some changes to address both issues; the first, we check for Py3 and try to convert it to a `str` first (assuming utf8 compatible text) before further use, and second, I added your suggestion for reading plaintext body out of an HTML-only email. It's committed to `master` and will be rolled into the next bug release (0.2.2). If you can, please check it out to make sure there's no errors before I release it. Thanks!

**Comment by rjuppa** [comment]
Thanks for the confirmation.  
FYI: IMAP works well.

**Comment by gwasser** [comment]
I'm going to close this ticket to clean up the issues list, but please let me know if you run into any more issues.

**Comment by jbmyre** [comment]
I updated my addition- this will prevent style tags or commented html from ending up in the ticket body. 

Line 359 of get_email.py-

if not body:    
    mail = BeautifulSoup(part.get_payload(), "lxml")if ">" in mail.text:
            body = mail.find('body')
            body = body.text
            body = body.encode('ascii', errors='ignore')
        else:
            body = mail.text

**Comment by gwasser** [comment]
Thanks @jbmyre I updated the patch for this, I'll include in the next bugfix release.
