### ISSUE TITLE
translation for zh_CN is ready

### ISSUE THREAD

**Issue by pjsong** [django-helpdesk/django-helpdesk#571]
translation for zh_CN is 100% in progress.

**Comment by gwasser** [comment]
Thank you, great! Is the translation on transifex?

**Comment by gwasser** [comment]
Nevermind, I see that you did update it on transifex.

**Comment by gwasser** [comment]
I committed your translations to `master` so should be rolled into the next release. I'll wait for your template translations before I do it (#572). Thanks very much!
