### ISSUE TITLE
Email templates translation zh_Hans (zh_CN)

### ISSUE THREAD

**Issue by pjsong** [django-helpdesk/django-helpdesk#572]
Email templates needs chinese version too, which branch should be the target pull request?

**Comment by gwasser** [comment]
Thanks for translations! You can do a PR to the `master` branch to update the templates for now. I'll merge it into `develop` and we'll see if anything needs changing from there at the next release.

**Comment by gwasser** [comment]
OK looks like Django since 1.9 has used zh_Hans rather than zh_CN (see https://github.com/django/django/pull/1872). So thank you for including the templates as part of #573!
