### ISSUE TITLE
Demo ist broken

### ISSUE THREAD

**Issue by TobitRE** [django-helpdesk/django-helpdesk#576]
I tried to login with demo demo into the demo an get this error.

http://django-helpdesk-demo.herokuapp.com/view/?ticket=demo&email=demo&csrfmiddlewaretoken=mZyx0NIeJ3onk418nlZA0Q5sR1ln9u5JFvGitexUsE0kZ00pa0ebecKpdSujw0IN

<img width="1422" alt="bildschirmfoto 2017-12-13 um 14 18 41" src="https://user-images.githubusercontent.com/4648804/33940795-b6328d82-e010-11e7-9974-617ebc271b5e.png">

**Comment by gwasser** [comment]
Looks like you entered demo/demo in the "View A Ticket" form on the main page. You enter a ticket ID and your email address there, it is meant for someone without an account to view only the ticket they submitted.

Please click "Log In" at the top of the page, then enter demo/demo, to log in as a staff user.

**Comment by gwasser** [comment]
Actually we should more gracefully handle this error in case someone makes that same mistake. I'll reopen and look at a fix.

**Comment by gwasser** [comment]
I made a quick patch for this to redirect you to the home page instead of giving an error. Not perfect but there's some more permanent fixes coming, so I'll go ahead and close this for now. I'll update the demo soon when version 0.2.4 is released. Thanks for the comment!
