### ISSUE TITLE
Error  in get_email.py 

### ISSUE THREAD

**Issue by hitnik** [django-helpdesk/django-helpdesk#582]
File "/home/odo/djhelpdesk/helpdesk/management/commands/get_email.py", line 179, in process_queue
    full_message = encoding.force_text("\n".join(server.retr(msgNum)[1]), errors='replace')
TypeError: sequence item 0: expected str instance, bytes found

**Comment by gwasser** [comment]
Thanks, which version of Python are you using here? Do you have an example of the email that caused this?

**Comment by hitnik** [comment]
Python 3.5.3, django 2.0, error occurs on all messages.

**Comment by gwasser** [comment]
`django-helpdesk` doesn't officially support Django 2.0 yet, so that could be the reason. Would you mind trying with Django 1.11 and see if you still get the error?

**Comment by hitnik** [comment]
OK, I'll try and let you know about the result.

**Comment by hitnik** [comment]
With django 1.11.9 I have the same problem.

**Comment by solutionfinders** [comment]
In case you are still stuck at this: I ran into the same problem with pop3 and get_email, once I switched to IMAP, everything worked. Perhaps you can also switch to IMAP to get the emails?

**Comment by gwasser** [comment]
Thanks @solutionfinders ! I personally use the local option not POP3 or IMAP so I think those are less tested on py3. The unit tests need an overhaul to properly test POP3, so that's a work in progress!

**Comment by sheadscott** [comment]
I was able to get POP3 working by converting the newline to bytes before doing the join. 
`full_message = encoding.force_text(b"\n".join(server.retr(msgNum)[1]), errors='replace')`
