### ISSUE TITLE
Working with windows

### ISSUE THREAD

**Issue by Mradr** [django-helpdesk/django-helpdesk#584]
Sorry new to stuff like this, but a bit lost on how to make this work on windows? Most of "how-tos" seems to be using make - instead of just running a main.py file instead - didn't know if there way a to force this to run like that or not?

**Comment by gwasser** [comment]
The `make` command is just a simple demo meant to quickly show off features, but it is not required to use `django-helpdesk`. You should be able to create a Django project and install the `django-helpdesk` app to use in your project as normal. That said, I use and develop on linux so let us know if there are any problems running under windows.

**Comment by gwasser** [comment]
I'm going to close this ticket as part of cleanups for the next release, but please re-open if you have any questions!
