### ISSUE TITLE
Add .split(',') to new_ticket_cc().

### ISSUE THREAD

**Issue by electroniceagle** [django-helpdesk/django-helpdesk#585]
The admin doc string indicates you can pass in a comma separated list.  I don't believe that mail_templated allows a string for recipient_list.  It should be a list of strings.  Adding .split(',') should be safe here.

Recipients takes a python list.  
https://github.com/django-helpdesk/django-helpdesk/blob/5112f0dfd07527157157b73a8c20efffd92687fc/helpdesk/management/commands/get_email.py#L507

**Comment by gwasser** [comment]
The conversion of `str` to `list` (if necessary) occurs within the `send_templated_mail` function in `helpdesk.lib` itself, so I believe this situation is covered. Do you think this is insufficient or have a failing test case?

**Comment by gwasser** [comment]
Since the `ticket_cc` part of the code has been significantly updated, I believe this issue has been resolved. I'm going to close the ticket since I didn't get a response and assume everything is ok, but please feel free to re-open or file a new ticket if there's a problem. Thanks.
