### ISSUE TITLE
AttributeError: 'Ticket' object has no attribute 'customer_id'

### ISSUE THREAD

**Issue by abannerjee** [django-helpdesk/django-helpdesk#588]
In our django-helpdesk app, we are allowing non-staff users the ability to update their tickets. However, when attempting to view the ticket (as a non-staff user), the following error is thrown:

`AttributeError: 'Ticket' object has no attribute 'customer_id'`

Looking at the "_is_my_ticket" function in staff.py, if a user is not superuser or staff, then a check is made to verify the user id matches the ticket customer_id. However, the Ticket model does not define "customer_id" as one of its attributes.

Reference: https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/views/staff.py#L92

To get around this, this line has been changed to compare user.email to ticket.submitter_email on our forked repo.

**Comment by gwasser** [comment]
Thanks! That sounds like a reasonable solution, I'll take a look.

**Comment by xiendong** [comment]
Is it possible to compare by user object itself? Not everyone has an email address.

**Comment by gwasser** [comment]
Thanks @xiendong I compare the user IDs as it used to do. For some reason, a typo must have entered in with `customer_id` instead of the correct `assigned_to` value. I added a simple unit test case to try to catch this type of mistake in the future. Let me know if this doesn't fix the issue.
