### ISSUE TITLE
SQL Syntax Error in staff.py

### ISSUE THREAD

**Issue by xiendong** [django-helpdesk/django-helpdesk#600]
Hello, I encountered the following error while trying to load the dashboard page of helpdesk in our app. Any advice on this?

`ProgrammingError at /helpdesk/dashboard/
('42000', u"[42000] [FreeTDS][SQL Server]Incorrect syntax near the keyword 'open'. (156) (SQLExecDirectW)")` 

The error was found at these lines in `staff.py`:
`                    COUNT(CASE t.status WHEN '1' THEN t.id WHEN '2' THEN t.id END) AS open,
                    COUNT(CASE t.status WHEN '3' THEN t.id END) AS resolved,
                    COUNT(CASE t.status WHEN '4' THEN t.id END) AS closed
            %s
            %s
            GROUP BY queue, name
            ORDER BY q.id;
    """ % (from_clause, where_clause)) `

Thanks!

**Comment by gwasser** [comment]
I hadn't heard of FreeTDS before, looks like it's some kind of wrapper to talk to a Microsoft SQL server? My guess is that Microsoft SQL syntax is a little different from what's here. Hard-coded SQL isn't a great idea but it hasn't been upgraded yet. If possible, you might try to use MySQL or another database and see if it works. If you need Microsoft SQL then we'll have to do some more digging on that error message.

**Comment by xiendong** [comment]
Thanks for the reply, I can't change the backend server though, so might have to work on the error message.

**Comment by gwasser** [comment]
Does that SQL statement work on your backend? If not, could you rewrite it so that it works? We might be able to hardcode in a check to use the correct SQL syntax as a temporary workaround. Long run it shouldn't be hardcoded :-)

**Comment by gwasser** [comment]
Hi @xiendong I just merged in #603 to the `master` branch that modernizes that hard-coded SQL query. Let me know if it fixes your issue.

**Comment by gwasser** [comment]
Hi @xiendong I'm going to assume this fixed your issue and close the ticket, but please re-open or file a new one if you still have trouble.
