### ISSUE TITLE
Routing of staff views

### ISSUE THREAD

**Issue by andreyyudin** [django-helpdesk/django-helpdesk#601]
Dear django-helpdesk developers,

Please could you explain how to route django-helpdesk/helpdesk/views/staff.py to a specific database? In particular, the problem is caused by
line 165     """ % (from_clause, where_clause))

**Comment by gwasser** [comment]
Do you have any further details, like the complete error message? That section of the code is some hard-coded SQL to produce statistics. A similar ticket recently pointed out that it does not work on Microsoft SQL (my guess is the query was written with mysql/sqlite in mind, it works fine on those), if that's what you're using. We need to find a way to replace the hard-coded query. If you have an idea please submit a PR! Thanks!

**Comment by gwasser** [comment]
I'm going to close the ticket since it appears to be fixed in PR #603 but re-open or file a new ticket if any problems. Thanks!
