### ISSUE TITLE
Is there a way to show ticket priority to staff only and not users?

### ISSUE THREAD

**Issue by kmacod** [django-helpdesk/django-helpdesk#606]

**Comment by gwasser** [comment]
I don't think so in the current release. This would require better user permissions handling which is on the to-do list. Pull requests welcome!

**Comment by timthelion** [comment]
Do you want this to be a separate option or should it not show the priority when `HELPDESK_PUBLIC_TICKET_PRIORITY` is set?

**Comment by gwasser** [comment]
Is `HELPDESK_PUBLIC_TICKET_PRIORITY` an existing option? I'm not aware of it and don't see it in the `settings.py` module. We could potentially add that setting to implement this.

**Comment by timthelion** [comment]
Yes, it was added in https://github.com/django-helpdesk/django-helpdesk/pull/583

**Comment by gwasser** [comment]
Oh I forgot about that! Should have checked the docs and not the `settings.py` for things that aren't default :-) That option only sets the default priority. I think a separate option might be better, but those settings seem to keep things hidden anyway. There might be a better way to consolidate those options.
