### ISSUE TITLE
unresolved reference urlencode in akismet.py with Python3

### ISSUE THREAD

**Issue by ssboy** [django-helpdesk/django-helpdesk#607]
`from urllib import urlencode `with Python3 seems to be the cause of  an unresolved reference alert.
To have compatibility I would replace the code with the following:
```
try:
    from urllib import urlencode  # python2
except ImportError:
    from urllib.parse import urlencode  # python3

```
Could it be an acceptable solution?
Thanks for your work!
Simon

**Comment by gwasser** [comment]
No it's ok, the `akismet.py` code is BSD licensed so we can definitely modify it. I added your suggestion in the `master` branch. I don't personally use akismet so let me know if it works or not.

**Comment by ssboy** [comment]
Sure ... tanks
