### ISSUE TITLE
Invalid "from" formed when queue email is not specified and default has a specific form.

### ISSUE THREAD

**Issue by adrianboyko** [django-helpdesk/django-helpdesk#608]
Queue's _from_address method will return an invalid value if both of the following are true:
- The queue does not have an email address specified
- DEFAULT_FROM_EMAIL (in settings.py) is of the form `Mr Foo <foo@example.com>`

To be precise, it will return `NO QUEUE EMAIL ADDRESS DEFINED <Mr Foo <foo@example.com>>`

**Comment by gwasser** [comment]
The Queue's email address uses Django's internal `EmailField` to represent it, which I think only takes the email in the format `foo@example.com`. Do we just need better documentation?

**Comment by adrianboyko** [comment]
This problem arises when there is NO queue email address specified and the default from settings.py is used instead.

**Comment by gwasser** [comment]
OK I understand the problem, the double `<` is not valid name. I added in a little check using a regex to check the format. Checked into `master` should be in the next release soon.
