### ISSUE TITLE
Provide mechanism for customizing CSS

### ISSUE THREAD

**Issue by adrianboyko** [django-helpdesk/django-helpdesk#610]
Can helpdesk provide a mechanism for customizing its CSS that doesn't require modification of helpdesk itself? For instance, adding `@import 'helpdesk-customize.css';` at the top of **helpdesk-extend.css** would allow me to add a **[...]/static/helpdesk/helpdesk-customize.css** to my project in which I can add stuff like `ul.timeline li:first-child {display:none}` (inspired by #421).

Or is there already some other way of tweaking the CSS that doesn't require modification of helpdesk?

**Comment by gwasser** [comment]
I think the official Django way of overriding is to add the new CSS file (whether a copy of default helpdesk CSS or an entirely new file) to your top project directly. Django will automatically load it before loading the default helpdesk CSS.

If it helps, I think having the import to make it easier to add styling without copying the old file is fine. I can make that change.

**Comment by gwasser** [comment]
This is fixed as part of #635 so will close this ticket. Thanks!
