### ISSUE TITLE
Documentation Incorrect for 'HELPDESK_ENABLE_PER_QUEUE_PERMISSION'

### ISSUE THREAD

**Issue by askvortsov1** [django-helpdesk/django-helpdesk#611]
The documentation states that this setting is called 'HELPDESK_ENABLE_PER_QUEUE_PERMISSION'; in actuality it is called 'HELPDESK_ENABLE_PER_QUEUE_STAFF_PERMISSION'

**Comment by gwasser** [comment]
Thanks, I only found one instance of this in a note about the old setting's name in `settings.rst`. I did a grep of the whole project and couldn't find it anywhere else so I think it was just a typo I missed. Should be fixed in `master` so closing this ticket. Thanks!
