### ISSUE TITLE
Tickets - Run Query in Use Saved Query not working in Django 2

### ISSUE THREAD

**Issue by ssboy** [django-helpdesk/django-helpdesk#613]
I'm using the master branch project in Pycharm Ide; Django 2.0; Python 3.4; PostgreSQL (but it's the same thing using SQLite). I can save the filter but when try to use it is not applied. No message appears next to the 'apply filter' button. I tried on herokuapp demo installation and the same filter is applied normally ... the success message appears at the side of the 'apply filter' button. I have tried logged as superuser and as staff: same problem. Can anyone try to reproduce the situation on own master project installation? Thanks.
** UPDATE: 
This is an encoding problem that reside in the bytes literal prefix ('b) before the query field in helpdesk_savedsearch table. Django 2 saves the filter with that prefix, Django 1.11 instead no. When the filter is read under Python3 with Django2:
`staff.py -> line 834: query_params = json.loads(b64decode(str(saved_query.query)).decode())`
the returned params are empty. Without the bytes literal prefix all its ok. 
Be careful: the run_report function in staff.py contains the same code at line n. 1141.
I have apply a provisory workaround at lines 834 and 1141:
`query_params = json.loads(b64decode(str(saved_query.query).lstrip("b\\'")).decode())`
I'm sorry but I still do not know helpdesk code well enough to find a consistent solution valid for all the various combinations versions of both Python and Django.

**Comment by gwasser** [comment]
I added a check on the version of Django to use your workaround for Django 2.x and the previous code for Django 1.11 (which I believe works fine in testing). It's a bit nasty but will have to do for a bugfix release. I expect the next major release 0.3 to be solely based on Django 2/ Python 3 to allow more clean up.

**Comment by ssboy** [comment]
Sure! Thanks you for your work.
