### ISSUE TITLE
"Page not found" while opening an attachments in the ticket

### ISSUE THREAD

**Issue by kaluman123** [django-helpdesk/django-helpdesk#614]
Hi,

I am getting an "Page not found" error when I am trying to open an attachment. Do I have forget something, because I cant see the path in the URLS file

![helpdeks-error](https://user-images.githubusercontent.com/4519367/39363607-285415fa-4a2b-11e8-9eb8-7deb7b8ec66c.JPG)

Thanks in advance!

**Comment by somesmart** [comment]
Have you set your media_url and media_root in  your settings.py file?

https://docs.djangoproject.com/en/2.0/howto/static-files/

**Comment by kaluman123** [comment]
I just checked. No, I forget that. Does it have to be a special value or should I use the standard path (MEDIA_ROOT = '/media/')?
