### ISSUE TITLE
Tickets - Delete Saved query: error when you don't Delete It

### ISSUE THREAD

**Issue by ssboy** [django-helpdesk/django-helpdesk#615]
Hi.
When you are in Tickets, applying a saved filter, and next deleting it, you are redirected to a confirmation page. If you press the "No, do not delete it" button, it will generate an error: "The current path, delete_query, does not match any of these".
The problem is in confirm_delete_saved_query.html in line 14 where <a href=../''> I think it's not the correct code.
This is my patch:
`<p><a href=''><button onclick="history.go(-1)" class="btn btn-primary btn-lg">{% trans "No, Don't Delete It" %} </button></a></p>`
Bye

**Comment by gwasser** [comment]
Thanks! Rather than using `onclick` I used a django template to redirect back to the ticket search with the chosen query. I committed to `master`.
