### ISSUE TITLE
Cant seem to get emails of tickets

### ISSUE THREAD

**Issue by tinomhishi** [django-helpdesk/django-helpdesk#619]
I have setup users with different emails, yahoo,gmail. Dont appear to be receiving any emails from the application for followups, etc.

**Comment by gwasser** [comment]
Are you running the `get_email` script as suggested in the install instructions? The queues need to be configured with email information and then the script run to process new mail.

**Comment by tinomhishi** [comment]
Got it. Its working fine now. Thansks @gwasser

**Comment by gwasser** [comment]
Great! I'll close this but please file a new ticket if you run into other problems.
