### ISSUE TITLE
manage.py get_email is not working

### ISSUE THREAD

**Issue by ramdaz** [django-helpdesk/django-helpdesk#620]
File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:645)

This is an error I am receiving. I tried with 3 different email ids across multiple service providers.

Any ideas on what I am missing?

**Comment by Rohitmittal-p** [comment]
I am also getting the same issue.Is there anyone who can help me on this?

**Comment by gwasser** [comment]
Are you using POP or IMAP? With what email service? A google search suggests that the port being used might be wrong. Check your service settings and ensure the correct port is set in your configuration. The default is 993 (IMAP) or 995 (POP) for SSL but that may not be what your service expects.

**Comment by Rohitmittal-p** [comment]
Thanks for the reply and we have figured out the problem last week itself. Its going to be a issue with Imap folder. Everything is working fine for now.

**Comment by gwasser** [comment]
OK great! @ramdaz does that fix your problem too? If you are using IMAP, ensure that you set the correct folder name in the queue settings. The suggested default is `INBOX` but it could be a different name depending on your service provider.
