### ISSUE TITLE
Getting a AttributeError: 'NoneType' object has no attribute 'email' while doing get_email.

### ISSUE THREAD

**Issue by ddwaraka** [django-helpdesk/django-helpdesk#622]
I have a cron job scheduled to do the get_email task to pull from the tickets inbox every 5 mins. That task recently failed to fetch tickets for a particular queue. When I manually ran the command, I got this error:

```
  File "helpdesk/management/commands/get_email.py", line 388, in ticket_from_message
    current_cc_users = [x.user.email for x in current_cc]
AttributeError: 'NoneType' object has no attribute 'email'
```

I printed out some of the values there and:
`current_cc_users = [u'<someone@gmail.com>']`
`current_cc = [<TicketCC: <someone@gmail.com> for Update on Order 12345678>]`

Am I doing something wrong or is this a bug?

**Comment by gwasser** [comment]
This is probably some kind of logic error/bug. It looks like the `TicketCC` class does not necessarily have to have a non-null `user` property, the `_display` function checks for this and simply returns an email if there is no `user`. I'll add in a fix and release something new soon!

**Comment by gwasser** [comment]
Actually are you using the latest `django-helpdesk` release? Based on the line number shown in your error, I don't think you're on the latest release since I see that around line 446 in the current `master` branch.

**Comment by ddwaraka** [comment]
You're right, I am not using the latest release, my last update was easily a couple of releases ago.

**Comment by gwasser** [comment]
OK, please let me know if the update fixes the issue.

**Comment by gwasser** [comment]
I'm closing the ticket as part of the cleanups toward the 0.3 release but please reopen if this still a problem for you. Thanks!

**Comment by tboulogne** [comment]
hello,

I'm using django 0.2.10 and getting :
````
  File "/home/tboulogne/.virtualenvs/apiprint/lib/python3.6/site-packages/helpdesk/management/commands/get_email.py", line 240, in process_queue
    ticket = ticket_from_message(message=full_message, queue=q, logger=logger)
  File "/home/tboulogne/.virtualenvs/apiprint/lib/python3.6/site-packages/helpdesk/management/commands/get_email.py", line 404, in ticket_from_message
    body = body.text
AttributeError: 'NoneType' object has no attribute 'text'
````

Any idea to fin please ?

**Comment by gwasser** [comment]
Do you have an example email that causes this error message?

**Comment by tboulogne** [comment]
Just send an html mail without anything into body, just object. I think you will reproduit this.

If not, i will backward my change and reproduit for you.
