### ISSUE TITLE
This site can’t be reached localhost refused to connect. No Django procress running

### ISSUE THREAD

**Issue by vnahmias** [django-helpdesk/django-helpdesk#623]
hi please take a look at this : 
https://stackoverflow.com/questions/51287486/this-site-can-t-be-reached-localhost-refused-to-connect-no-django-procress-runn?noredirect=1#comment89556229_51287486

if someone can help it would be nice !

**Comment by gwasser** [comment]
Unfortunately I'm not what to suggest. I didn't notice anything in the logs that indicated you're running `django-helpdesk`, is it part of your project?

**Comment by vnahmias** [comment]
I thought Helpdesk meant it was a kind of community support center for Django

**Comment by gwasser** [comment]
Oh I see! No `django-helpdesk` is a Django app for handling tickets for user-reported issues and suggestions.
