### ISSUE TITLE
Problem with date due in "edit" of a ticket

### ISSUE THREAD

**Issue by lbopp42** [django-helpdesk/django-helpdesk#625]
Hello it's me again,
I found an other "bug":
When you create a ticket and you go on "Ticket summary", click on "edit", at the end you got "Date due" and if you select a date with the calendar and save, it doesn't put an hour by default (like when you create a ticket) and say an error (because no hour is define).

Regards,
BOPP Lucas / System Administrator for SIMCO

**Comment by ssboy** [comment]
the version that are you use? 
--> 0.2.9: I tried to reproduce the bug but for me everything works perfectly ... after editing the field I have the following result without error:
Due Date Thu, 2 Aug 2018 00:00:00 +0200 (1 day, 14 hours from now)

**Comment by lbopp42** [comment]
Yes for the 0.2.9 version. When you create the ticket it's ok. But when you edit it, it's not.

**Comment by lbopp42** [comment]
Ok nevermind it's when you select the current day. Not really a bug
