### ISSUE TITLE
Change text - Queue

### ISSUE THREAD

**Issue by eyalabadi98** [django-helpdesk/django-helpdesk#628]
Hello,

I am wondering where In the code is the location to change the word "Queue" to something else, like "Topic". I want to appear on the Add a new Ticket.

I have tried editing it in the language pack and some other places, but I have not had any luck.

Thanks in advance!
Eyal

**Comment by gwasser** [comment]
The word "Queue" is probably hardcoded into the `models.py` file, there is a `Queue` class. There's no way that I'm aware to change it easily from settings instead of modifying the source. Unless you are talking about changing the translation?

**Comment by eyalabadi98** [comment]
Hello,

Yes, I would not mind changing the source, I just don’t know where. I have tried changing many of them but it does not appear to work.

Eyal Abadi

On Aug 20, 2018, at 10:13 AM, Garret Wassermann <notifications@github.com<mailto:notifications@github.com>> wrote:


The word "Queue" is probably hardcoded into the models.py file, there is a Queue class. There's no way that I'm aware to change it easily from settings instead of modifying the source. Unless you are talking about changing the translation?

**Comment by eyalabadi98** [comment]
This did not solve it. I am trying to change the name that shows up on the admin's side of it

**Comment by gwasser** [comment]
Since you're changing the model, you might need to do a `migrate`, I'm not sure. Since you want to tinker with the admin page, I think this is related to #644.

**Comment by gwasser** [comment]
I'm going to close this issue as part of tidying up for the 0.3 release, but let us know if you have any other questions.
