### ISSUE TITLE
It is too easy to guess ticket ids

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#629]
Given that the ticket view requires knowledge of only a user's email and ticket ID, it is far too easy to view other people's tickets by navigating to the `http://example.com/helpdesk/view/?ticket=3&email=email%40example.com` url. I've been trying to investigate ways of solving this issue. It seems that it is too late to use https://github.com/jbrendel/django-randomprimary due to backwards compatibility, though I guess that I could write a migration to deal with that.

**Comment by timthelion** [comment]
A colleague of mine solved a similar problem with https://github.com/aaugustin/django-sesame.

**Comment by gwasser** [comment]
Thanks for the suggestion! `django-sesame` sounds like it could work, at least as an optional feature. Will flag it for the next release.

**Comment by timthelion** [comment]
So I discussed this with my aforementioned college and he disagrees with the use of sesame because sesame would require two things:

 1. Automatic account creation for all ticket submitters
 2. Potentially unwanted ability to log in "insecurely"

Instead, he suggests we take the hash of the ticket ID and the server's SECRET_KEY and include that hash in the URL.

Regardless of whether we use a specially created token or we use sesame, one major problem remains. What about all of the current django-helpdesk-admin users who will have their links broken by such a fix? I imagine that something like a Boolean setting in the Queue model "Require token to display tickets" which would default to True for new Queues but would be set to False by the migration which added the field. That would mean that old links would work, and old Queues would continue to be insecure, but I don't think that can be avoided without complex logic such as allowing access only of tickets are older than the datetime when the migration was performed.

**Comment by timthelion** [comment]
A third option would be to add a field to the ticket model `ticket_auth_code` which would be set in new links. Old links would still work to old tickets which did not have `ticket_auth_code` set.

**Comment by timthelion** [comment]
The last question that I would have, is how should I deal with cases where `HELPDESK_VIEW_A_TICKET_PUBLIC`. I really don't see of a good way of making that secure.

**Comment by gwasser** [comment]
Thanks for the feedback! I like the hash idea.

Keeping things backwards compatible I think is good if at all possible. I mostly envision `django-helpdesk` as a tool for open source projects where tickets being publicly visible isn't really a big threat (possibly you'd want to keep submitter emails private, but other than that, ok if it is easy to find because really we want the tickets to be easy to find!). We'd probably need to keep that as the default behavior and then allow an opt-in secure mode that would do the fancy secure URLs as you describe.

This might be a little more work than able to do at the moment so could get bumped to the 0.4 release as we think about the best path forward a little more.

**Comment by timthelion** [comment]
I am working on an open source project where we need to keep the tickets private ;) In our case, we are an effective transportation non-profit and we run several "campaigns" for which we provide support. One such campaign is a bike to work competition in which everyone gets a T-shirt. These are mailed out, given that the campaign is country wide, and we often field requests regarding their delivery. Obviously, we don't want to make people's shipping addresses public. Similarly, we accept payments, and when people have trouble with payments, there is usually personal info involved. So even though everything we do is under the GPL, we still need the security.

**Comment by timthelion** [comment]
This is fixed in https://github.com/auto-mat/django-helpdesk/commit/c1750a74612b0e2eb2a1eff0ae6dd3cf131ac0a1
