### ISSUE TITLE
RSS feeds should be staff only and not available to any logged in user

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#633]
If I go to `helpdesk/rss/queue/<slug>/` I can see all tickets in the entire system even if I'm a non-staff user.
https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/urls.py#L172

**Comment by gwasser** [comment]
Shouldn't the `login_required` decorator make you login? Right now the permissions system is very weak and doesn't do a good job differentiating staff from other users unfortunately, that's a to-be-updated in the next major release.

**Comment by gwasser** [comment]
Fixed in #636 so closing the ticket. Thanks for the contribution!
