### ISSUE TITLE
Existing users may end up with corrupted user settings when initial migration is applied after adding django-helpdesk

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#643]
````
Request Method: | POST
-- | --
http://example.com/desk/tickets/submit/
2.0.7
Error
Incorrect padding
/home/aplikace/klub_django-devel/env/lib/python3.5/base64.py in decodebytes, line 554
/home/aplikace/klub_django-devel/env/bin/python3
3.5.1
['/home/aplikace/klub_django-devel/env/lib/python2.6/site-packages',  '/home/aplikace/klub_django-devel/env/bin',  '/home/aplikace/klub_django-devel',  '/home/aplikace/klub_django-devel/env/lib/python35.zip',  '/home/aplikace/klub_django-devel/env/lib/python3.5',  '/home/aplikace/klub_django-devel/env/lib/python3.5/plat-linux',  '/home/aplikace/klub_django-devel/env/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5',  '/usr/local/lib/python3.5/plat-linux',  '/home/aplikace/klub_django-devel/env/lib/python3.5/site-packages',  '/home/aplikace/klub_django-devel/env/src/model-mommy',  '/home/aplikace/klub_django-devel/env/src/django-braces',  '/home/aplikace/klub_django-devel/env/src/django-advanced-filters',  '/home/aplikace/klub_django-devel/env/src/django-helpdesk',  '/home/aplikace/klub_django-devel/project',  '/home/aplikace/klub_django-devel/apps',  '/home/aplikace/klub_django-devel/env/lib/python3.5/site-packages/odf',  '/home/aplikace/klub_django-devel/env/lib/python3.5/site-packages/odf',  '/home/aplikace/klub_django-devel/env/lib/python3.5/site-packages/odf',  '/home/aplikace/klub_django-devel/env/lib/python3.5/site-packages/odf',  '/home/aplikace/klub_django-devel/env/lib/python3.5/site-packages/odf',  '/home/aplikace/klub_django-devel/env/lib/python3.5/site-packages/odf',  '/home/aplikace/klub_django-devel/env/lib/python3.5/site-packages/odf']
Tue, 11 Sep 2018 17:23:28 +0200
````

**Comment by timthelion** [comment]
It would seem that this only happens for users that existed in the system before django-helpdesk was added.

**Comment by gwasser** [comment]
Actually I see py2 being called there with py3 above it. I've run into this before. Python 2 and 3 use different data compression formats and so the data stored in the database is incompatible. I'm not sure if there's any way to fix that honestly. You might need to start with a fresh Py3 instance for now.

**Comment by timthelion** [comment]
I looked into this further and there are several things I'd like to point out.

1. The broken fields in the database look like this:

         "b'gAN9cQAoWBAAAAB0...'"

    That's not valid base 64 encoding in any version of python. The `b'` and the end single quote simply shouldn't be there.

2. These settings should not be in a python dictionary at all. They should be normal fields in the model. Doing things this way can only make things more difficult.

3. Even if they are to be encoded as a dictionary, they should not be encoded using pickling, but rather in JSON.

**Comment by timthelion** [comment]
Finally, I'd like to point out, that even if pickling is to be used. Rather than base64 encoding the values BinaryField would be much preferred.

**Comment by timthelion** [comment]
Was the goal of the dictionary hack by any chance to add the ability for 3rd party applications to extend UserSettings with their own settings?

**Comment by gwasser** [comment]
I'm not sure the purpose of `UserSettings` encoding a dictionary. I inherited this project from the original author :-) I imagine it allows more customization and easier access to all of the settings at once within the code. So the `b` means Python is treating it as bytes so it probably isn't properly encoded as anything at all. Was this a totally new python 3 project or did you migrate from 2? If you migrated, I would guess that means Py3 doesn't know how to interpret the data so is just reading it as straight up bytes.

**Comment by timthelion** [comment]
You didn't understand what I wrote. The `b` does NOT mean that python is treating it as bytes. After-all, it is a TextField. Python is treating it as a string. The `b` is actually IN the string. That is the bug.

I believe that the bug is in migration 0002_populate_user_settings. If you look closely at the code in `models.py` and in that migration you will notice that in `models.py` we `.decode()` the pickled settings (in Python3) in order to get a string. In the migration, however, no such distinction between bytes and strings is made.

- https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/migrations/0002_populate_usersettings.py#L17

- https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/models.py#L1133

When the code in the migration then goes to save the pickled dictionary to the database, python automatically casts the bytes to a string using the `str` function which inserts the unwanted `b'` quoting.

That said, I would much prefer to either switch to using JSON or change the model into a normal Django model than fix fiddly b64 encoding bugs ;)

**Comment by gwasser** [comment]
Oh yes I did not understand, thanks for investigating and clarifying! Your hypothesis about the migration bug looks correct to me. I like JSON and think that's a reasonable thing to use here. We could switch it to normal Django models but I suppose keeping it in one field as JSON allows easier customization without having to migrate the underlying model, so I would lean toward keeping the UserSettings field. Either fix b64 or use JSON.

**Comment by timthelion** [comment]
One of the main advantages of using a normal django model is that you have migrations dealt with for you pretty much automatically. The existence of migrations is actually a good thing. It prevents the need for boilerplate code like this:

      settings.get('key', DEFAULT_VALUE)

Every time you want to read a setting. Without migrations, using dictionaries you need that, because you need to be able to handle the case where the setting has never been set, and you need to handle it every single time you access that setting. Futhermore, because dictionaries are untyped, there is a risk that, for example, the number `ticktets_per_page` will be accidentally saved as a string. This can lead to messy and unnecessary situations in the DB.

**Comment by gwasser** [comment]
Thanks, I understand that the django model is good for many reasons but I want to make sure we're not overlooking some other purpose for it.

@rossp do you have any comments on the original purpose of `UserSettings` as a base64 encoded string in the database rather than a collection of django fields? Would you recommending keeping `UserSettings` as such, or converting to using the typical model/fields? Thanks!

**Comment by rossp** [comment]
The reason `UserSettings` is an object rather than Django fields is that it felt like UserSettings was changing on a semi-regular basis at the time, and it didn't make sense to keep updating the model. It might have even been before migrations were easy, to be honest. 

If I were doing it today I might be having a Django model with additional fields (managed by migrations) and/or having a model with simply `User`, `SettingName` and `Value` fields so each separate option gets a separate DB entry.  You might also do it with a JsonField or similar, again I'm not sure if that was an option when this model was originally built.

Given we now have a solid Migrations module there's no reason UserSettings can't just have a field per option - this makes lookups easier, simplifies code, etc.

**Comment by gwasser** [comment]
Thanks @rossp! I appreciate your feedback, I wanted to make sure I wasn't missing something about its usage. Based on your reply, it sounds like we should look at breaking it into model fields.

**Comment by gwasser** [comment]
Thanks to the work by @timthelion in #653 looks like we'll have a new model for the settings in the 0.3 release. I'll close this ticket for now.
