### ISSUE TITLE
Remove Submitter Email field on Admin Page

### ISSUE THREAD

**Issue by eyalabadi98** [django-helpdesk/django-helpdesk#644]
Hello,

I am wondering how I can remove the Submitter Email's field on the admin's side?

![image](https://user-images.githubusercontent.com/3536706/45401036-74b73400-b681-11e8-9ead-7f65d5510bbf.png)

I also wanted to know how I can change the name of Helpdesk to Customer Issues?
![image](https://user-images.githubusercontent.com/3536706/45401073-8c8eb800-b681-11e8-9e84-9a7e27ca3a9f.png)

I tried editing the language files but no changes are reflected anywhere.

**Comment by gwasser** [comment]
You have to edit the `admin.py` file to change the admin pages. I think specifically remove `'hidden_submitter_email'` from the `list_display` variable of `TicketAdmin`, but I haven't tried this yet to confirm. This would only remove it from the admin webpage view, it would still be contained in the database so anyone with database access could still see it, if that's important.

**Comment by eyalabadi98** [comment]
Thanks for the quick response! 
I think what you are referencing to is the table displaying the tickets, but I am talking about when creating a new ticket.

**Comment by eyalabadi98** [comment]
Also, should I change the /helpdesk or /build files? They seem to contain the same files

**Comment by eyalabadi98** [comment]
I am also noticing that the project is not reflecting changes being done. I introduced a print statement on the TIcketAdmin, migrated it, restarted the server but it never gets printed. I tried adding/removing fields to the listview but it doesn't reflect it. Am I missing something here?

Thanks for the continuous help, its just really weird why its not taking effect. I also turned off caching.

The file I am changing is /django-helpdesk/helpdesk/admin.py

**Comment by eyalabadi98** [comment]
Here is the git if you'd like to see it: https://github.com/eyalabadi98/HelpDesk-Other

**Comment by gwasser** [comment]
Is your clone actually installed or are you using the one from `pip` (official release)? I usually do something like `python3 setup.py develop` to ensure that the system python connects to my git clone and doesn't use a distro package or pip version. That might be why you're not seeing changes, it's not running the code in your git repo!

@timthelion brings up a good point though, `django-helpdesk` is designed to add tickets thru the user form and not the admin panel so you could be missing out on important checks if you do it that way. What is your use case that you want to remove the submitter email?

**Comment by eyalabadi98** [comment]
Basically Its a staff-only ticket system. They raise tickets internally for internal problems. and I installed it by cloning the repo through git.

**Comment by gwasser** [comment]
Hmm I think in that case if you disable the public interface, then the only people that can submit tickets are users. It will show the user name instead of the email address. Does that work for your case?

Like I said, run `python setup.py develop` to specially install it in a way that allows instant changes whenever you update the code. Otherwise, you'd have to reinstall the package every time you make a change. Hope that helps!

**Comment by eyalabadi98** [comment]
Yeah, setup.py develop actually did it! 

I'll setup my interface from  the non-admin side now!

Thanks

**Comment by gwasser** [comment]
I'm going to close this but let us know if you have any comments or questions.
