### ISSUE TITLE
Is serverside processing for datatables on ticket_list.html a feasible implementation?

### ISSUE THREAD

**Issue by ddwaraka** [django-helpdesk/django-helpdesk#648]
We have a live implementation django-helpdesk on our site, all is working well. A big thanks to the community!
The number of tickets on our system right now amounts to over 2.3k. This is causing significant page load delays. Our initial approach to fixing this was to only display "Open" and "Re-opened" tickets, but even then, the page load times did slightly improve. 

But, what I propose here is to have the datatables on ticket_list.html page pull data from the server, on request. I have done this before on another project and would be more than willing to submit a pull request to have this implementation released. 

But there is a caveat
The search field is slightly tricky to get it working. We have two options to get it working:
    a. Have a new field on the lines of `search_field` that stores all the fields data as a string and we     have to search that field
    b. The other approach is to query each field in the Ticket model with the search string and display the matching row. This approach will not let the user search the `follow_up` fields. 

This of-course may not be a noticeable load time change in the demo pages, but as and when a live implementation grows, will certainly play a significant part. 

Please let me know what you guys think! Thanks!

**Comment by ddwaraka** [comment]
Sorry about the vagueness, what I meant was to implement server side processing on the [datatables](https://datatables.net/examples/data_sources/server_side).

Yes, like you said, right now we're doing something on the lines of `Ticket.objects.all()`, ofcourse, we do some filtering before we actually get it on the page, but it still puts a lot of tickets on the template and that creates a lot of delay on the page. 

With this approach, we only pull the first 10, 25, 50 or 100 (as set by the user) tickets and every ticket thereafter is fetched on demand only [Clicking on next page is a GET request, searching is a GET request etc etc]. [Here's an example](https://github.com/twtrubiks/DRF-dataTable-Example-server-side) of what I'm talking about.

**Comment by gwasser** [comment]
That sounds like a great feature! I would support a PR if you'd like to work on it. Thanks!

**Comment by ddwaraka** [comment]
Cool, thanks! Will work on during the weekend!

**Comment by gwasser** [comment]
Merged as #650 so closing. Thanks for the PR!
