### ISSUE TITLE
Capacity Limitation up to which number

### ISSUE THREAD

**Issue by sadeghk91** [django-helpdesk/django-helpdesk#656]
Hello,

I appreciate your good job on the ticketing system, Just I have one concern, which is up to how many tickets this app can handle?
suppose I want to raise monthly 200 ticket and total capacity is 200k, can this app support my application requirement?

**Comment by gwasser** [comment]
In principle I believe it can handle as many tickets as you want. It's more accurate to say you're only limited by what backend database you use and how much disk space you have. You should be able to use `django-helpdesk` with any database Django supports. There were some performance issues with lots of tickets reported by others but I think some recent commits have helped with that.

Hope that helps! I'll close the ticket for now but feel free to ask other questions.

**Comment by sadeghk91** [comment]
Thank you gwasser ;)
