### ISSUE TITLE
Move Custom Fields on top of default options in create ticket

### ISSUE THREAD

**Issue by SadeghKrmi** [django-helpdesk/django-helpdesk#669]
How to move custom fields over "Summary of the problem" and below "Queue" ?

![image](https://user-images.githubusercontent.com/5988663/48499165-0f341f00-e84d-11e8-8be1-21b7a4145040.png)

**Comment by gwasser** [comment]
At the moment I think the custom fields are hard-coded to appear at the bottom of the list of fields. You could copy and change the HTML templates to put the custom fields wherever you like, this is a nice feature of Django that your project templates can override the default templates. But at the moment there's no way to do this within the app.

**Comment by timthelion** [comment]
This should be done by over-riding templates.
