### ISSUE TITLE
django-markdown-deux - obsolete 

### ISSUE THREAD

**Issue by lbazan** [django-helpdesk/django-helpdesk#673]
Hi this requirement is obsolete.

https://github.com/trentm/django-markdown-deux

Cheers,

**Comment by gwasser** [comment]
Thanks! Yes it seems unmaintained. Do you have a recommendation on which markdown library we should switch to?

**Comment by lbazan** [comment]
https://github.com/svetlyak40wt/django-markdown2/

I think this can be a solution.

**Comment by gwasser** [comment]
Hmm it doesn't look super active either, at least in terms of the library (last update to actual code was 3 years ago). `django-markdownx` (https://github.com/neutronX/django-markdownx) looks very active and supports the latest Django 2.1, so perhaps that will be a good one? I'll take a look deeper at the options.

**Comment by lbazan** [comment]
good!

**Comment by gwasser** [comment]
I think this was addressed in #728 and so will be in the 0.3 release. Thanks!
