### ISSUE TITLE
Datatables async in devel has improperly configured URL

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#674]
https://github.com/django-helpdesk/django-helpdesk/blob/3dc14bb7285209888768c5181e0f0ed40ac22ae7/helpdesk/templates/helpdesk/ticket_list.html#L21

Needs to be changed to:

    {% url 'datatables_ticket_list' %}

**Comment by gwasser** [comment]
Thanks! Probably leftover from the unfinished UI work as part of #635
