### ISSUE TITLE
Difference between closed and resolved?

### ISSUE THREAD

**Issue by johanovic** [django-helpdesk/django-helpdesk#678]
Sorry if this is really obvious and I feel to understand it, but I'm confused between the closed and resolved states. What is the purpose of each of these states?

thanks

**Comment by johanovic** [comment]
Also see https://github.com/django-helpdesk/django-helpdesk/issues/202

**Comment by gwasser** [comment]
You can adapt the meanings to your use case, but to me generally "resolved" means the ticket was completed with some sort of successful result (like a bug was reported and fixed), whereas a more generic "closed" might be closed for some other reason (like an invalid report).

**Comment by gwasser** [comment]
Being more clear as in #202 is probably a good goal to have, but haven't worked on the UI for that yet.

**Comment by gwasser** [comment]
I'm going to close this one since #202 covers this issue, thanks!
