### ISSUE TITLE
bootstrap4 feedback

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#684]
The new bootstrap work is pretty nice, but there are a few details that still need to be ironed out.

When logged in
----

 - [x] I don't understand why tickets has a one item long submenu

- [ ] There are too many line breaks in the summary part of the dashboard

![bootstrap4](https://user-images.githubusercontent.com/1391608/50486278-92729400-09f9-11e9-90b9-6a22a7c1edc8.png)

When public submission is enabled, and one is logged out
--------

- [x] the side menu doesn't make a lot of sense, because the dashboard, tickets list, and stats pages are all unavailable. It would be nice to have this menu disabled when logged out. The top menu suffices.

![topmenu](https://user-images.githubusercontent.com/1391608/50486477-6d325580-09fa-11e9-994e-14eb18c9ef62.png)

- [x] Finally, there is a small bug in the new code. When logged out and clicking the "Submit a Ticket" link.

![bootstrapnotregistered](https://user-images.githubusercontent.com/1391608/50486555-d74afa80-09fa-11e9-884a-8c79bce47937.png)

**Comment by gwasser** [comment]
Thank you for testing, I was hoping you'd see it and take a look :-) it's nearly done but has some issues like you point out, but I didn't want to hold up testing for bootstrap4 any longer.

For your questions:

> I don't understand why tickets has a one item long submenu

When you save custom query filters, a list of your custom queries appears there too underneath the main ticket link. There should probably be a short message like "No custom queries available. Create one now." with a link to the query page.

> There are too many line breaks in the summary part of the dashboard

Whoa it definitely doesn't like that on my end, interesting. I'm not sure what's causing the line breaks.

> the side menu doesn't make a lot of sense, because the dashboard, tickets list, and stats pages are all unavailable. It would be nice to have this menu disabled when logged out. The top menu suffices.

That sounds reasonable to me. I admit that I have not tested the public interface nearly as much as the logged-in staff interface.

> Finally, there is a small bug in the new code. When logged out and clicking the "Submit a Ticket" link.

Ah missed a change to "bootstrap4form" I guess. Probably already covered in #685 right?

**Comment by gwasser** [comment]
I'm going to close this as I believe all the issues are addressed, please reopen if there's still weird line breaks. Thanks!
