### ISSUE TITLE
PyPi Django helpdesk has a bad migration checked in for version 0.2.11

### ISSUE THREAD

**Issue by kalwalkden** [django-helpdesk/django-helpdesk#688]
django.db.migrations.exceptions.NodeNotFoundError: Migration helpdesk.0024_initial_user_groups_import dependencies reference nonexistent parent node ('helpdesk', '0023_add_enable_notifications_on_email_events_to_ticket')

**Comment by gwasser** [comment]
Thanks! I forgot about that working file I had when I distro'd up that release, figures. Let me issue a correction. Not sure if can reupload 0.2.11 so maybe bump to 0.2.12.

**Comment by gwasser** [comment]
OK issued 0.2.12, thanks for the report!
