### ISSUE TITLE
Demo login not working

### ISSUE THREAD

**Issue by abdiallo** [django-helpdesk/django-helpdesk#690]
Unable to login to demo on heroku using the listed username and password.

**Comment by mariomoraing** [comment]
I have same problem. I can't login with username and password.

**Comment by gwasser** [comment]
Hmm very interesting, will investigate.

**Comment by gwasser** [comment]
Someone must have went to the admin site and changed the password. I reset the password and disabled admin site access so should work now, thanks for reporting and showcasing!

The demo is actually fairly outdated now compared to the `develop` branch, but I'll leave the demo alone for a while yet until version 0.3 is almost ready.

**Comment by wml1993** [comment]
what is username and pwd?

**Comment by gwasser** [comment]
It should say in the banner:
username: demo
password: demo1234
