### ISSUE TITLE
New ticket page for staff takes long time to load for us

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#691]
This is because the select owner dropdown includes all user accounts, and not just staff accounts. Populating this dropdown means putting in thousands of entries for us ;)

**Comment by timthelion** [comment]
It turns out that there is already a setting to fix this: https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/settings.py#L108

**Comment by gwasser** [comment]
Ah perfect! I honestly forgot that was a setting. Our settings will have to get some cleanup once permissions are fixed up.
