### ISSUE TITLE
The dashboard order is weird

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#697]
Currently the order is:
- All Tickets submitted by you
- Open Tickets assigned to you 
- Unassigned Tickets

It would make a lot more sense to me to have this be:

- Unassigned Tickets
- Open Tickets assigned to you
- All Tickets submitted by you

Because that way the dashboard is ordered by the items that current user is most likely to need to act on.

**Comment by gwasser** [comment]
I think the intent was to have items ordered by those that most likely to need to act on, just as you say -- we just differ in what we think is most likely :-) in my mind a user most cares about their own tickets, then tickets assigned to them, then finally the extra unassigned ones. But I agree it can depend on priority, where a quick early response to unassigned tickets is most important.

Probably the answer here is the dashboard should be configurable, letting the administrator or individual users set whatever order they want (and maybe even add queries to the dashboard). Probably not quite ready to do that work but something to consider for future releases!

**Comment by timthelion** [comment]
It turns out that the template for the dashboard is short enough that it probably makes most sense just to over-ride it :)

**Comment by gwasser** [comment]
True! You can do that.
