### ISSUE TITLE
czech translation

### ISSUE THREAD

**Issue by jachym** [django-helpdesk/django-helpdesk#703]
I've added Czech translation on Transifex https://www.transifex.com/django-helpdesk/django-helpdesk

what is the next step? Shell we create pull request for it?

**Comment by timthelion** [comment]
How can I see this translation? Do I need to log in?

**Comment by gwasser** [comment]
@timthelion yes I think you need to login to transifex to see it.

@jachym Thank you very much for the translation! A pull request is best. There are two things to change.

1. add the .po/.mo folders to the locale folder in a new subfolder for czech ('cz')
2. in templates/helpdesk, make a folder 'cz' and add the translated templates there.

**Comment by gwasser** [comment]
You can submit this PR to `master` branch and I will pull it into `develop` from there. Thank you!

**Comment by jachym** [comment]
@gwasser - locale for czech is cs_CZ - there is `cs` used in django-helpdesk right now (and it coresponds to https://github.com/django/django/blob/master/django/conf/global_settings.py#L62 

therefore, I'm going with `cs` not `cz`

**Comment by jachym** [comment]
We still do some cleanups but for the record, before I do the pull request, the code is here https://github.com/OpenGeoLabs/django-helpdesk/tree/cs_translation

**Comment by gwasser** [comment]
Sorry about that! I thought I had read `cz` was the correct two letter code, my mistake. Use whatever is correct :-)

**Comment by timthelion** [comment]
cz is country, cs is language.

**Comment by gwasser** [comment]
The updated translation was merged in #716 so I think it's safe to close this ticket now. Thank you!
