### ISSUE TITLE
Display queues belonging only to each user

### ISSUE THREAD

**Issue by jachym** [django-helpdesk/django-helpdesk#704]
Either I miss something, or current behaviour, if user logs in and want's to submit new ticket, all queues are displayed in the drop-down list.

I thin, it would be more appropriate, if there would be listed only queues, which do have the `Helpdesk | Queue | Permission for Queue NAME` permission set.

I've  implemented it in forked branch https://github.com/OpenGeoLabs/django-helpdesk/tree/user-queue  does it make sense to make pull request?

**Comment by gwasser** [comment]
Yes. Better use of permissions is part of the plan for the 0.3 release, probably the last main thing to do actually before release. I think this would fit well in that plan. Please feel free to open a PR!

**Comment by jachym** [comment]
Pull request created - let me know, what I should workon to make it acceptable https://github.com/django-helpdesk/django-helpdesk/pull/706
