### ISSUE TITLE
Time tracking

### ISSUE THREAD

**Issue by jachym** [django-helpdesk/django-helpdesk#708]
Any idea about how to track time spend on a ticket? Put it later into statistics overview? 

Would it be possible to achieve using custom fields or special implementation is needed?

**Comment by gwasser** [comment]
You might be able to use a custom field to track the time just as text. For a "real" implementation we'd have to add a DateTime widget to the model. A good feature request! Might be fairly easy to add too before our next major release.

**Comment by jachym** [comment]
Implemented, merged, closing.
