### ISSUE TITLE
Resolving a ticket on a private followup makes the resolution public

### ISSUE THREAD

**Issue by JayTurnr** [django-helpdesk/django-helpdesk#710]
Not sure if that has been addressed before, but if I change the status from open to resolved on a private followup, the contents of the message on the private followup gets copied to the ticket "resolution" field and becomes publicly visible.

Maybe a solution is to make "resolution" a foreignkey to the followup?

**Comment by gwasser** [comment]
I think the idea was that the resolution is whatever you tell the original ticket reporter about how it was fixed, so I'm not sure if a private resolution makes a whole lot of sense, at least with the way it is now. Maybe the UI can better indicate this.

**Comment by JayTurnr** [comment]
Ah, makes sense! Wasn't sure if it was intentional or a bug.

**Comment by gwasser** [comment]
Intentional at the moment but certainly open to better ways to make this clear to the user. Thanks!
