### ISSUE TITLE
bootstrap4form at develop branch not available

### ISSUE THREAD

**Issue by jachym** [django-helpdesk/django-helpdesk#713]
/helpdesk/tickets/submit/ address ends-up with error

```
TemplateSyntaxError at /helpdesk/tickets/submit/

'bootstrap4form' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
```

I pip-installed django-bootstrap4-form package - did not help. What is the name of the right package?

**Comment by gwasser** [comment]
This is the correct package: https://pypi.org/project/django-bootstrap4-form/#files

The pip name is `django-bootstrap4-form` but django app is just `bootstrap4form`.

**Comment by jachym** [comment]
Sorry for that - I had to add `bootstrap4form` to `settings.py
