### ISSUE TITLE
adding filter does not work

### ISSUE THREAD

**Issue by jachym** [django-helpdesk/django-helpdesk#714]
Adding filter to list of tickets does not seem to be working

![obrazek](https://user-images.githubusercontent.com/1460823/52222735-81dcf580-28a4-11e9-9db4-9eb4ab7b3179.png)

When I click at the `+` button, nothing happens - nothing appears in the JavaScript development console as well. I can delete one of the two available filters, but not add new one. 

Applies for both - `development` and `master`

**Comment by gwasser** [comment]
Hmm that suggests to me javascript isn't loading at all. Do you use any script or ad blockers that need to be disabled?

**Comment by jachym** [comment]
Well, those JS files were loaded (I'm on localhost)

![obrazek](https://user-images.githubusercontent.com/1460823/52223287-9241a000-28a5-11e9-9610-d975aba0556b.png)

But maybe you are right and I missed (again) to call some `collectstatic` django magic?

**Comment by gwasser** [comment]
Hmm filter.js I think should be the right functions, not sure why it wouldn't be running. What browser are you using? (looks like firefox?).

**Comment by jachym** [comment]
I use Firefox, yes - but I got same problem with chrome

I'll try to have a look into the javascript code

**Comment by jachym** [comment]
Ach, I did not understand the behaviour - the button works only, if the filter type is not already used. Sorry - thank you for your patience. Closing

**Comment by gwasser** [comment]
Good point, ideally the drop down will only include new filter types. That's a future UI enhancement.
