### ISSUE TITLE
django code in comment field does not get escaped

### ISSUE THREAD

**Issue by kotowicz** [django-helpdesk/django-helpdesk#72]
I had a ticket where I had to post some django code. The exact comment was:
_"commented out the {% if new %} check for the forms, since we don't use this button anyway"_

When I try to submit this comment, I get a crash, because 'endif' is not found:
_TemplateSyntaxError: Unclosed tags: else, endif_

**Comment by gwasser** [comment]
I confirmed this issue still exists in 0.2.0, and can potentially even be a security concern. Will take a look at a better way for template processing.
