### ISSUE TITLE
attachments for knowledgebase item

### ISSUE THREAD

**Issue by jachym** [django-helpdesk/django-helpdesk#725]
Should be relatively easy: 

1. Switch `Attachment` class to `abstract` class https://docs.djangoproject.com/en/2.1/ref/models/options/#abstract
2. Create new `FollowUpAttachment` with `FollowUp` as *foreign key*
3. Create new `KBIAttachment` with `KBItem` as *foreign key*
4. Adjust `attachment_path` accordingly - it should be method of the `Attachment` class

Any thoughts?

**Comment by gwasser** [comment]
Good suggestion! I like it.

**Comment by jachym** [comment]
merged in #731
