### ISSUE TITLE
Editing form in public queue

### ISSUE THREAD

**Issue by jachym** [django-helpdesk/django-helpdesk#758]
**Describe the bug**

When ticket submitted to public Queue from unregistered user, the ticket is correctly created, but user can not add any comments in later conversation - if not registered.

**To Reproduce**
Go to http://helpdesk.opengeolabs.cz/view/?ticket=open-source-gis-67&email=jachym.cepicky@gmail.com&key=dc5d12e7-c3a5-42eb-8c89-a0adf507dddd 

you have the unique URL -> you should be able to edit ticket details. Yet, you can not.

**Expected behavior**
Editing form pops up

**Comment by gwasser** [comment]
Fixed with #759 thanks!
