### ISSUE TITLE
Add phone number to the ticket property?

### ISSUE THREAD

**Issue by clack1987** [django-helpdesk/django-helpdesk#763]
**Is your feature request related to a problem? Please describe.**
Yes
**Describe the solution you'd like**
Could add phone number the ticket property?
**Describe alternatives you've considered**

**Additional context**

**Comment by gwasser** [comment]
Hi, can you provide more detail? Are you looking for a phone number of the person that reported the ticket? Where do you want this information displayed?

**Comment by clack1987** [comment]
Thanks. At last, I find this could be done by Django administrator tool.
