### ISSUE TITLE
Error in emailtemplate.json

### ISSUE THREAD

**Issue by sergeyrylov** [django-helpdesk/django-helpdesk#767]
End of string 381
` ... <a href=\"{{ ticket.ticket_urL }}\">{{ ticket.ticket_url }}</a>.</p>`
God string
`... <a href=\"{{ ticket.ticket_url }}\">{{ ticket.ticket_url }}</a>.</p>`

**Comment by gwasser** [comment]
Thanks! Fixed in `master` and will be included in the 0.2.17 bugfix.
