### ISSUE TITLE
users cannot respond ticket

### ISSUE THREAD

**Issue by attapolk** [django-helpdesk/django-helpdesk#773]
Pleas, how to allow Users  respond ticket after opened that ticket. for now my Users just follow-ups own ticket but cannot respond or  change status

**Comment by gwasser** [comment]
Can't respond from the web interface, or the email reply isn't being added to the ticket? Can you provide more information about exactly what is happening?

**Comment by attapolk** [comment]
yep, Can't respond from the web interface. (just staff or admin can update respond message)

**Comment by gwasser** [comment]
Do you have the public interface running? I believe currently only staff users can respond to messages, others have to use the public interface.

**Comment by attapolk** [comment]
yes,  i have public interface and can view a ticket but cannot respond.

**Comment by AhmadiEhsan** [comment]
same problem!

**Comment by timthelion** [comment]
This is fixed by the addition of a secret key for updating the ticket. A magic URL is sent to users and that URL can be used to update the ticket.
