### ISSUE TITLE
SMTPRecipientsRefused when user create ticket and python tried to send email 

### ISSUE THREAD

**Issue by eazaika** [django-helpdesk/django-helpdesk#774]
Test user without special rights can create ticket, but after creating there is no email about ticket for gmail-box.
(from superuser to simple user)
```
2019-09-03 12:40:38,139 ERROR 36256 [helpdesk] lib.py:144 - SMTPException raised while sending email to [u'm***@gmail.com']
Traceback (most recent call last):
  File "/edx/app/edxapp/django-helpdesk/helpdesk/lib.py", line 142, in send_templated_mail
    return msg.send()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/mail/message.py", line 348, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 111, in send_messages
    sent = self._send(message)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 127, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python2.7/smtplib.py", line 747, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {u'm***@gmail.com': (554, '5.7.1 <m***@gmail.com>: Relay access denied')}
```
But when superuser send email to myself, it working fine and I receive this mail. 
In django settings i set SMTP server (which no credentials needed) EMAIL_HOST and QUEUE_EMAIL_BOX_HOST. Also QUEUE_EMAIL_BOX_TYPE = 'SMTP'
Other apps uses this email server good, without problems.
What I'm doing wrong?
django-helpdesk==0.2.16

**Comment by gwasser** [comment]
To make sure I understand you: if you create a ticket with a regular user, you do NOT receive the notification email, but it does work when you create a ticket as superuser/staff?

**Comment by eazaika** [comment]
Oh, no: 
- only superuser receive emails when helpdesk send it (via superuser create ticket - helpdesk sent email fine, superuser becomes the owner of ticket - helpdesk sent email fine, anouther user create ticket - helpdesk fault SMTPRecipientsRefused)

**Comment by eazaika** [comment]
Ok, I complete some tests and there is tiny new fact:
- simple user receive notification email about creating ticket if mailing address of this user in the company domain (someuser@ourcompany.domain)
It's strange because other apps can sending email by this SMTP server on gmail's and others mailing servers without problems.

**Comment by eazaika** [comment]
Sorry, I found the problem and it not depends on helpdesk)

**Comment by azprasla** [comment]
@eazaika do you mind sharing what was the problem? As am having the same issue and don't know why
