### ISSUE TITLE
templates not found

### ISSUE THREAD

**Issue by jfoucry** [django-helpdesk/django-helpdesk#776]
Hello folks,

Not sur it's a bug, may be a bad configuration from me, but I need help.

The crontab process to fetch mail on the server work well and new tickets are created. But the newticket_submitter and new_ticket_cc template are not found.

```
***** Wed Sep 11 19:15:00 2019: Begin processing mail for django-helpdesk
Attempting IMAP server login
Received 1 messages from IMAP server
Processing message b'1'
No tracking ID matched.
[support-4] test4
template "newticket_submitter" does not exist, no mail sent
template "newticket_cc" does not exist, no mail sent
Successfully processed message b'1', deleted from IMAP server
```

In the django admit site, Email_template section they are all present and editable.

I cannot figure where to look for them
```$ django-admin version
1.11.23
```

I run django-helpdesk on a FreeBSD Jail (this should not be a problem).

```
$ pip show django-helpdesk
Name: django-helpdesk
Version: 0.2.16
Summary: Django-powered ticket tracker for your helpdesk
Home-page: https://github.com/django-helpdesk/django-helpdesk
Author: Ross Poulton
Author-email: ross@rossp.org
License: BSD
Location: /usr/home/vagrant/venv/lib/python3.6/site-packages
Requires: setuptools, simplejson, email-reply-parser, lxml, Django, pytz, beautifulsoup4, django-markdown-deux, six, django-bootstrap-form
Required-by: 
```

Thanks for your help

**Comment by gwasser** [comment]
Is this a brand new installation? You'll need to install the fixtures so they are in the database. Check out the install guide Step 9 and see if that fixes your situation. https://github.com/django-helpdesk/django-helpdesk/blob/master/docs/install.rst

**Comment by jfoucry** [comment]
Oh my dear! I forgot to answer to you. I'm so sorry. 

You were right, I forgot the step 9.

FYI, I wrote a blog post (sorry it's in french) about django-helpdesk installation on a FreeBSD jail.

https://adminblog.foucry.net/posts/info/helpdesk-jail/

Please excuse my stupidity…

**Comment by gwasser** [comment]
No worries! I'm glad that it worked for you, thank you for the feedback and writing a blog post about us!
