### ISSUE TITLE
Move from `develop` to `master` branch

### ISSUE THREAD

**Issue by gwasser** [django-helpdesk/django-helpdesk#785]
So here's what I'm thinking -- the need for a `develop` branch is pretty much gone. As I recall I created it to fork off the 0.2.x release from the original 0.1 branch, but clearly 0.2.x is pretty stable now and seems to be what everyone is using.

I am therefore proposing that we merge `develop` into `master` and delete the `develop` branch. All development work for the next release would continue on the `master` branch, which is I think what most people expect. So we'd have the following workflow:

- bugfixes get committed to the the release branch, such as `0.2.x` branch; those bugfixes can then be cherrypicked into `master` if needed.
- development for the next major release will be on `master`. when ready for release candidates, `master` gets branched into a new release branch (such as `0.3.x`) that will take bugfixes, then `master` is ready to accept new PRs and features for the next release (0.4.x, etc.).

Any feedback? I'll probably do this end of November, maybe sooner if positive feedback. I'd like to take a look thru the currently open tickets and PRs on the 0.3.x branch first and work on whatever can be done before the switch to avoid a little rebasing hassle.

**Comment by gwasser** [comment]
As an active contributor lately @timthelion what do you think?

**Comment by timthelion** [comment]
I support the idea. It would mean that more people would test my code ;) and it could encourage more users because the project would look more active.

**Comment by haricot** [comment]
I like your project a lot, I'm missing some time for now but I'm coming soon to test it all. Your workflow proposal is fine for me, although I'm looking at it for now.

**Comment by gwasser** [comment]
Just did this check out #789 for my comment. Accepting patches on `master` for next couple of weeks then we'll branch off a `0.3.x` release!
