### ISSUE TITLE
Django newbie "how to"

### ISSUE THREAD

**Issue by coutoreis** [django-helpdesk/django-helpdesk#786]
I'm a business consultant and haven't tryied Django until I saw this project. The point is that I'm struggling A LOT to make it work in a brand new Python installation.

I wish there was a kind of "step by step" tutorial, like (below is just an EXAMPLE):
pip install django-bootstrap-form
pip install django-helpdesk
pip install docutils
pip install django-markdown-deux
pip install email-reply-parser
django-admin startproject hd
cd hd
cp $1 hd/settings.py
cp $2 hd/urls.py
python manage.py syncdb --noinput
python manage.py migrate helpdesk
echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')" | python manage.py shell
python manage.py collectstatic --noinput

mkdir -p /var/www/static/helpdesk/attachments
chown www-data:www-data /var/www/static/helpdesk/attachments

a2dissite 000-default
a2enconf django-helpdesk
a2enmod wsgi

chown -R www-data:www-data /var/django-helpdesk

**Comment by gwasser** [comment]
Hi there! Glad you're interested in trying out the project! Check out the `docs/` folder for some more information on installation. For example, the install : https://github.com/django-helpdesk/django-helpdesk/blob/master/docs/install.rst, configuration settings options: https://github.com/django-helpdesk/django-helpdesk/blob/master/docs/settings.rst.

I'm not sure how super current those instructions are so if you have any specific questions or comments, we can try to improve the docs. Thanks!

**Comment by coutoreis** [comment]
Thanks for the reply, @gwasser , but I was following exactly those installation instructions.

So, let me explain a bit. 

1. I ran `pip install django-helpdesk`
2. After that what should I do? I don't know what is "a migrate before adding helpdesk to your INSTALLED_APPS", neither "Edit your settings.py file and add helpdesk to the INSTALLED_APPS setting. You also need django.contrib.admin in INSTALLED_APPS if you haven't already added it."
(where is `settings.py`? Where can I find `INSTALLED_APPS`? How should I do a `migrate`?)

P.s.: I'm exagerating a bit about what I did.

**Comment by gwasser** [comment]
`django-helpdesk` definitely assumes you already know a bit about how Django works, so maybe this is something we can improve.

The Django documentation is really good and I recommend going through the tutorial if you haven't yet. In particular, part 1 of the tutorial explains a lot of your questions, see: https://docs.djangoproject.com/en/2.2/intro/tutorial01/#creating-a-project.

Basically, there is a difference between a Django project and a Django app. A project is the your project, the thing you want to set up and develop and use. A project can make use of one of more apps, which are like pre-packaged code and files (like HTML) to quickly add features to your project without reinventing the wheel. `django-helpdesk` is an app, not a project, so we assume that you've already created a project and just need to add `django-helpdesk` as an app to get its features into your project. Like I said, the first tutorial will walk you through creating a very basic barebones project, which you can then use to install `django-helpdesk`.

You can also take a look at the demo project within `django-helpdesk`. The `Makefile` has a list of commands to set up your environment from scratch, so you can follow along with that to get started. The actual code is within the `demo/` folder, actually the project is in the `demo/demodesk/` directory. If you look in there, you will see a `manage.py` file that is what you use to manage and start your project. In the `demo/demodesk/config/` directory, you'll find the `settings.py` and `urls.py` files that are used to configure the apps in your project, including `django-helpdesk`. You can take a look at the demo files for basic ideas on how to get started.

The demo project of course was not designed for "real world" use, is not optimized or secure or anything like that. You will want to start a new project and configure it the way you need based on the Django and django-helpdesk docs, but you can at least take a look at the demo to see what you need to get started. I hope that helps you get started!

**Comment by coutoreis** [comment]
@gwasser I've had health issue in the later days - I'll need to take a break. Thanks for the feedback. I haven't seen yet the docs you suggested, but I'll try my best soon when I get better.

**Comment by gwasser** [comment]
I'm sorry to hear about the health issues @coutoreis, hope you take a nice break and are better soon! Will try to improve things in the meantime so let me know if you have any questions whenever you're ready. Thanks!
