### ISSUE TITLE
We need a plan for getting to the next release

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#789]
We've done a lot of work adding new features and the code in `develop` is pretty far from the stable release. To reduce the divide between those using the old code (which includes broken mail parsing) and the new code it would be best to make a new release. I think it's time to create a new branch "freeze" and perhaps release it on pypi as a `-beta` tagged release. I know that there are still bugs in the new code, but I think it would be better to work on fixing those in a "stablized" feature frozen environment.

**Comment by gwasser** [comment]
I just merged `develop` into `master` and then removed `develop`. Any remaining bugfixes in the 0.2 release should go on the `0.2.x` branch, otherwise let's look at `master` a little more and clean things up before we branch it off for release. Thanks!
