### ISSUE TITLE
KB items should be orderable

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#795]

**Comment by gwasser** [comment]
I agree. The KB is the next big milestone though, gotta try to get the next 0.3.0 release out first :-)

**Comment by gwasser** [comment]
Did this get resolved in #797 ?

**Comment by timthelion** [comment]
Nope, that's still todo

20. ledna 2020 21:34:56 SEČ, Garret Wassermann <notifications@github.com> napsal:

**Comment by timthelion** [comment]
Fixed: https://github.com/django-helpdesk/django-helpdesk/commit/d0aafd61359d82a3351e5a8de55384f8a97d49dd
