### ISSUE TITLE
Not Able to run demo

### ISSUE THREAD

**Issue by nfire007** [django-helpdesk/django-helpdesk#809]
While I'm running make rundemo it's giving me error: 
Makefile:81: recipe for target 'demo' failed
make: *** [demo] Segmentation fault (core dumped)

**Comment by gwasser** [comment]
What version of python and django are you using? If you can try to run it manually and get a more helpful error message that helps a lot.

**Comment by timthelion** [comment]
Closing as stale, there is not enough info and this has probably been fixed upstream.
