### ISSUE TITLE
Template Override issues

### ISSUE THREAD

**Issue by samrose** [django-helpdesk/django-helpdesk#814]
Hi there I am following this exact method in django 2.2

https://docs.djangoproject.com/en/2.2/howto/overriding-templates/#overriding-from-the-project-s-templates-directory

I literally have 

```


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES = [    
    {    
        'BACKEND': 'django.template.backends.django.DjangoTemplates',    
        'DIRS': [os.path.join(BASE_DIR, 'templates')],    
        'APP_DIRS': True,    
        'OPTIONS': {    
            'context_processors': [    
                'django.template.context_processors.debug',    
                'django.template.context_processors.request',    
                'django.contrib.auth.context_processors.auth',    
                'django.contrib.messages.context_processors.messages',    
            ],    
        },    
    },    
]    
```

then in my base dir I have 

```
templates/
└── helpdesk
    ├── base.html
    └── navigation-header.html
```

the `base.html` and `navigation-header.html` are copied directly from for instance https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/templates/helpdesk/base.html

yet these templates do not override the helpdesk application templates

what am I missing here? Thanks!

**Comment by gwasser** [comment]
Is your basedir the directory with settings.py? If so, you want the templates directory to be a sibling directory with your project basedir, something like this:

basedir/
└── settings.py
templates/
└── helpdesk
    ├── base.html
    └── navigation-header.html

**Comment by samrose** [comment]
@gwasser thanks for the response my `BASE_DIR` is one level up from my `PROJECT_DIR` (my `PROJECT_DIR` has the settings.py file)

I have the templates/helpdesk/base.html in the `BASE_DIR`

**Comment by samrose** [comment]
(so it my templates dir appears to be where you are already suggesting)

**Comment by samrose** [comment]
This is the actual list that Django holds on the values in the `TEMPLATES` settings

```python
[{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': ['/code/templates'], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}]```

**Comment by gwasser** [comment]
OK looks like you might need to change the DIRS line in TEMPLATES:
`'DIRS': [os.path.join(PROJECT_ROOT, '..', 'templates'),],`
That's what I'm using in a project that is deployed and working, so maybe try that? Hope it works!

**Comment by samrose** [comment]
Ok this seems to make progress thank you

although I am now seeing the following

```

Request Method: | GET
-- | --
http://0.0.0.0:8008/tickets/
2.2.12
TemplateSyntaxError
'helpdesk_staff' is not a registered tag library. Must be one of: admin_list admin_modify admin_static admin_urls bootstrap cache humanize i18n in_list l10n load_helpdesk_settings log markdown_deux_tags saved_queries static staticfiles ticket_to_link tz user_admin_url
/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py in find_library, line 1023
/usr/local/bin/python
3.8.2
['/code',  '/usr/local/lib/python38.zip',  '/usr/local/lib/python3.8',  '/usr/local/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/site-packages']
Tue, 21 Apr 2020 17:35:58 +0000
```

**Comment by samrose** [comment]
AHA! I was using the wrong templates (from `master` brnach) when i should have been using 

https://raw.githubusercontent.com/django-helpdesk/django-helpdesk/0.2.19/helpdesk/templates/helpdesk/navigation.html

(for instance on 0.2.19 tag)

THANK YOU @gwasser !

**Comment by samrose** [comment]
(I got the template tags error by copying in the wrong git commit release tag version of templates if anyone else runs into this)
