### ISSUE TITLE
    "trying to load '%s': %s" % (entry[1], e) django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'django.contrib.admin.templatetags.admin_static': cannot import na me 'RemovedInDjango30Warning' from 'django.utils.deprecation' (C:\Users\manish.podugu\PycharmProjects\DjangoDashProject\venv\lib\site-packages\django\utils\deprecation.py)

### ISSUE THREAD

**Issue by podugumanish** [django-helpdesk/django-helpdesk#823]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by podugumanish** [comment]
![bug](https://user-images.githubusercontent.com/42859310/81793893-98521200-9527-11ea-954f-3722649ca92b.PNG)

-> This is an issue raised after running 'python manage.py runserver ' within my pycharm project

**Comment by gwasser** [comment]
Are you using Django 3? We don't support that yet.
