### ISSUE TITLE
Provide a Dockerfile to help config a setup plz

### ISSUE THREAD

**Issue by danijeljw** [django-helpdesk/django-helpdesk#826]
**Is your feature request related to a problem? Please describe.**
I am not a django user, but would like to see this spun up inside a Docker container. Can you please adda Dockerfile to the project to use?

**Describe the solution you'd like**
Having a pre-configured Dockerfile to see what the install instructions mean. I didn't understand them.

**Describe alternatives you've considered**
I have tried to follow your steps. I don't undersatnd.

**Additional context**
Having a Dockerfile would give me visibility on how to setup the project.

**Comment by gwasser** [comment]
This is a great idea. I'm not super familiar with Docker so I invite folks to submit a PR with a dockerfile. Might be better to use this eventually than the bash testing script currently in use.

**Comment by danijeljw** [comment]
@gwasser Can you provide me the bash script you use to setup this project? I would be happy to look at how to create a Dockerfile for you as I'm better with that.

I just need to see what steps - even just the basics - put together to setup this project and I will look into it for you.

**Comment by timthelion** [comment]
Have you found this README and associated Makefile? 

https://github.com/django-helpdesk/django-helpdesk/blob/master/demo/README.rst

https://github.com/django-helpdesk/django-helpdesk/blob/master/Makefile

**Comment by pupattan** [comment]
This will be helpful

**Comment by vzankov** [comment]
https://github.com/clwluvw/Django-HelpDesk
