### ISSUE TITLE
Support for django 3.0

### ISSUE THREAD

**Issue by pupattan** [django-helpdesk/django-helpdesk#827]
Could you please support django 3.0 also ?

**Comment by pupattan** [comment]
Any expected date ?

**Comment by gwasser** [comment]
I don't have an expected date unfortunately, my personal schedule has been quite busy. But it is on my todo list. I also welcome pull requests from folks to help push this along!

**Comment by alligatorbait** [comment]
Django 3 is now working with `master` branch and the default version for django is no longer set to a specific version number.

**Comment by gwasser** [comment]
It's working in `master` now and I'm hoping with a little more work we can have a helpdesk 0.3.0 release (or at least a beta release) out soon! I'm going to close this for now for triage purposes to figure out what needs done before release.
