### ISSUE TITLE
pagination on "users closed tickets"

### ISSUE THREAD

**Issue by Bukowskaii** [django-helpdesk/django-helpdesk#829]
**Is your feature request related to a problem? Please describe.**
In our application, we have 600-1000 tickets a month, when one or two users is doing the bulk of these tickets, it makes the dashboard view load absurdly slowly. Ideally, we would have pagination on each section in order to prevent these lists from rolling over to 

![image](https://user-images.githubusercontent.com/4584035/83367802-3d178080-a36b-11ea-8fcd-8bb82a519cd6.png)

**Describe the solution you'd like**
Pagination on the dashboard page for both open unassigned tickets and closed tickets to prevent long load times. We can do better queries elsewhere to search for old tickets if need be.

**Describe alternatives you've considered**
Modifiying the repo myself or switching to a different plugin, this can't be solved with the options available as far as I can tell.

**Additional context**
settings.py contain the following
![image](https://user-images.githubusercontent.com/4584035/83368097-7997ac00-a36c-11ea-9d6b-a7963e630bed.png)

**Comment by gwasser** [comment]
Thanks this is a great idea. I'm happy to take PRs from you or the community to help address this issue.

**Comment by Bukowskaii** [comment]
see PR https://github.com/django-helpdesk/django-helpdesk/pull/830

**Comment by gwasser** [comment]
PR merged so I will close this ticket. Thank you!
