### ISSUE TITLE
Sender email isn't parsed correctly when there is a comma inside From header

### ISSUE THREAD

**Issue by Benbb96** [django-helpdesk/django-helpdesk#832]
**Describe the bug**
When I try to open a ticket by email, sending one to the address I configured in my testing queue, the ticket get created but the `submitter_email` is wrong, and so I don't receive the confirmation email.

**To Reproduce**
1. Change your display name in your email service : add a comma and a special character like an accent, so that it will be encoded in UTF-8. Example : _Bernard-Bouissières, Benjamin_
2. Send a test email to the address defined by your queue
3. Execute the `get_email` command.
For information, by debugging, I can see here that the decoded parts by `email.header.decode_header(string)` are : `[(b'Bernard-Bouissi\xc3\xa8res, Benjamin', 'utf-8'), (b' <benbb96@gmail.com>', None)]`
4. Ticket is created but the `submitter_email` is _Bernard-Bouissières_ whereas it should have been _benbb96@gmail.com_. It only keeps the first part before the comma (because the `email.utils.parseaddr(sender)` considers the comma as a separator like specified in RFC 5322.

**Expected behavior**
The `decode_mail_headers` function should wrap the name in the From header with double quotes in order to avoid considering the comma as a separator. See discussion [in this SO question](https://stackoverflow.com/questions/46775787/python3-email-parsing-a-list-of-email-addresses-with-embedded-commas/46776895)

**Desktop :**
 - OS: Windows 10
 - Browser Chrome
- Python 3.8
 - Version django-helpdesk 0.2.21

**Additional context**
The FROM line in my raw mail header looks like this : 

> From: =?UTF-8?Q?Bernard=2DBouissi=C3=A8res=2C_Benjamin?= <benbb96@gmail.com>

As a workaround, I remove commas inside the `decode_mail_headers` function.

**Comment by gwasser** [comment]
I believe this is fixed in the 0.2.22 release now. Thanks!

**Comment by Benbb96** [comment]
Thanks a lot @gwasser ! I have tested it in my project and it's working correctly 😃
