### ISSUE TITLE
Mailing

### ISSUE THREAD

**Issue by MisterMah** [django-helpdesk/django-helpdesk#834]
I am a little confused about the use of the mail system. Please help me to configure the mail system if I use my own server and / or if I use another server such as smtp.gmail.com (for smtp.gmail.com, I provide the data from the settings.py file and it works, the question is to have if it is the right way to do it in this specific case.)
--------------
Je suis un peu confus quant à l'utilisation du système de mail. Bien vouloir m'y aider afin de configurer le système de mail si j'utilise mon propre serveur et/ou si j'utilise un autre serveur tel que smtp.gmail.com (en ce qui concerne smtp.gmail.com, je renseigne les données depuis le fichiers settings.py et ça marche, la question est de avoir si c'est la bonne manière de faire dans ce cas précis.)

**Comment by gwasser** [comment]
You should be able to use either.

**Comment by MisterMah** [comment]
If I want to use my own server what would be the configuration or procedure

**Comment by gwasser** [comment]
You'll need to configure your Django project for your mail server, see: https://docs.djangoproject.com/en/2.2/topics/email/#email-backends

**Comment by MisterMah** [comment]
Ok thank you
