### ISSUE TITLE
saving attachment binaries to DB

### ISSUE THREAD

**Issue by chris-hellberg** [django-helpdesk/django-helpdesk#842]
Hi,

One of the great things generally about django-helpdesk is that almost all data is saved to a database. So if I'm running an instance of django-helpdesk on AWS, I can kill the instance and/or redeploy a modified instance without worrying about affecting any production data. There is one exception and that is attachments, which are saved to the filesystem. We only keep metadata in the database. The binary blob is saved to disk. This means that I need to take care to back up files before redeploying an instance and generally having two types of backup schemes (DB and filesystem).

Has anyone evaluated saving attachment binaries to the DB as well so all data is concentrated in one place?

Thanks

**Comment by timthelion** [comment]
As far as I know this is already supported. You need to just configure your file storage backend for it. https://pypi.org/project/django-db-file-storage

Note that I wouldn't recomend doing this, it will be slower, more expensive and less scaleable.

12. července 2020 19:11:50 SELČ, hellcheese <notifications@github.com> napsal:

**Comment by koriaf** [comment]
For AWS setup the `django-storages` project configured to save files to S3 may be the best solution; see their documentation for details.
