### ISSUE TITLE
Undocumented setting MAX_EMAIL_ATTACHMENT_SIZE

### ISSUE THREAD

**Issue by alligatorbait** [django-helpdesk/django-helpdesk#846]
There is an undocumented attachment size setting used to determine if the attachment on a ticket will be attached to an email.
lib.py:314:    max_email_attachment_size = getattr(settings, 'MAX_EMAIL_ATTACHMENT_SIZE', 512000)

No reference to this setting was found in the documentation.

Suggest changing name of setting to HELPDESK_MAX_EMAIL_ATTACHMENT_SIZE and including in documentation.

**Comment by gwasser** [comment]
Thanks. I had thought this was due to something from django but couldn't find reference to it anywhere. In that case, I think your suggestion is a good one.

**Comment by gwasser** [comment]
Renamed the setting and added documentation for it. Thanks!
