### ISSUE TITLE
Add email template to response in web interface

### ISSUE THREAD

**Issue by typonaut** [django-helpdesk/django-helpdesk#852]
Perhaps I am missing this, but shouldn't it be a basic feature that when responding to a ticket that you are able to add text from a template? ie, if the user has a question about setting up an account, you have a template that tells them how to do that, or has a link to a KB article?

**Comment by gwasser** [comment]
django-helpdesk does support email templates, but right now you have to edit or create them via the django admin interface. It would be nice to add an editor to the web interface so that you didn't need to be an admin to create/edit them.

**Comment by typonaut** [comment]
Sorry, I haven't been clear enough. I don't mind so much that one must create/edit templates in the Django admin interface, but that when updating a ticket you should be able to choose a template to populate the response field.

**Comment by gwasser** [comment]
Are you using 0.2.x or `master`? I'm pretty sure it used to allow selection of a template, so if that drop down box is no longer available, then it must have been broken in a patch.

**Comment by typonaut** [comment]
Sorry, my error, I was expecting that this would be populated by the material in e-mail templates, but in fact it has another table "pre-set replies", that requires records to be added before the pop-up list appears on the response form.

Probably something to also add to the documentation.
