### ISSUE TITLE
INSTALLED_APPS bootstrapform should change to 'bootstrap4form' 

### ISSUE THREAD

**Issue by wml1993** [django-helpdesk/django-helpdesk#857]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gwasser** [comment]
Can you give details about the problem here? `bootstrap4form` only applies to the development work on `master`, not the 0.2.x release.

**Comment by wml1993** [comment]
yes. and the world is not about development branch? 发自我的华为手机-------- 原始邮件 --------发件人： Garret Wassermann <notifications@github.com>日期： 2020年8月17日周一 下午3:07收件人： django-helpdesk/django-helpdesk <django-helpdesk@noreply.github.com>抄送： wml1993 <13774420748@163.com>, Author <author@noreply.github.com>主    题： Re: [django-helpdesk/django-helpdesk] INSTALLED_APPS bootstrapform should change to 'bootstrap4form'  (#857)
Can you give details about the problem here? bootstrap4form only applies to the development work on master, not the 0.2.x release.

**Comment by gwasser** [comment]
this issue is addressed as part of #878 so will close this issue. thanks!
