### ISSUE TITLE
how to login in the system helpdesk

### ISSUE THREAD

**Issue by wml1993** [django-helpdesk/django-helpdesk#861]
FIrst, on the homepage Queue is -------- and has not another selected. 
And second i could not login in the system, tell me how to login in the system with password.Thanks

**Comment by gwasser** [comment]
You probably need to add a queue in the admin interface if you do not see anything else.

The login is whatever you set it to be for your django project. `django-helpdesk` does not set up your user name or password. Unless you're talking about the demo website? Then the username/password is demo/demo1234.

**Comment by wml1993** [comment]
it is not the demo website, the url is http://127.0.0.1:3000/helpdesk/login/?next=/helpdesk/ on localhost, because i start the website on 3000 port.  The login is whatever you set it to be for your django project how to set it this name or password.

**Comment by wml1993** [comment]
it is not the demo website, the url is http://127.0.0.1:3000/helpdesk/login/?next=/helpdesk/ on localhost, because i start the website on 3000 port.  The login is whatever you set it to be for your django project how to set it this name or password.

**Comment by wml1993** [comment]
it is not the demo website, the url is http://127.0.0.1:3000/helpdesk/login/?next=/helpdesk/ on localhost, because i start the website on 3000 port.  The login is whatever you set it to be for your django project how to set it this name or password.

**Comment by wml1993** [comment]
it is not the demo website, the url is http://127.0.0.1:3000/helpdesk/login/?next=/helpdesk/ on localhost, because i start the website on 3000 port.  The login is whatever you set it to be for your django project how to set it this name or password.

**Comment by gwasser** [comment]
You can check the Django documentation on how to install django and create a new project: https://docs.djangoproject.com/en/2.2/intro/install/. You can also check the `demo/` directory for an example small project.

**Comment by wml1993** [comment]
THANKS A LOT发自我的华为手机-------- 原始邮件 --------发件人： Garret Wassermann <notifications@github.com>日期： 2020年8月20日周四 下午1:38收件人： django-helpdesk/django-helpdesk <django-helpdesk@noreply.github.com>抄送： wml1993 <13774420748@163.com>, Author <author@noreply.github.com>主    题： Re: [django-helpdesk/django-helpdesk] how to login in the system helpdesk (#861)
You can check the Django documentation on how to install django and create a new project: https://docs.djangoproject.com/en/2.2/intro/install/. You can also check the demo/ directory for an example small project.
