### ISSUE TITLE
Way to integrate with sites base template

### ISSUE THREAD

**Issue by LenCole** [django-helpdesk/django-helpdesk#864]
Would like a way (or if there is I can't find it) to integrate with site so that the sites base.html template is used (to provide sites - header, footer, etc.)

**Comment by alligatorbait** [comment]
> Would like a way (or if there is I can't find it) to integrate with site so that the sites base.html template is used (to provide sites - header, footer, etc.)

I second this one. Would be very nice to have a way to create a directory in Django with templates that wrap the django-helpdesk templates. This is something I have done with djangorestframework.

**Comment by gwasser** [comment]
Thank you for the suggestion. The templates currently in use are pretty old and definitely need some refactoring for the next major release.

**Comment by alligatorbait** [comment]
I looked over the templates and have an easy way to add an override for a navigation header above the django-helpdesk navigation. I will put in a pull request on master soon.

**Comment by timthelion** [comment]
This is fixed right?
