### ISSUE TITLE
Public Tickets are not created 

### ISSUE THREAD

**Issue by m1thrandir225** [django-helpdesk/django-helpdesk#871]
**Describe the bug**
So I had 2 public queues everything was working fine until I added, a non public queue. I add all the information it sends a POST request but it doesn't create the ticket. This problem doesn't occur when I make the tickets while logged in. I have absolutely no idea how this came to be any tips to fix? 

**Expected behavior**
The thing I wanted to create was 2 public queues where all people can submit tickets, and one private(internal) queue for employees to submit.

**Comment by timthelion** [comment]
Which version is this?

**Comment by m1thrandir225** [comment]
> Which version is this?

0.2.22

I literally reinstalled my whole project, I thought I had messed something up but still the same problem continues, a new fresh install, 2 public queues and one that needs to be signed in. When I submit a ticket to the public queue it goes to localhost/helpdesk/#submit and nothing happens, it sends a POST request but doesn't actually do anything.

**Comment by Mte90** [comment]
Can you share the post request/code are you doing/using?
So we can replicate it and investigating, maybe after all those years the issue is fixed...

**Comment by m1thrandir225** [comment]
> 

Sorry I don't think I have the code
