### ISSUE TITLE
How to integrate this ticket system with existing project?

### ISSUE THREAD

**Issue by bavamca** [django-helpdesk/django-helpdesk#872]
Hi,
I want to execute the ticket system on my existing project, is there any documentation or guidance are there?

**Comment by bavamca** [comment]
I need the integration of the ticket creation interface with my existing project

**Comment by bavamca** [comment]
When I use this package on Django 3.1 it throws an error and not running  and also it degrades the Django from 3.1 to 2.1

**Comment by gwasser** [comment]
django-helpdesk does not currently support Django 3

**Comment by bavamca** [comment]
Thanks @gwasser

**Comment by timthelion** [comment]
There is now good iframe support https://django-helpdesk.readthedocs.io/en/0.5.0/integration.html
