### ISSUE TITLE
Inside your MEDIA_ROOT folder, inside the helpdesk folder, is a folder called attachments. Ensure your web server software can write to this folder - something like this should do the trick:  chown www-data:www-data attachments/ chmod 700 attachments  i can't understand this line in official documentation (iam a noob) there is no folder like attachments in helpdesk package

### ISSUE THREAD

**Issue by KarthikeyanTealorca** [django-helpdesk/django-helpdesk#873]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alligatorbait** [comment]
The attachments folder is created when you attempt to attach a file to a ticket. Test the feature first to see if it is working, if it is not working then you may need to investigate the Web Server installation settings to determine if there are restrictions of directory access. The django-helpdesk creates the folder with the o700 rights of the user running Django. If the Web Server is run by a different user than Django it will not be granted access to the folder. In common scenarios this will not be an issues as the Web Server and Django are run by a processes owned by root.

**Comment by KarthikeyanTealorca** [comment]
Ohh Thank you, and one more question i have setup the package on my project, can i extend the models in helpdesk and create new models ??

**Comment by alligatorbait** [comment]
There are instructions to add custom fields: https://django-helpdesk.readthedocs.io/en/0.2.x/custom_fields.html
As far as adding additional tables, that may required greater modification.

**Comment by KarthikeyanTealorca** [comment]
okay thanks a lot!!! for ur support
