### ISSUE TITLE
Instructions (Documentation) on using non-default database

### ISSUE THREAD

**Issue by alligatorbait** [django-helpdesk/django-helpdesk#877]
**Is your feature request related to a problem? Please describe.**
I have a default database as the sqlite type and would like to use a PostgreSQL database specifically setup for django-helpdesk. I did not find instructions to accomplish this goal and was unsuccessful trying to solve on my own.

**Describe the solution you'd like**
Add instructions into the docs on how to setup a non-default database and routers to properly configure django-helpdesk for this scenario.

**Additional context**
I attempted to setup a router that would route any helpdesk traffic to my non-default database with label helpdesk (PostgreSQL database) and the closest I got was while trying to migrate received the following errors. My setup did not properly create tables, and so some instructions would be valuable to me and others.
```
python manage.py migrate helpdesk 
Operations to perform:
Apply all migrations: helpdesk
Running migrations:
Applying helpdesk.0003_initial_data_import...Traceback (most recent call last):
File "virtualenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "helpdesk_emailtemplate" does not exist
LINE 1: UPDATE "helpdesk_emailtemplate" SET "template_name" = 'assig...
^
```

**Comment by gwasser** [comment]
Hmm I had thought django itself would handle most of the database stuff transparently for us. PostgreSQL is common enough we should have specific documentation for it if that's necessary.

**Comment by timthelion** [comment]
Yeah, this deffinitely isn't an issue with helpdesk. What you are trying to do is extremely non standard. What problem are you trying to solve?

**Comment by alligatorbait** [comment]
@timthelion I thought I described the problem I was trying to solve clearly in my post? Additional context: Using a default database that is sqlite (which contains data that can be thrown away and recreated without issue) I would like to route the helpdesk app to use a PostgreSQL database in a completely separate environment/location that is backed up and not considered temporary.

**Comment by timthelion** [comment]
Django uses separate tables to track migrations, content types and other important metadata. Unless you are re-routing these tables as well your approach won't work.

**Comment by alligatorbait** [comment]
I see that I would need to route all the django_xxxx tables to another location. In my situation the user_xxxx tables are disposable. Thanks for that catch. I am able to route those tables, I'm wondering why my router for helpdesk wasn't working properly. It is not the standard use case, but that's the best part of django, the ability to customize to your needs. Sounds like you may know how to do this?

**Comment by alligatorbait** [comment]
I did more research and had a couple of problems, none of which are helpdesk and all were Django. The main problem, even when I had all the routers setup properly, was that Django requires a migrate command to be run for each database with the database specified on the command line, the Django documentation does not tell you this in the section that explains Multiple Databases.

**Comment by alligatorbait** [comment]
And for posterity, I made a suggestion to the Dango Project to improve the documentation: https://code.djangoproject.com/ticket/32083#ticket
