### ISSUE TITLE
After the master branch runs the service, it opens the page and displays an exception

### ISSUE THREAD

**Issue by yan0727** [django-helpdesk/django-helpdesk#897]
**Describe the bug**
Page display exception

**To Reproduce**

**Expected behavior**
After the master branch runs the service, it opens the page and displays an exception

**Screenshots**
![image](https://user-images.githubusercontent.com/54628126/98207333-7be2df80-1f76-11eb-9646-7c3098d81369.png)
![image](https://user-images.githubusercontent.com/54628126/98207393-94eb9080-1f76-11eb-85da-d4dfe35f6512.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 86.0.4240.111

**Smartphone (please complete the following information):**
 - Device: windows
 - OS: windows
 - Browser chrone
 - Version 86.0.4240.111

**Additional context**

**Comment by Benbb96** [comment]
What is the exception message ?

And did you pull the last changes of the master branch, It could be a bug I introduced in my last PR...

**Comment by yan0727** [comment]
@Benbb96 Yes, I pulled the latest master branch to run, and the error message was a page exception. Please have a look at the screenshot above

**Comment by Benbb96** [comment]
By exception, you mean that the page is not well displayed ?

Do you see an error in the browser console ?

**Comment by gwasser** [comment]
I merged the potential fix but if that didn't fix it please feel free to leave a comment or open a new ticket. Thanks!
