### ISSUE TITLE
Slow TestGetEmail using socks

### ISSUE THREAD

**Issue by koriaf** [django-helpdesk/django-helpdesk#902]
When I run tests (just as `python qucktest.py helpdesk`) they take 40 minutes; IF i set variable `case_socks` to just `[False]` in the test_get_email.py file it works fine.

**To Reproduce**
1. run virtualenv or install test and base requirements in other way
2. run `python quicktest.py`
3. observe it's slow
4. open helpdesk/tests/test_get_email.py and set `case_socks` variable to `[False]`
5. re-run the tests and observe it's working fast now

**Expected behavior**
It works fine from the box

May be it lacks the documentation how to configure these socks things, but I feel that it's just misconfigured from the box and tries to connect to some non-existent service (which is incorrect because these tests are unit, not integration, and generally shouldn't be connecting anywhere).

**Comment by gwasser** [comment]
The tests used to run very quickly and I wondered what made them so slow. I suppose something was changed along the way. Thanks for the heads up on setting `case_socks` that might help with future testing.

**Comment by martin-marty** [comment]
```Ran 112 tests in 6.146s

OK (skipped=2)
Destroying test database for alias 'default'...

real	0m8.095s
user	0m7.607s
sys	0m0.072s
```

The above is the result of `time ./quicktest.py` - @koriaf are you still experiencing slow test issues?
If you are, do you use a proxy for your connection?

**Comment by martin-marty** [comment]
Looking further, a change was made around the time of this issue which flipped the defaults so socks has to be explicitly enabled.

**Comment by uhurusurfa** [comment]
@gwasser  Happy to close this?

**Comment by gwasser** [comment]
Thanks for investigating @martin-marty! do we have the socks enabling stuff in the code and/or docs? Just wanted to check before close the ticket.

**Comment by martin-marty** [comment]
@gwasser Hi, I'm not sure if it's in the docs, it's currently a comment block in the code.
```# uncomment if you want to run tests with socks - which is much slover
# case_socks = [False] + [c[0] for c in Queue._meta.get_field('socks_proxy_type').choices]
case_socks = [False]
case_matrix = list(itertools.product(case_methods, case_socks))
```

**Comment by gwasser** [comment]
I think I remember this as some kind of syntax change that caused problems. Has it been handled somewhere else in the code? It seems like the tests have been running much faster recently, if so I think we could just close this ticket.

**Comment by martin-marty** [comment]
@gwasser Sorry, I didn't look any furhter, saw a 'fix' was in place and reported back. I'd say close for now and re-address later if needed.
