### ISSUE TITLE
demo login not working

### ISSUE THREAD

**Issue by hiaselhans** [django-helpdesk/django-helpdesk#916]
**Describe the bug**

http://django-helpdesk-demo.herokuapp.com/accounts/login/?next=/

```
Not Found

The requested resource was not found on this server.
```

**To Reproduce**

1. Go to http://django-helpdesk-demo.herokuapp.com/accounts/login/?next=/

**Comment by gwasser** [comment]
Yes I'm working on updating the demo to show off the beta to our new version 0.3, hope to have it up and running soon!

**Comment by gwasser** [comment]
This was fixed with a recent pull request, and I updated the demo. You should be able to login now. Thanks!

**Comment by JMIdeaMaker** [comment]
Which pull request?
