### ISSUE TITLE
French translation issue

### ISSUE THREAD

**Issue by HugoDelval** [django-helpdesk/django-helpdesk#918]
**Describe the bug**

In french `Queue` is `File` as said here: https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/locale/fr/LC_MESSAGES/django.po#L72-L73

But `File` is also another english word (meaning document), in french `File` is `Fichier` : https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/locale/fr/LC_MESSAGES/django.po#L824-L825

I think this is the root issue of the weird behaviour bellow (see how the first label of the form is `Fichier` and not `File`):

![image](https://user-images.githubusercontent.com/9109308/103562684-c2dc4b00-4ebb-11eb-826f-b01ffc041aee.png)

**To Reproduce**
1. Set the django locale to french
2. Click on 'Nouveau ticket' (create a ticket in english)
3. See the wrong translation `Fichier` instead of `File`

**Expected behavior**
The label should be `File`, this is disturbing because it uses another completely unrelated word (`Fichier`)

**Desktop (please complete the following information):**
 - OS: archlinux
 - Browser: chromium
 - Version django-helpdesk==0.3.0b2, latest chromium

**Additional context**

Maybe this is due to my browser, but the other translations look fine, I don't understand...

**Comment by gwasser** [comment]
One thought that comes to mind is that 0.3.0 is a significant change from
the 0.2 series and the translations may not be "good" anymore. I'd have to
update the base translations in transifex and see if any of it needs fixing.

**Comment by Benbb96** [comment]
I remember fixing that issue but it was probably on my own fork.

This is caused by this line : https://github.com/django-helpdesk/django-helpdesk/blob/63790c5b1df1f5c745cfa100196166c9d7a21a42/helpdesk/templates/helpdesk/create_ticket.html#L37

The label is translated twice : in the model definition and also on the template. I can make a PR to fix that !

**Comment by gwasser** [comment]
Thanks very much! I didn't catch that. Double translating will definitely do it.

**Comment by HugoDelval** [comment]
wow good catch, thanks!
