### ISSUE TITLE
TicketCustomFieldValue Boolean (if not required) does not set in EditTicketForm

### ISSUE THREAD

**Issue by alligatorbait** [django-helpdesk/django-helpdesk#926]
**Describe the bug**
When a Custom Field Value is created as Boolean and is Not Required the value never sets. If Required the value is only allowed to be set to true.

django-helpdesk        0.3.0b3
Django                 3.1.5

**To Reproduce**
Create a Custom Field as Boolean and Not Required.
Try setting the value and saving a ticket. When you are in the Ticket edit screen it is always checked as True by default, but when you save and view the ticket it is always False.
Set the Custom Field as Required and repeat the above steps and the system forces you to set the boolean as true, it cannot be set to false.

I did not look into the code to determine where the problem is, so if someone is already familiar and can make the change, much appreciated.

**Comment by alligatorbait** [comment]
Required on boolean is expected behavior in Django, focusing on when Required is not set now.

https://docs.djangoproject.com/en/3.1/ref/forms/fields/#booleanfield

`Since all Field subclasses have required=True by default, the validation condition here is important. If you want to include a boolean in your form that can be either True or False (e.g. a checked or unchecked checkbox), you must remember to pass in required=False when creating the BooleanField.`

**Comment by alligatorbait** [comment]
For the BooleanField I found the following:
`initial = True` renders an HTML input that uses True as the checked value. If initial is False the default checked value is False and thus checked or unchecked the POST sends a value that translates to False in Python.
`required = True` renders HTML that requires the checkbox to be checked.

In HTML the input tag uses the `checked` key to indicate the checkbox should be checked. I haven't figured out how to change that using the BooleanField or CheckboxInput Widget yet.
`<input type="checkbox" name="custom_whatever" class="form-control" id="id_custom_whatever" checked="">`

Anyone know how this works? I'm spending a lot of time trying to figure this out, figure someone knows...

**Comment by Benbb96** [comment]
I think I could give it a try 😉

**Comment by Benbb96** [comment]
@alligatorbait I found what was going wrong with the non required Boolean Custom Field. See my PR #927 😉

**Comment by alligatorbait** [comment]
@Benbb96 I totally missed that. Just looked at my log output and I see 'False' and 'True'. I certainly had tunnel vision. Thanks for looking at this and fixing it. I tested and confirm the fix is good! Thanks again.

**Comment by gwasser** [comment]
Thank you @Benbb96 for the fix and @alligatorbait for reporting and testing! I just merged it.
