### ISSUE TITLE
Forms force Date Time Formats, Use DATETIME_FORMAT

### ISSUE THREAD

**Issue by alligatorbait** [django-helpdesk/django-helpdesk#928]
**Is your feature request related to a problem? Please describe.**
Django has a DATETIME_FORMAT  that can be configured and also has a default. Some of the forms in Django-helpdesk force a specific format and may not be what the end users need on a particular installation.

**Describe the solution you'd like**
Remove the forms forced format of Date Time and use the Django configured format.

**Describe alternatives you've considered**
Alternative would be to patch the files for a particular install, but this is not a great option.

**Additional context**
These files force RFC format and "d. E Y" format. I suggest we remove the formatting and utilize Django built in format specifications.
helpdesk/templates/helpdesk/public_view_ticket.html
helpdesk/templates/helpdesk/ticket.html
helpdesk/templates/helpdesk/include/tickets.html
helpdesk/templates/helpdesk/include/unassigned.html
helpdesk/templates/helpdesk/ticket_desc_table.html

**Comment by alligatorbait** [comment]
Formats are still hardcoded in email templates, I did not look into changing those just yet.

**Comment by alligatorbait** [comment]
These are the hard coded formats found in emailtemplate.json to be replaced with DATETIME_FORMAT.
"l j F Y à H:i\"
"l, j. N Y, \\u\\m H:i\"
"l N jS Y, \\a\\t P\"

Noticed I replaced the "r" RFC 5322 format with just Date, changing it to use DATETIME_FORMAT instead.

**Comment by alligatorbait** [comment]
@Benbb96 @timthelion Are either of you using something other than 'en' locale email templates? Do you foresee any issues changing the hard coded emailtemplate.json |date:"...." formats to |date:"DATETIME_FORMAT"  ?

These are the three formats that would be replaced:
1. "l j F Y à H:i"
2. "l, j. N Y, \u\m H:i"
3. "l N jS Y, \a\t P"

**Comment by Benbb96** [comment]
Hi @alligatorbait, I'm only using '_fr_' locale and I made a PR in the past to use the first date format you specified but I don't see any issue to update the `emailtemplate.json` since it won't affect current values in my database.

And yes, I believe it would be cleaner to use `DATETIME_FORMAT` 😉
