### ISSUE TITLE
Comments' search does not work on demo. 

### ISSUE THREAD

**Issue by egelados** [django-helpdesk/django-helpdesk#930]
**Describe the bug**
I installed demo and used it a little. I noticed that followup comments are not searchable. Is it an sqlite issue? This also stands for edited descriptions. Initial description is searchable. But if i add a word to the description does not register on search after that!!! Perhaps a prefilter/cache issue?

**Comment by Benbb96** [comment]
At the moment, the search function doesn't go through each followup comments (cf. [the code](https://github.com/django-helpdesk/django-helpdesk/blob/aeb3bf0762c5c325eb660b2b4bba94d97ca6d58c/helpdesk/query.py#L54)) but maybe it could be improved.

As for the edited description, I've just tried and it's working for me.  
What's your steps to reproduce it ?

**Comment by uhurusurfa** [comment]
@gwasser @Benbb96  - perhaps this should be closed due to lack of feedback?

**Comment by gwasser** [comment]
If there are remaining issues with the search, please let us know with a new ticket!
