### ISSUE TITLE
merged_to field needs help_text

### ISSUE THREAD

**Issue by alligatorbait** [django-helpdesk/django-helpdesk#938]
**Is your feature request related to a problem? Please describe.**
Some users do not find the "Merged to" title to be intuitive enough.

**Describe the solution you'd like**
Add help_text to the `merged_to` field in the `class Ticket` of `models.py` and update migrations as necessary.
`help_text=_('If selected, this ticket will be merged into the selected ticket.'),`

![image](https://user-images.githubusercontent.com/60234929/106806812-a7cd3a00-6625-11eb-8d64-44a33353db7d.png)

**Describe alternatives you've considered**
Renaming the field was another option, but this seems like a simple solution that will work well with minimal effort.

**Comment by Benbb96** [comment]
You're right, the name is not really explicit. But warning : if you edit a ticket and set the `merged_to` field, it won't trigger the real merging action.
To do this, you have to select the tickets you want to merge in the ticket list. Then you would choose which information to keep, and all the followups, ticketcc and attachments will be moved from a ticket to the main one.

So this field in the edit ticket form is not really necessary in fact. It's more for the superuser to correct an error. So maybe the best solution would be to remove it from this form for normal users ?

**Comment by alligatorbait** [comment]
The field could be disabled (grayed out) on the edit screen for display purposes.
OR
The field change could trigger the merging action.

Either option could work, I'm not familiar with how we would accomplish either.

**Comment by Benbb96** [comment]
Yeah I think first option could be nice, I can make a PR for that.
Second might not really be easy to implement since it requires an intermediate page to choose which information to merge.

**Comment by alligatorbait** [comment]
Will you include the help_text on your PR also please.

**Comment by alligatorbait** [comment]
help_text=_('This ticket is merged into the selected ticket.'),

**Comment by Benbb96** [comment]
Yes no problem 😉
