### ISSUE TITLE
Handle carbon copied addresses on tickets submitted via email

### ISSUE THREAD

**Issue by fatbox** [django-helpdesk/django-helpdesk#95]
If a ticket submitted by email has CC'd recipients they are currently ignored. They should be added to the CC list for the Ticket that gets created.

See also GH-18. My feeling right now is that CC'd addresses should have _view only_ permissions to the tickets, but perhaps we can make it a configurable option.

**Comment by gwasser** [comment]
This was implemented as part of #507 so closing. Let me know if you run into any bugs while testing!
