### ISSUE TITLE
Saved queries going out of saved queries on vertical navbar.

### ISSUE THREAD

**Issue by EliasOPrado** [django-helpdesk/django-helpdesk#952]
**Describe the bug**
When clicking on the `Saved Queries` link on vertical navbar, some of the names pop out of it. Making the system unresponsible. I could help if I could knew previously where the file is adding a e.g:`| slice: 75` in the for loop if you are using the plain template system of django.

**To Reproduce**
1. Go to helpdesk demo page;
2. Click on saved queries
3. Scroll down through the names;
4. If you have any big titles you will be able to see some titles going out of the navbar container.

**Expected behavior**
As mentioned before the titles has to be sliced to not have this behaviour or adding an auto-scrolling to their container. 

**Screenshots**
https://drive.google.com/file/d/1y7wc4KufROw1R1qXHZV2OYjfA-l1qK2c/view?usp=sharing

**Desktop (please complete the following information):**
 - MacOS: BigSur
 - Browser: Chrome
 - Version: latest 2021

**Comment by gwasser** [comment]
THanks! What you're looking for is here: https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/templates/helpdesk/navigation-sidebar.html#L25. I'd prefer to have an auto-sized/auto-scroll container than to chop off the name.
