### ISSUE TITLE
IMAP connection fails (possible typo)

### ISSUE THREAD

**Issue by gilbertusMK** [django-helpdesk/django-helpdesk#954]
**Describe the bug**
IMAP connection fails

**To Reproduce**
1. Configure IMAP queue
2. Go to django/python console
3. try:
 ```
from helpdesk.email import process_email
process_email()
```
4. the error would be:
`IMAP4 StartTLS unsupported or failed. Connection will be unencrypted.`

**Expected behavior**
no error

On closer examination file: helpdesk/email.py on line 146 has server.starttl() 
when i changed it to server.starttls() ( [as in imaplib IMAP4.starttls() docs](https://docs.python.org/3/library/imaplib.html)  ) it works.

**Comment by gwasser** [comment]
Interesting that the unit tests missed this typo! Fixed on the `master` branch. Thanks!
