### ISSUE TITLE
User has no usersettings_helpdesk.

### ISSUE THREAD

**Issue by Bastilla123** [django-helpdesk/django-helpdesk#956]
Hello,

i get exception:

User has no usersettings_helpdesk.

I migrate all model incl. 

class UserSettings(models.Model):
    """
    A bunch of user-specific settings that we want to be able to define, such
    as notification preferences and other things that should probably be
    configurable.
    """
    PAGE_SIZES = ((10, '10'), (25, '25'), (50, '50'), (100, '100'))

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="usersettings_helpdesk")

I can see it in postgres database but i get the exception:

Request Method: | GET
-- | --
http://127.0.0.1:8001/tickets/
3.1.7
RelatedObjectDoesNotExist
User has no usersettings_helpdesk.
/home/sebastian/.local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py, line 421, in __get__
/usr/bin/python3
3.8.5
['/home/sebastian/PycharmProjects/verwaltung',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/home/sebastian/.local/lib/python3.8/site-packages',  '/home/sebastian/PycharmProjects/helpdesk/django-helpdesk',  '/home/sebastian/PycharmProjects/helpdesk/django-helpdesk/demo',  '/usr/local/lib/python3.8/dist-packages',  '/usr/lib/python3/dist-packages',  '/usr/lib/python3.8/dist-packages']
Wed, 31 Mar 2021 12:48:05 +0000

**Comment by gwasser** [comment]
Is this a new installation? Please be sure your Django project is
initialized before installing django-helpdesk.

**Comment by Bastilla123** [comment]
I found the problem. I build this app in my own app but on old users there are no now entrys created in usersettings model. When i create a new user with createsuperuser then also a new entry in usersettings is created.
