### ISSUE TITLE
Turkish localization

### ISSUE THREAD

**Issue by csengor** [django-helpdesk/django-helpdesk#957]
Hello,
I am developing [a computer-assisted translation tool in Django/Electron](https://github.com/kaplanPRO/kaplan-desktop) and stumbled upon django-helpdesk a few days ago, while looking for a ticket platform to handle user queries and whatnot. Firstly, great job with the Django app!
I see that there are 500+ strings that have not been localized into Turkish. As a translator/opensource-enthusiast, I would like to offer help. I've already submitted a request to join the Turkish team on Transifex. My username on Transifex is [csengor](https://www.transifex.com/user/profile/csengor/). If the django-helpdesk account on Transifex is no longer managed, I can, alternatively, translate the .po file using the CAT tool I'm developing and create a pull request.
Best,

**Comment by gwasser** [comment]
Hello @csengor! Thank you for offering to update the Turkish translations! I'm sorry I didn't see this sooner, for some reason I did not receive an email notification so didn't know you submitted a request. I just approved you on Transifex so please feel free to use it and open a pull request when you're ready to submit. Thanks again!
