### ISSUE TITLE
Problems integrating Helpdesk html with project

### ISSUE THREAD

**Issue by ebeers-png** [django-helpdesk/django-helpdesk#960]
Hi, I'm having some trouble integrating helpdesk's html with my project. I'd like to add my project's sidebar to helpdesk and edit the header. For some reason though, the HTML of helpdesk in my project doesn't match the demo's HTML or the code in the GitHub repo, so I'm at a bit of a loss. I'm somewhat new to Django apps (helpdesk was added by another member of my team), so I could be missing something, but could someone point me in the right direction on how to get this to work?

Unedited, my page looks like this:

![image](https://user-images.githubusercontent.com/53191386/116450648-8a28fe80-a829-11eb-8223-31903ef5b476.png)

I can add some header edits and helpdesk's own sidebar code to files named navigation.html and base.html. The result looks like this:

![image](https://user-images.githubusercontent.com/53191386/116451200-310d9a80-a82a-11eb-84b0-c7c12d98aee7.png)

The HTML appears to be wholly different from helpdesk's, and I'm not sure why, or where it's coming from.

![image](https://user-images.githubusercontent.com/53191386/116451406-6c0fce00-a82a-11eb-9ea4-ff8d4741ce28.png)

Any pointers on where the issue might be coming from would be much appreciated!

**Comment by gwasser** [comment]
Offhand, I'd guess you might be mixing the version 0.2 and version 0.3 html
templates. The demo website uses the 0.3 version beta, check out:
http://django-helpdesk-demo.herokuapp.com/ and see if that's closer to what
you're seeing in terms of the sidebar to confirm. 0.3 hasn't been
officially release yet but is in a beta state. it's what you'd see in the
master branch.

**Comment by ebeers-png** [comment]
Yup, you're right! It looks like I was searching GitHub in the wrong places for the 0.2 code that we're using. Hopefully it'll be smooth sailing from here - thanks so much for the quick response!
