### ISSUE TITLE
Email not sending when a ticket is updated

### ISSUE THREAD

**Issue by rifat0rahman** [django-helpdesk/django-helpdesk#962]
**Describe the bug**

I configured the app using the official documentation and everything is working fine except the email sending issue, I saw a lot of problem on the Github but doesn't match with me.

the problem doesn't show any error but says:
`template "updated_submitter" does not exist, no mail sent`
`template "updated_cc" does not exist, no mail sent`

can anyone help me to fix that?
thank you in advance

**Comment by Benbb96** [comment]
Did you run this command `python manage.py loaddata emailtemplate.json` ?
What's you `LANGUAGE_CODE` ?

**Comment by rifat0rahman** [comment]
> Did you run this command `python manage.py loaddata emailtemplate.json` ?
> What's your `LANGUAGE_CODE` ?

I did  `python manage.py loaddata emailtemplate.json`  and still not working. 
my language code is `en-us`

**Comment by Benbb96** [comment]
Can you confirm that there are records in the `helpdesk_emailtemplate` table in your database ?

My bad, the setting `LANGUAGE_CODE` is not taken into account. What's important is the value you set for the locale in your queue (or the setting `HELPDESK_EMAIL_FALLBACK_LOCALE`), it should be `en` to work for English.

You can see the code for it here : https://github.com/django-helpdesk/django-helpdesk/blob/a8ae89ce232b902ad94861e054125fe633b9c40e/helpdesk/templated_email.py#L58

**Comment by rifat0rahman** [comment]
> Can you confirm that there are records in the `helpdesk_emailtemplate` table in your database ?
> 
> My bad, the setting `LANGUAGE_CODE` is not taken into account. What's important is the value you set for the locale in your queue (or the setting `HELPDESK_EMAIL_FALLBACK_LOCALE`), it should be `en` to work for English.
> 
> You can see the code for it here :
> 
> https://github.com/django-helpdesk/django-helpdesk/blob/a8ae89ce232b902ad94861e054125fe633b9c40e/helpdesk/templated_email.py#L58

I have a table in my database `helpdesk_emailtemplate` , I donno what to do!!

is there any solution for override the function for updating tickets? or any solution?

**Comment by rifat0rahman** [comment]
> Can you confirm that there are records in the `helpdesk_emailtemplate` table in your database ?
> 
> My bad, the setting `LANGUAGE_CODE` is not taken into account. What's important is the value you set for the locale in your queue (or the setting `HELPDESK_EMAIL_FALLBACK_LOCALE`), it should be `en` to work for English.
> 
> You can see the code for it here :
> 
> https://github.com/django-helpdesk/django-helpdesk/blob/a8ae89ce232b902ad94861e054125fe633b9c40e/helpdesk/templated_email.py#L58

the problem is solved , I created a new project with follow up the docs again. It solved it. I think the problem was I did not add my domain name in the first Sites name in admin panel
thanks for replying.
