### ISSUE TITLE
Pip install auto-downgrades django to 2.2.24

### ISSUE THREAD

**Issue by duendwang** [django-helpdesk/django-helpdesk#968]
**Describe the bug**
Installing in existing project. When running pip install django-helpdesk, it automatically uninstalled the django 3.2 that I had installed and installed django 2.2.24.

**To Reproduce**
start venv in powershell. Run pip install django-helpdesk

**Screenshots**
https://imgur.com/a/MvuBGta
I've attached 3 screenshots. The first 2 are the output in Powershell after running pip install and upgrading django back to 3.2. The third is the output of pip freeze.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] W10
 - Browser [e.g. chrome, safari] Chrome

**Comment by gwasser** [comment]
This isn't an error, the current django-helpdesk release requires Django
2.2 and doesn't technically support Django 3.

However, our next release of django-helpdesk will support Django 3.2 and
should be released very soon.

**Comment by duendwang** [comment]
Ah understood. Thank you.

So for now, is upgrading Django back to 3.2 ok?

 

David

**Comment by gwasser** [comment]
It might not work if you use Django 3, but I'm not sure. The next
django-helpdesk release specifically supports Django 3. You can try the
beta version (0.3.0b3) from pypi with Django 3 if you'd like, feedback is
appreciated to iron out serious bugs before final release.

**Comment by duendwang** [comment]
Oh ok. I'll try out the beta. Thanks.

**Comment by duendwang** [comment]
Great! thank you!
David
