### ISSUE TITLE
Redundant cc code in email.py?

### ISSUE THREAD

**Issue by ebeers-png** [django-helpdesk/django-helpdesk#969]
**Describe the bug**
I'm doing some work on helpdesk/email.py for a fork of Helpdesk. I noticed that the work done in [lines 507-516](https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/email.py#L507) don't seem to have any effect, and when run, the block doesn't parse the emails from `message.get_all('cc', None)` properly in one case.

The block seems to be leftover from some rework commits, since the variable `cc` isn't used elsewhere; later on, the line 360 creates a list of addresses correctly and in fewer lines.

Is there a reason for this code block to be here? Or can I remove it without issue?

**To Reproduce**
Here's a reproduction based on one email I imported. For this email, on line 507, `message.get_all('cc', None)` produces this list of length 1 (I've randomized the names/domain):
```
[
    '"Brunet, Angelus (ABC)" <Angelus.Brunet@abc.com>, "Durant, Lawrence ABC)"\r\n\t<Durant.Lawrence@abc.com>, "Abrami, Henri (ABC)" <henri.abrami@abc.com>, \r\n\t"Barta, Kai (ABC)" <Kai.Barta@abc.com>'
]
```

Using that value for `cc`, and replacing line 510's `message.get_charset()` with `None`, the final result on line 516 splits on the commas inside the names, and it doesn't strip `\r\n\t` from one of the strings.
```
{
    '"Barta',
    'Kai (ABC)" <Kai.Barta@abc.com>',
    '"Durant', 
    'Angelus (ABC)" <Angelus.Brunet@abc.com>',
    '"Abrami',
    'Henri (ABC)" <henri.abrami@abc.com>',
    '"Brunet',
    'Lawrence ABC)"\r\n\t<Durant.Lawrence@abc.com>'
}
```

**Expected behavior**
I would expect the block to instead produce the following:
```
{
    '"Barta, Kai (ABC)" <Kai.Barta@abc.com>', 
    '"Brunet, Angelus (ABC)" <Angelus.Brunet@abc.com>', 
    '"Abrami, Henri (ABC)" <henri.abrami@abc.com>',
    '"Durant, Lawrence (ABC)" <Lawrence.Durant@abc.com>'
}
```

**Additional context**
My fork of email.py is up to date with the latest commit in the master branch. I'm debugging email.py locally, by running `./manage.py get_email` with a real email address using IMAP.

**Comment by timthelion** [comment]
Re: the cc code. There used to be code that used that variable, it was removed in this commit: https://github.com/django-helpdesk/django-helpdesk/commit/5f0d22a692df963580d24f32fb9ec4802b677843#diff-fc8fbd08361454d941ea50755b4864511012b23e0ad1f4cfe2df63bd62b28043L405

**Comment by gwasser** [comment]
It can probably be removed without issue, sounds like it got leftover during a refactoring at some point. Thanks for spotting it! Feel free to submit a PR to fix this upstream, we appreciate bug fixes too.

**Comment by ebeers-png** [comment]
Thanks, I'll take it out of my fork then! 

I'll try to submit a PR after I finish working on the file! I've cleaned up some other little importing bugs for my fork that I'm sure would be useful to the master branch :)

**Comment by gwasser** [comment]
thanks @ebeers-png a PR would definitely be welcome to help clean up the master branch before officially releasing it as 0.3.0.

**Comment by gwasser** [comment]
This was cleaned up for our next release (0.5), check out the `unstable` branch.
