### ISSUE TITLE
Introduce abstract models to allow entensibility 

### ISSUE THREAD

**Issue by pandafy** [django-helpdesk/django-helpdesk#971]
**Is your feature request related to a problem? Please describe.**
Creating abstract models will ease extensibility in downstream projects. It will avoid the need for re-declaring models for modifying fields. 

**Describe the solution you'd like**
Supporting [swappable models](https://github.com/openwisp/django-swappable-models) along with abstracting core model logic will be a great improvement. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by gwasser** [comment]
Interesting idea! Worth looking into, but probably not until after our next release. (0.3.0)

**Comment by uhurusurfa** [comment]
Adding swapable models will have significant consequences and unlikely there is a very compelling argument to make it possible, the better solution is to request enhancements to the Helpdesk code base.
Swapable models will require extensive code changes to make it relatively seemless for the core application to work without having to modify the core classes and methods to manage any new fields added and this is a huge task.
