### ISSUE TITLE
Use django signals for performing operations on related objects

### ISSUE THREAD

**Issue by pandafy** [django-helpdesk/django-helpdesk#975]
**Is your feature request related to a problem? Please describe.**
I see many instances where related objects are saved/modified in save operation of other object. This logic should be detached form using django signals. 

**Describe the solution you'd like**
Use Django's [post_save](https://docs.djangoproject.com/en/3.2/ref/signals/#django.db.models.signals.post_save) signal to create relate objects and sending email notifications.

**Comment by timthelion** [comment]
Honest question: why?

**Comment by pandafy** [comment]
I believe it will improve extensibility of the project.

**Comment by gwasser** [comment]
This is definitely worth exploring but will require some significant code changes I think. Will put it on the list for a future major version. Thanks for the suggestion!

**Comment by uhurusurfa** [comment]
@pandafy - feel free to raise a PR to start moving towards this pargidgm if you really want to make it happen.
