### ISSUE TITLE
ticket.ticket_url

### ISSUE THREAD

**Issue by pjanzen** [django-helpdesk/django-helpdesk#979]
In the templates the {{ ticket.ticket_url }}. This points to http://example.com of course my site is called differently.

How and where do I change this? There is no mention in the docs.

Thanks.

**Comment by timthelion** [comment]
This isn't a bug ;) you just need to have it configured correctly. The code you're looking for is here: https://github.com/django-helpdesk/django-helpdesk/blob/3f245871ac91356fd91a4e2cea5048bcac1d833e/helpdesk/models.py#L709

all you need to do is change the configuration of django sites (in the admin) and restart the server. Hope this helps...

**Comment by pjanzen** [comment]
yeah, sorry about that. Of course I need to update the site to the correct URL..

**Comment by gwasser** [comment]
can we update the docs to help with this? even just to let folks know it's something that needs done, and point to the django docs on how to set it. anyone have a good link to the django docs handy?
