### ISSUE TITLE
Tuple of tuple used for `assigned_to`

### ISSUE THREAD

**Issue by code-review-doctor** [django-helpdesk/django-helpdesk#988]
**Describe the bug**
Tuple of tuples passed into `assigned_to` because unwanted comma on line 854:

https://github.com/django-helpdesk/django-helpdesk/blob/09494e961ea00b2715c97c415e3bf8edeff4a975/helpdesk/views/staff.py#L853-L854

and as far as I can tell, `assigned_to` should instead be a tuple containing 2 items, but instead evaluates to:
```
(('closed_owner', context),)
```
The impact is expect error to happen when this code is hit: https://github.com/django-helpdesk/django-helpdesk/blob/09494e961ea00b2715c97c415e3bf8edeff4a975/helpdesk/models.py#L647

The error will be  `ValueError: not enough values to unpack (expected 2, got 1)`

**Expected behaviour**
Extra comma should be removed so it's just `('closed_owner', context)`.

**Additional context**
I am a static analysis bot that found this issue automatically (but my maintainer raised this ticket).

I can raise a PR to fix this for you

**Comment by timthelion** [comment]
I say the bot is probably right. I commit that code https://github.com/django-helpdesk/django-helpdesk/commit/09d8f8c488f6781d7641f45b187881eb424c501b#diff-206db4cdb6cf21b5ed528d9c5ebf6be95c221a1da93bbf1d2470521af208774eR740 and I'm sure I would never do something tricky like that on purpose, I'd always use the full parens for tupleization.

**Comment by gwasser** [comment]
I removed the comma in a commit on `stable`, thanks @code-review-doctor
