### ISSUE TITLE
How to fix Errors: fields.E300, fields.E307?

### ISSUE THREAD

**Issue by ak2ree** [django-helpdesk/django-helpdesk#992]
I downloaded project and connect to my project like in guide Installation. then i started migrate helpdesk project and i have this issue
**ERRORS:
helpdesk.KBItem.team: (fields.E300) Field defines a relation with model 'pinax_teams.Team', which is either not installed, or is abstract.
helpdesk.KBItem.team: (fields.E307) The field helpdesk.KBItem.team was declared with a lazy reference to 'pinax_teams.team', but app 'pinax_teams' isn't installed.**

System check identified 2 issues (0 silenced).
I assure that i've already installed pinax_teams package

**Comment by Benbb96** [comment]
Did you add it to your `INSTALLED_APPS` like it is said in the docs : https://github.com/django-helpdesk/django-helpdesk/blob/stable/docs/install.rst#adding-to-your-django-project

**Comment by uhurusurfa** [comment]
@gwasser @Benbb96  Close this die to lack of feedback? Seems like it is a config error on the end users part anyway.

**Comment by gwasser** [comment]
I probably kept it open to double check that the docs were clear, but I think OK to close.

**Comment by Alijon142** [comment]
Pashol naxuy
