### ISSUE TITLE
How to create/signup a new user in help desk ?

### ISSUE THREAD

**Issue by bharathjinka09** [django-helpdesk/django-helpdesk#997]
Hi all,

I am trying to create a user, but it is showing only the login button in the navbar.

There is no signup button. How a user will signup ? I got stuck here. Will you please share the related docs? It will be very useful.

Thank you so much for the awesome product

**Comment by Benbb96** [comment]
Hi @bharathjinka09,

By default, you can add a new user from the admin module.

Then if you really need to have a signup page, you can implement it in your Django project (cf. this tutorial : https://learndjango.com/tutorials/django-signup-tutorial)

**Comment by bharathjinka09** [comment]
Thanks for your reply

Thanks and Regards

J. Ranga Bharath
Cell: 9110334114

**Comment by gwasser** [comment]
RIght now django-helpdesk does not have a new user account sign up page. You could make one yourself with Django as @Benbb96 shared, or there are potentially other django packages you could use to create user account sign up pages with password resets, etc., done correctly and securely. We could potentially add a user account feature in the future if there's a need and demand for it, but right now the easiest is for the administrator to add users. You don't need to be a user to fill out a report using the software.
