### ISSUE TITLE
User Settings-issue

### ISSUE THREAD

**Issue by afranjin** [django-helpdesk/django-helpdesk#998]
**Describe the bug**
Typo in view wrong model field name.

Steps to reproduce:   
1\.Log in with user(role-admin)   
2\.User Settings   
\-Uncheck "E-mail me on ticket change?"   
3\.Helpdesk   
4\.New Ticket   
\-Leave empty "Case owner"   
5\.Submit Ticket   
6\.Dashboard   
7\.Click "Take" button for previously created Ticket   
Issue:   
AttributeError at /tickets/10/
'UserSettings' object has no attribute 'email_on_ticket_assigned'
Request Method: | GET
-- | --
http://127.0.0.1:8080/tickets/10/?take
3.2.12
AttributeError
'UserSettings' object has no attribute 'email_on_ticket_assigned'
/Users/antunfranjin/repos/helpdesk./django-helpdesk/helpdesk/views/staff.py, line 712, in update_ticket
/Users/antunfranjin/repos/helpdesk./helpdeskvenv/bin/python3.9
3.9.5
['/Users/antunfranjin/repos/helpdesk./helpdeskvenv/bin',  '/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python39.zip',  '/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9',  '/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload',  '/Users/antunfranjin/repos/helpdesk./helpdeskvenv/lib/python3.9/site-packages',  '/Users/antunfranjin/repos/helpdesk./django-helpdesk',  '/Users/antunfranjin/repos/helpdesk./django-helpdesk/demo']
Fri, 11 Mar 2022 09:52:18 +0000

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version Version 98.0.4758.109 (Official Build) (arm64)

**Comment by afranjin** [comment]
https://github.com/django-helpdesk/django-helpdesk/pull/999

**Comment by gwasser** [comment]
Thank you for catching the typo! The fix should be merged with #999.
